### ISSUE TITLE
Add visual feedback for format keyboard shortcut

### ISSUE THREAD

**Issue by ydlamba** [vega/editor#110]
Same click button effect like we have done for parsing?

**Comment by ydlamba** [comment]
After the new top bar, we need to add visual feedback for parsing/formatting again.

**Comment by domoritz** [comment]
👍

**Comment by algomaster99** [comment]
@domoritz Can you please explain what this issue is about? :) I could work on this probably.

**Comment by domoritz** [comment]
When you format the code for example with a keyboard shortcut, there is no visual indicator. Same for running a spec btw.

**Comment by siddhant1** [comment]
I thinkthis can also be closed @domoritz
