### ISSUE TITLE
docker-compose build fails on Windows 

### ISSUE THREAD

**Issue by Jasperhino** [vega/editor#1107]
![image](https://user-images.githubusercontent.com/33397387/145957287-8882dcc8-41f6-44e0-afa0-ca838fdd97d6.png)
When I clone the repo and run `docker-compose build` it fails with the following bundle error.

Can someone help me, or tell me what's wrong here?

**Comment by domoritz** [comment]
I can't but maybe we should add support for vscode dev containers instead. For now, I will remove the docker compose script.
