### ISSUE TITLE
option to include config in Share dialog

### ISSUE THREAD

**Issue by declann** [vega/editor#1108]
This option in present in Export dialog for JSON exports (below, embeds config into the bottom of the spec).

Share dialog involves URLs and Gists. Certainly with Gists, there is a further question of using a separate config.json (and reflecting where Gists are loaded) versus embedding into the spec.

![2021-12-18 (4)](https://user-images.githubusercontent.com/353214/146657320-1ae4b6ea-b121-4692-9d5e-680d319b1aee.png)

**Comment by domoritz** [comment]
I think that adds too much complexity and we already have support for merging the config into the spec via editor actions.
