### ISSUE TITLE
Docker Compose is missing

### ISSUE THREAD

**Issue by rgaiacs** [vega/editor#1231]
README says that a Docker Compose setup is available but no `docker-compose.yaml` is in the repository.

**Comment by domoritz** [comment]
Right, I removed that since it wasn't working reliably and it's also not really needed. Can you send a pull request to remove the references?

**Comment by rgaiacs** [comment]
The repository still has a `Dockerfile` file. Is the `Dockerfile` working?

**Comment by domoritz** [comment]
Right. I think it works but I don't maintain it so I removed it in https://github.com/vega/editor/commit/b1aabe5001bdc4bb589fce2c6e1776840ae10f90 to avoid any confusion. Thanks for raising the issue.
