### ISSUE TITLE
Usage Instructions Fail for Local Installation on Windows

### ISSUE THREAD

**Issue by PBI-David** [vega/editor#1242]
I'm following the instructions from https://github.com/vega/editor. I have run yarn and yarn start. I'm getting the following error. 
```

PS C:\Users\XXX\OneDrive\Documents\GitHub\editor> yarn start
yarn run v1.22.19
$ webpack serve --mode development
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] Content not from webpack is served from 'C:\Users\XXX\OneDrive\Documents\GitHub\editor\public' directory
ERROR in ./src/constants/specs.ts 1:26-70
Module not found: Error: Can't resolve '../../public/spec/vega/index.json' in 'C:\Users\XXX\OneDrive\Documents\GitHub\editor\src\constants'
 @ ./src/constants/index.ts 1:0-54 1:0-54 1:0-54
 @ ./src/components/app.tsx 11:0-44 102:21-30 105:26-39 122:33-42 125:38-51 139:44-63
 @ ./src/components/app-shell.tsx 3:0-24 9:80-83 11:73-76 12:98-101 13:103-106 14:95-98 15:95-98 16:107-110 17:101-104 18:79-82 19:88-91
 @ ./src/index.tsx 8:0-46 22:28-36

ERROR in ./src/constants/specs.ts 2:31-80
Module not found: Error: Can't resolve '../../public/spec/vega-lite/index.json' in 'C:\Users\XXX\OneDrive\Documents\GitHub\editor\src\constants'
 @ ./src/constants/index.ts 1:0-54 1:0-54 1:0-54
 @ ./src/components/app.tsx 11:0-44 102:21-30 105:26-39 122:33-42 125:38-51 139:44-63
 @ ./src/components/app-shell.tsx 3:0-24 9:80-83 11:73-76 12:98-101 13:103-106 14:95-98 15:95-98 16:107-110 17:101-104 18:79-82 19:88-91
 @ ./src/index.tsx 8:0-46 22:28-36

webpack compiled with 2 errors
```

As an aside, I have also cloned vega-lite and intend to link the two. Will this allow me to set breakpoints and step through the vega-lite code?

**Comment by domoritz** [comment]
It looks like the vendor script didn't run correctly: https://github.com/vega/editor/blob/ae80f89429806a86fb1e25dab5100a600e267d8a/package.json#L94. 

I don't test the setup on windows so you will need to debug the script. 

Yes, once you link, you can modify Vega-Lite and set breakpoints as well. However, if you just want to set breakpoints, you can even do that in the deployed editor.

**Comment by PBI-David** [comment]
I'll investigate and report back. When you say "However, if you just want to set breakpoints, you can even do that in the deployed editor", can you please expand on that?

**Comment by domoritz** [comment]
Closing for now since we don't officially support windows.
