### ISSUE TITLE
Vega-Lite to Vega should open Vega spec

### ISSUE THREAD

**Issue by domoritz** [vega/editor#128]
Right now we clear the spec and show an empty Vega spec.

**Comment by ydlamba** [comment]
We already have a way to switch to Vega spec.

**Comment by domoritz** [comment]
Yeah, but why not just open the corresponding Vega spec when you change the type?

**Comment by algomaster99** [comment]
@domoritz We already have a compiled vega spec pane right? So what is the need?

**Comment by domoritz** [comment]
When you switch from Vega-Lite to Vega through the dropdown, we should not clear the spec and instead open the compiled Vega spec.
