### ISSUE TITLE
Label Transform is not positioning the labels properly (anymore)

### ISSUE THREAD

**Issue by anton-bulyenov** [vega/editor#1332]
I'm using the following vega spec to render the labels — https://vega.github.io/editor/#/gist/860f696e9be11fc454f881c69798532b/label-vega-spec.json

Previously, labels were positioned above the rectangles of the bar chart, but as of 2 weeks ago, it stopped working and all of the labels are squished to the top right corner. The issue is reproducible on different browsers and OSs. I suspect it's related to label transform but I'm not entirely sure.

So far, it could be a bug of both editor and vega itself

**Comment by domoritz** [comment]
Can you figure out whether it's a bug in Vega or the editor?

**Comment by domoritz** [comment]
Related https://github.com/vega/vega/issues/3746

**Comment by anton-bulyenov** [comment]
Confirmed. This issue occurs in the editor only. I've played with both vega.js 5.24 and 5.25 — the bug is not reproducible here (here's [a link](https://codepen.io/bulyonov/pen/RwejQzP) to the chart using 5.24)

**Comment by domoritz** [comment]
It's probably a version mismatch. We need to update all the versions.

**Comment by anton-bulyenov** [comment]
Based on what I'm seeing in the editor's source code, it is already at 5.25. Perhaps, the editor needs to be released on githib.io
