### ISSUE TITLE
Unnecessary white pane

### ISSUE THREAD

**Issue by ydlamba** [vega/editor#134]
![screenshot_20180715_190153](https://user-images.githubusercontent.com/21237466/42734444-8de9965a-8861-11e8-8f9f-8acf5555bda8.png)

**Comment by domoritz** [comment]
How do you get this?

**Comment by ydlamba** [comment]
Resize the complied vega spec header without instead of clicking on it.

**Comment by siddhant1** [comment]
Its certainly the same as #244 , I will be taking a look on this

**Comment by domoritz** [comment]
Great. We can close two issues when this is fixed.
