### ISSUE TITLE
Line Comment shortcut ctrl+/ does not work on Windows

### ISSUE THREAD

**Issue by Salat23** [vega/editor#1343]
**Vega-Editor d0ef006**

In the [Vega Editor](https://vega.github.io/editor/#/edited), The command `ctrl + /` does not work on a Windows machine. When I press it, simply nothing happens.

I have verified that the exact same command does work in an online JupyterLab editor [here](https://jupyter.org/try-jupyter/lab/?path=notebooks%2FIntro.ipynb), in the exact same browser.

Using the following browser and OS:
- Google Chrome 114.0.5735.134 (Official Build) (64-bit) (cohort: Stable) 
- Windows 11 Version 22H2 (Build 22621.1848)

**Comment by domoritz** [comment]
I don’t have a windows machine to test. Can you send a fix?

**Comment by Salat23** [comment]
Not sure if that was directed at me as the original poster or at someone else? If me, could you clarify what you mean by "a fix"? Obviously if I knew how to fix it I wouldn't be creating the issue in the first place (or I would indicate that in the issue description :-) ).

**Comment by domoritz** [comment]
Yeah, I was asking whether you’d be willing to try to send a pull request with a fix. I’d be able to answer questions here so it’s generally useful to make an issue before sending a pull request. 

I think one question to answer is whether this is an issue with Monaco itself rather than the editor. Did you test other Monaco editors on other websites?

**Comment by domoritz** [comment]
Here https://microsoft.github.io/monaco-editor/.

**Comment by Salat23** [comment]
Alright, so this has been resolved. Just in case someone else runs into this in the future, here's the solution:

- The correct shortcut might be `ctrl + '` rather than `ctrl + /`
- The shortcut might be "overtaken" by 1Password which will prevent it from being effective. Changing to a different shortcut in the 1Password settings will make it work again.
