### ISSUE TITLE
Make sure the Vega editor with Vite works with linked Vega and Vega-Lite packages

### ISSUE THREAD

**Issue by domoritz** [vega/editor#1346]
Developers, for now, roll back to a pre-vote version: 53b8515f8adef9fb2aa3b578c8ff7275ddd15969

**Comment by sfc-gh-cheliu** [comment]
@domoritz Hi there! I'm wondering if this caused the error I encountered https://github.com/vega/editor/issues/1366. Thanks.

**Comment by sfc-gh-cheliu** [comment]
@domoritz  I guess this is still `yarn link` issue, appreciate it if you could give some suggestions. Thanks.

**Comment by kanitw** [comment]
Ok I thought something is wrong with my computer.  lol

**Comment by domoritz** [comment]
I think we are running into https://github.com/vitejs/vite/issues/8619. I got it mostly working but you need to save your Vite config file right now. The plus is that you don't even need to rebuild or watch Vega-Lite anymore.
