### ISSUE TITLE
Public Facing Vega Editor Not Loading

### ISSUE THREAD

**Issue by crambelsoupy** [vega/editor#1352]
Hi,

It looks like the public facing editor linked from libraries such as [react-vega](https://www.npmjs.com/package/react-vega) and from the [vegalite home page](https://vega.github.io/vega-lite/) is not loading. This is the URL that doesn't load is: [vega editor](https://vega.github.io/editor/#/custom/vega-lite). Is this the relevant repos?

**Comment by domoritz** [comment]
Yep. Can you try with another browser?
