### ISSUE TITLE
Link issue when developing vega-lite and testing local changes in vega editor

### ISSUE THREAD

**Issue by sfc-gh-cheliu** [vega/editor#1366]
I followed the instructions in https://github.com/vega/editor - running `yarn link` in `vega-lite` and `yarn link vega-lite` in `editor`, but there's an error:

![link_error](https://github.com/vega/editor/assets/112987415/c9c5ded8-28b8-4c9c-aac5-4ba139d68f50)

Stacktrace:
(myenv) cheliu@RJFYQ0Y7WX editor % yarn start
yarn run v1.22.19
$ vite serve

  VITE v4.4.9  ready in 369 ms

  ➜  Local:   http://localhost:5173/editor
  ➜  Network: use --host to expose
  ➜  press h to show help
Error:   Failed to scan for dependencies from entries:
  /Users/cheliu/editor/index.html

  ✘ [ERROR] Failed to resolve entry for package "vega-lite". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

-----------------------------------------------------------------------

Fyi, when running `yarn` in `vega-lite`:

(myenv) cheliu@RJFYQ0Y7WX vega-lite % yarn
yarn install v1.22.19
[1/5] 🔍 Validating package.json...
[2/5] 🔍 Resolving packages...
[3/5] 🚚 Fetching packages...
[4/5] 🔗 Linking dependencies...
warning "rollup-plugin-sourcemaps > @rollup/pluginutils@3.1.0" has incorrect peer dependency "rollup@^1.20.0||^2.0.0".
warning " > vega-embed@6.22.2" has unmet peer dependency "vega@^5.21.0".
warning " > vega-embed@6.22.2" has unmet peer dependency "vega-lite@".
warning "vega-embed > vega-themes@2.14.0" has unmet peer dependency "vega@".
warning "vega-embed > vega-themes@2.14.0" has unmet peer dependency "vega-lite@*".
warning "vega-embed@6.22.2" is missing a bundled dependency "yallist". This should be reported to the package maintainer.
[5/5] 🔨 Building fresh packages...
✨ Done in 26.95s.

When running `yarn` in `editor`:

(myenv) cheliu@RJFYQ0Y7WX editor % yarn
yarn install v1.22.19
[1/4] 🔍 Resolving packages...
[2/4] 🚚 Fetching packages...
[3/4] 🔗 Linking dependencies...
warning "react-select > @emotion/react > @emotion/babel-plugin@11.7.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "react-select > @emotion/react > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > react-split-pane@0.1.92" has incorrect peer dependency "react@^16.0.0-0".
warning " > react-split-pane@0.1.92" has incorrect peer dependency "react-dom@^16.0.0-0".
warning " > vega-embed@6.22.2" has unmet peer dependency "vega@^5.21.0".
warning " > vega-themes@2.14.0" has unmet peer dependency "vega@*".
warning " > vega-lite@5.14.1" has unmet peer dependency "vega@^5.24.0".
warning " > autoprefixer@10.4.15" has unmet peer dependency "postcss@^8.1.0".
warning "vega-embed@6.22.2" is missing a bundled dependency "yallist". This should be reported to the package maintainer.
[4/4] 🔨 Building fresh packages...
$ husky install && npx patch-package
husky - Git hooks installed
patch-package 8.0.0
Applying patches...
resize-observer-polyfill@1.5.1 ✔
$ yarn vendor
yarn run v1.22.19
$ scripts/vendor.sh
Copying data to 'public/data'.
Copy examples to 'public/spec'.
/tmp ~/editor
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 17.1M 0 17.1M 0 0 4576k 0 --:--:-- 0:00:03 --:--:-- 5337k
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 24.1M 0 24.1M 0 0 4759k 0 --:--:-- 0:00:05 --:--:-- 5381k
~/editor
✨ Done in 12.31s.
✨ Done in 30.86s.

Should I link `vega` as well? But I encountered this error:

(myenv) cheliu@RJFYQ0Y7WX vega % yarn link
yarn link v1.22.19
error Couldn't find package name.
info Visit https://yarnpkg.com/en/docs/cli/link for documentation about this command.

Any suggestions are appreciated:)

**Comment by joelostblom** [comment]
@lsh I think this is the same error I showed you yesterday. I was going to post the error myself so you had it for reference, but I will defer to the post above instead.

**Comment by sfc-gh-cheliu** [comment]
@joelostblom Not sure if this is related https://github.com/vega/editor/issues/1346, but I've tried cloning an older version of the repo but no luck.

**Comment by domoritz** [comment]
Use the version pre vite for now. I'm working on fixing vite support.

**Comment by sfc-gh-cheliu** [comment]
@domoritz Hey! `pre vite` = https://github.com/vega/editor/commit/53b8515f8adef9fb2aa3b578c8ff7275ddd15969? I actually have tried this but no luck.

**Comment by sfc-gh-cheliu** [comment]
@domoritz  I guess this is still `yarn link` issue, appreciate it if you could give some suggestions. Thanks.

**Comment by sfc-gh-cheliu** [comment]
@domoritz Resolved the dependency issue by switching `vega-lite` back to `5.8.0` and running `yarn build` inside of the `vega-lite` repo. Maybe worth to mention this in the onboarding doc or your ticket.

**Comment by domoritz** [comment]
Thanks for noting that here for anyone who runs into the same issue before I fix things.
