### ISSUE TITLE
Loading the editor initially neither activates vega, nor vega-lite mode

### ISSUE THREAD

**Issue by domoritz** [vega/editor#139]

**Comment by siddhant1** [comment]
@domoritz is this one solved?

**Comment by domoritz** [comment]
Idk. Try clearing your app storage and see what happens.

**Comment by domoritz** [comment]
Yes

expected

<img width="1071" alt="Screen Shot 2019-03-10 at 21 09 41" src="https://user-images.githubusercontent.com/589034/54094653-df1f0780-4378-11e9-9680-23c771fabfe3.png">


actual

<img width="1068" alt="Screen Shot 2019-03-10 at 21 09 36" src="https://user-images.githubusercontent.com/589034/54094649-d8909000-4378-11e9-9618-7a573ea836bc.png">

**Comment by domoritz** [comment]
Something is wrong in the initialization.

**Comment by ganeshpatro321** [comment]
@domoritz Can you tell me the steps to reproduce?

**Comment by domoritz** [comment]
You delete your localstorage and refresh the page.
