### ISSUE TITLE
Can't use local version of `vega-transforms` in editor

### ISSUE THREAD

**Issue by julieg18** [vega/editor#1390]
I've been trying to run my local version of `vega/packages/vega-transforms` but the changes are not reflected in the localhost editor. 

I've tried linking the `vega` package, per the readme: 
1. `yarn build` in `vega`
2. `yarn link` in `vega/packages/vega`
3. `yarn && yarn link vega && yarn build && yarn start` in `editor`

I've also tried linking the `vega-transforms` in the `editor` directory or in the `packages/vega` directory but neither worked. Is there a bug or am I misunderstanding how running a local version is supposed to work?

**Comment by domoritz** [comment]
Thanks for the clear bug report. Unfortunately after updating to Vite, there is an issue with linking. You can either downgrade to a specific version before the change or manually restart the server after making a change to the source library. See https://github.com/vega/editor/issues/1346 for details.
