### ISSUE TITLE
Print dates in data viewer

### ISSUE THREAD

**Issue by domoritz** [vega/editor#149]
Check the first column. It should be dates rather than empty objects.

<img width="559" alt="screen shot 2018-08-06 at 10 26 19" src="https://user-images.githubusercontent.com/589034/43731397-39c1a58c-9963-11e8-8475-3d26f2accfec.png">

**Comment by ydlamba** [comment]
View API is giving date data like this -
![screenshot_20180807_002422](https://user-images.githubusercontent.com/21237466/43735440-3c515be2-99d8-11e8-8074-87911d00694e.png)

**Comment by domoritz** [comment]
Hmm, weird. Are they of type `DateTime`, though?

**Comment by ydlamba** [comment]
Looks like yes.

![screenshot_20180807_003437](https://user-images.githubusercontent.com/21237466/43735972-b02c2f46-99d9-11e8-89b5-8bd4855823d0.png)

**Comment by domoritz** [comment]
Then we should be able to show dates better.

**Comment by domoritz** [comment]
@siddhant1 This would also be great for you to look at!

**Comment by siddhant1** [comment]
Looks simple , will have a look

**Comment by domoritz** [comment]
I also pinged you on slack.
