### ISSUE TITLE
Refactor sharing modal

### ISSUE THREAD

**Issue by domoritz** [vega/editor#156]
I had another look at the sharing modal and noticed some issues with the code. Instead of changing the UI in `componentDidUpdate` in `exportURL` for example, we should change things in `render`. To clean things up, we should extract all the modals into their own components.

**Comment by domoritz** [comment]
Not yet done.

**Comment by nandinirai** [comment]
Can I work on this?

**Comment by domoritz** [comment]
Maybe try a smaller issue first.

**Comment by siddhant1** [comment]
I will be talking a look at this , can you explain what needs to be done @domoritz

**Comment by domoritz** [comment]
See the original text. I have not looked at the code since then but I remember that it could be refactored and cleaned up.

**Comment by siddhant1** [comment]
Not able to get this properly , can you explain.
Do I need to make tabs into their specific components?

**Comment by domoritz** [comment]
First, extract components. The header file is huge right now.

**Comment by siddhant1** [comment]
@ganeshpatro321 please comment if you are working , I had already made some progress with it 
Thanks

**Comment by ganeshpatro321** [comment]
Sorry @siddhant1 
There were no PRs since few days for this simple task(extracting the component), so thought no ones working.
