### ISSUE TITLE
Service to generate PDFs

### ISSUE THREAD

**Issue by domoritz** [vega/editor#158]
It would be sweet if we could deploy a service to generate PDFs for Vega or Vega-Lite specs. A simple option could be https://cloud.google.com/blog/products/gcp/introducing-headless-chrome-support-in-cloud-functions-and-app-engine.

If anyone wants to write the code, I'd be happy to deploy it.

**Comment by domoritz** [comment]
Not really urgent. I think fixing the json request service and formatting have higher priority. 

But I though this would be a fun one for someone who isn't familiar with the editor codebase.

**Comment by ydlamba** [comment]
Sounds good.

**Comment by ydlamba** [comment]
Yeah sure. :)

**Comment by domoritz** [comment]
Note that I already set up a bit of server infrastructure: https://github.com/vega/editor/tree/server. It probably makes sense to build on that.

**Comment by domoritz** [comment]
Looks relevant: https://github.com/alixaxel/chrome-aws-lambda

**Comment by nesterone** [comment]
looking

**Comment by domoritz** [comment]
We could use something similar to https://github.com/vega/vega/blob/master/packages/vega-cli/bin/vg2pdf

**Comment by domoritz** [comment]
I added experimental support through https://cloudconvert.com.

**Comment by domoritz** [comment]
Vega 5 now has PDF generation in node built in. We should use that.

**Comment by siddhant1** [comment]
I will pick this one.

**Comment by domoritz** [comment]
@jheer how do you recommend we send the visualization from the editor to a server? Ideally, we also want the interactive state. Should we send the spec, data, and state or can we just send the scenegraph instead? We could also send an SVG.

**Comment by g3o2** [comment]
hmm, I wonder, does this have the potential to cause privacy/confidentiality issues in case of confidential data sent to an external server?

**Comment by domoritz** [comment]
Yes, that's why we make it very clear in the message. I'd like to build my own service so we can make sure no logs are kept.

**Comment by domoritz** [comment]
https://github.com/yuzutech/kroki looks like a good option for this. I talked with @Mogztter and he's supportive of us using it. 

The service does not support fetching URLs so we would need to inline the data.

**Comment by domoritz** [comment]
We are working on this in https://github.com/vega/vega-render-service

**Comment by domoritz** [comment]
Done now.
