### ISSUE TITLE
Tooltips do not appear if VL editor is in fullscreen

### ISSUE THREAD

**Issue by Alcampopiano** [vega/editor#159]
[Click to see](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJgE6Asl2Ex3PJcTcA7oyXUwL3bGSE3WzB0JU0wVEYxHTBCINoxByVYMBZrMG5YpOCwAHFubmooy2R0XSQwADNuXRSUMHhS2rSAT25Weol4AGt0pTo1DUhNa0wcYEhWXTFsLRHSBt95RRUAX3UISAxdLpnIAI88AY28XRDYKt1UGYBtUAgNhrF4VjFrZF2AcnwiEnJXf4Y+UKyDo8G4qD4JTKiAA-ABHAC8HzAAGowMM8KxUHQAHLoVDvVRQdCwXaTaYaFYAXXWUGQSjBmg81Bmd3ukAAHqzIBVGMgxJpdgAJap+AKuWxqKB4ZqxXZw1ghIx4ayMKiQNYaDbNbm8-mC0wAWUiOgA+rFdKacugEsopZAZXLTAqlcxVerNfcoGCHLpdXyBbsAPL6JgqIkO2XvUxKcEeG0a2nHfJiIyEf363Z4gn2x3RqCxiJKBOe9mIXTICoZwOmcm5qO7Qvx6YrSkgVtAA/view)

**Comment by Alcampopiano** [comment]
Hi @domoritz,

Is this closed because it has been fixed? I ask because for some reason I thought I noticed the fix in the online editor, but now I see that tooltips are not appearing. Just letting you know.

**Comment by domoritz** [comment]
It hasn't been deployed yet.
