### ISSUE TITLE
Weird alignment in error log

### ISSUE THREAD

**Issue by domoritz** [vega/editor#165]
<img width="641" alt="screen shot 2018-09-18 at 10 14 55" src="https://user-images.githubusercontent.com/589034/45704441-bfc2c280-bb2b-11e8-9750-b4a8140c1f32.png">

**Comment by domoritz** [comment]
Why is the first line aligned differently?

**Comment by ydlamba** [comment]
I've fixed this locally. Most of the major style issues will be fixed by that single PR.
