### ISSUE TITLE
How to set locale globally

### ISSUE THREAD

**Issue by geohuz** [vega/editor#166]
In vega API doc I saw vega.formatLocale(definition) and vega.timeFormatLocale(definition) to define the locale globally. Is there any way to define this in vega editor?

**Comment by domoritz** [comment]
Not yet. We love pull requests and this would be a great addition.

**Comment by domoritz** [comment]
Actually, you can probably set this from the command line. `vega` is available in `VEGA_DEBUG`. Does this work for you @geohuz?

**Comment by algomaster99** [comment]
@domoritz It can be accessed through `VEGA_DEBUG.vega.formatLocale()`. I think this issue can be closed.

**Comment by domoritz** [comment]
It would be nice to have a UI for this eventually but yes, let's close this.
