### ISSUE TITLE
Data viewer is not updated when data is added or removed by signals

### ISSUE THREAD

**Issue by mattijn** [vega/editor#170]
A few months ago I made the following [use-case](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KAHdGAExbYwADgAMuxREgpG1fFoBM+w1ELo1axjOpaArDchr0eTDgDaShCgECFQMuioyFqe3ugA+oTcTniwCoEhkBToADasyKn+wJAAHpYGUACeWgDsdK4AvvJgRaU4AGzlkFXtdG2NzSVaAJwWTV1a2vUAujahkLJaAaGhRXgATqbUyGvRsGvwClCo3I4AZt1QewdjWbn50Wpr6C6N6SuQ65vb0fZqAApJGR4Q6QJywbbAnCQX4A5KQV7LEKrDbULY7KFrNCwoEgzHHKjRPHY4H1N5gKbpUkQGZKSCwUzhbIFMBLJFkyDhSK7fZpRGZHJ5aIAQi8eFYqF5y3mcn8ZKCkGQVCBzMgAAFRfFEslYAlAXgsMdWOC1NxlHIxqxCKKolDReL4bNlkVFchldFVDITcoDdwjchLSDLdbhXaJVTlhTQgi2XzOTaoI9npK5rdBbbvPbHUYFrLEUE5RkXW6oR6vT6-fjkE1S6by8bTeaC0Yg9545BgMUcE4qGs8AAKADkxQQOWQA6a8GyEUIfeKfYAlE1yqoNIh54uwBUuzIe-2BxUR9kxxOp6gZxUF-IDCYzHh1-VIAXw6FIyFo-nYxE2zC9cmMjmWQLYI8yMIsUmiQ16zNPwwLodhWAIWRYDAAAyFCwFg2BEEYU48AAaWQCpUPQoVYJyfDCKmYArAfLMpRbPA2w7bdd0HYd4FHccwDndcmi3MBuwhQcDw4o8uIve9HxA58QlfCB32adk40JLFfzo6VFiApsoDAlVIOQL0ZBgpU8DghC8CQ4iwFIky6CwnCKKItCMNs8iCIqKiaL-PkGLbUMpLzGTqUpUIlBpIxD3uXMYylZSoXY0dvKgPAKkINtsicZB0B2dSnmcNsV00dSAC9tm4LRThycF1JNDAnEWcoAEZ9DksAFOAuY4sqSKko+VL0sy7LeryrZohvcx1JkRh4HjdY8hKsqtDmqt2Vq9B6v8JrdFa8NwqgdBiiiwCVnZbgNldSEoHYbhEIldSevinr1LwaaAGsAGFfRxHBmue5gj2iAARRhYB8GQZpZVApl66gNjUJa1nm9lXXgE54w6qVYfULQMZ8q1Wxxul1m4V70f5O5ogAYiGGmHUuYnSYAdXUTQcCKVN410OhGvqIK3zoowXvgV7mSKXzCdBtYSbJjnonYKdhfhXmBagKd2GQJkce0yBxbZ7SjFORhsmyQnZaheX0EVhSQOhZwAbZ8m0zAXRrbzSBTlkPAAGVGFK02BXjRqLD5qMnxVj5-rJ3WBg9oEfb9h2zbARrRF512jDWjbFJA5t8cYiWGZlgO5YV166aJqWmZZxB-Ypn7eafMkZPa07zu+1XkFw3qHu60Soj+4XPtYdu2j+vB7agAAJZBTHwSGAGoADkAEE-mh9SsfhnBlvUlG0a1m3N4PnOdbzsnJel2uncganaf6CvpeZ1cr857mG+k8OhZFwno6KC-SZfiXS2Zc07hzVhrUW2tf76ygIbY2gDzalwdDA221AJ7s2LjgF2Ks5ix29r7Iuddk7B20iHNqn9I4-zPoTPB8dCFOxTqAgsnhuB1RlNnE+v8H4AMTpgq6SD77-2QE-VmAwk48zIXzZuYUPAYDWN-aKH4pQpTStEDKMh+7smSNsS2L0CQ4EqkyFafJThSwlA7DUDxYi6m1Mgvk0hew0MYBrLeUBSiuwVODfeesbbQJzm4iWfdogJQBmMQ2Ljgl2JPhcP+QSoQiUSmE5x2RXHjHThkIRCCoCU1OKceA8A2htCiTbIRIia68KISQ6STdKSOlxmEL8VifA2OVC04Ez1+q7AqKga6Jt1KmNYYTSx6ZmlajdB4hxl0ijhJSZEjxe81Do2YX4k+rQBg9xKE9WByTUnuJwZUQJiV4lbPdjs6IVR0kRULlkm+uT8mFOKW7OBJsKnXxyXkgpRTLn00rsI6uWSeZh2YYgbgPZj4lMLmUrJDR9ncPoW2TE8NvmnPga8hFBl4SN0RM3Op7IVHfkxJgdS2injwD0fGQx1V2QDPMQMYZCZrFjPAhMs6UzTkRPio80CXjFngvotQnxqzDkT02UEpJHKAnIpiXSOJvdEnbIlWk2FFQLDCrbAk0JUAk7YO1s8m57zckPORc8gA8nYeAzBpXau5g0LFyxpHBXqEAA):

where you can:

drag a point when mouse-down on point
insert a point with shift+click on a location in the chart
remove a point with alt+click on a point (on Mac this is option+click).

But when I add or remove a few points and update the data viewer, only the first three data points from the original spec remain visible.

**Comment by domoritz** [comment]
Even after you hit refresh? Do you have a screenshot of the final state where it's wrong? Can you compare it to the state of the view?

**Comment by mattijn** [comment]
<img width="1089" alt="bug_dataviewer" src="https://user-images.githubusercontent.com/5186265/46096058-74a94f00-c1be-11e8-9074-0e5fc3ae1262.png">

**Comment by domoritz** [comment]
Thank you for the bug report. We'll look into it or if you want to send a PR, we would love that as well.

**Comment by algomaster99** [comment]
@domoritz This is not an issue with my development setup.
![bug](https://user-images.githubusercontent.com/35191225/54121668-15b05d00-4421-11e9-8a07-cbe86ae2f2f5.gif)

**Comment by mattijn** [comment]
Now, it also works for me as expected in the https://vega.github.io/editor

**Comment by domoritz** [comment]
We're working on automatically updating the Dataviewer.

**Comment by algomaster99** [comment]
@domoritz Shall I try to do it?

**Comment by domoritz** [comment]
See https://github.com/vega/editor/issues/173
