### ISSUE TITLE
Support another spec format

### ISSUE THREAD

**Issue by evanliomain** [vega/editor#171]
The editor is a great tool as I have to design a new chart, or to enhanced a previous one. And thanks you a lot for that.

But, one big caveat, I have when I use it, is the supported format for the vega spec, the json format:
- can't write comment where I want (I know the `description` property)
- it fail every time I just want to add a new element in my spec because of a missing comma (comma that I add just after, but the time I write it, the visualisation go wrong.

It could be nice to support a nicer format that can be more _configuration_ or _code_ friendly.
I could suggest yaml or hjson, but it's not a close list.

[Here](https://nyurik.github.io/Vega-Sankey-Graph-for-Kibana/) an example of vega spec writed in hjson.

**Comment by domoritz** [comment]
Thank you for filing the issue. This is an often requested feature and we have discussed it many times. Until now, we decided that the disadvantages outweigh the potential benefits. See https://github.com/vega/vega/issues/1148 for example. 

I could be convinced to support comments but my main concern is supporting autocomplete. 

Also, check out bit.ly/js2json in the meantime. This shows you that I would like support for more than json as well.

**Comment by evanliomain** [comment]
Thank for the answer.
I understand it's not a quick feature, especially if you had to maintained more than 1 format in your doc.

**Comment by domoritz** [comment]
I don't think we will support this anytime soon so I'm closing this.

**Comment by alexeypetrushin** [comment]
You can have autocomplete if you provide TypeScript schema and enable TypeScript in the editor.
