### ISSUE TITLE
Multi-window support (feature request)

### ISSUE THREAD

**Issue by evanliomain** [vega/editor#172]
When developping with the editor, it happen to not have enought of space between the spec, the render and the data table.

Moreover, if you have a multiscreen configuration, it's nice to set a screen vertically to edit the code, and one screen horizontally to view the render.

But to work, the editor have to support multi-window rendering to place and resize them whenever we want.

So It could be nice to extract the peaces of the editor in a popup or in a new tabs, and still have instant refresh between the spec editor and the data view and table.

**Comment by domoritz** [comment]
That sounds like a nice feature. Thanks for suggesting it. I don't think we will get to it so of you want it, please send us a PR.

**Comment by domoritz** [comment]
I don't think this should be a priority for us until we have tests (https://github.com/vega/editor/issues/293).

**Comment by domoritz** [comment]
We have too many other more important feature to work on so I'll close this for now.
