### ISSUE TITLE
Use the data change API to update the data viewer

### ISSUE THREAD

**Issue by domoritz** [vega/editor#173]

**Comment by domoritz** [comment]
This feature is available in Vega: https://vega.github.io/vega/docs/api/view/#view_addDataListener

**Comment by domoritz** [comment]
@siddhant1 This would be a great issue for you to work on and familiarize yourself with the code. I assigned you.

**Comment by siddhant1** [comment]
Sure , I will send a pr and will ask you for assistance if I feel stuck anywhere !

**Comment by ganeshpatro321** [comment]
Are we talking about getting rid of the refresh button here in the data viewer? after any changes in the chart? @domoritz

**Comment by domoritz** [comment]
Yes.

**Comment by siddhant1** [comment]
@domoritz I have added event listeners and not when I am dispatching with the new Data using SET_VIEW , it is expecting type view , is there any method on view through which I can update the data of the view and set it as a new View? or is there any other approach?

**Comment by domoritz** [comment]
I don't get the question.
