### ISSUE TITLE
Wrong scaling on export from Editor

### ISSUE THREAD

**Issue by iliatimofeev** [vega/editor#175]
A bit unexpected differences between vega editor and export to png when range for y scale is used
![image](https://user-images.githubusercontent.com/11561581/47510011-e9d07880-d87f-11e8-8dac-42dc63d848fd.png)

[Vega editor](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KAHdGAExbYwAJgAMuxREgpG1fFr0GlkQujVrGM6loCsi62vR5MOANpKIUAhgqBl0VGQtSGlWACd4SMMQqDiAGyjPb1J4dFjYSWk5JJDIPFj0GVgAM25Y1C1-ZOCgpuDSgE9CSJxIKsZUvGRYhQDWyGQAD0JhnszWVF8AcgAJWthkQm5lIcWAXTAAQgBeMBlWVNSwADIrsDmFxYBZfuRYAH0u2LeAcXQL2T2hxOZwu11u9yWAEF4AlUkMvDwZIDjqdzulRiEAL4YsC7UbYiC7dxGBB-V4NUYtEphCJRCYjJodLpRVKOZC5BnJSCxbisGRqLRlVjIYptGSMBKC2LC0VGABeQ24UplOMgam4GEcWmAaq8PigMXiiSgfWQqQFPVWeQ2WyGkExsqg5Sc3RU6k0+NFVLF4VdkHanJKeE6ftZMnZw0d3N5-OVItV4slOCF8cZCp5caj6s1chwOsy+uivKNChNjDNFqgzzh70+Pz+qVk9qjzuort8OtgpjC6R6JjMeGbujxWK9Cd9US7CsDbWDzJ6YYjM6MPL5lZTUcTrqqf3WUfTSuT0tTXOz6C1ed13knxcl8jLFai0Nh8LwiObqtb7dE8gAzAA2ABGEdggJXFiSgdAJnJPxKVVUk4TpZcoGoWJ1EzVUzwvMAd1SPdVVqcsZEHHp2G4AgNWQ0oJQAawAYRjEiwDcVU3zwRDLTWG1tmGT04MZBC-QDKNUPQo8VUZLDcxw3cTxKQjkGIllkCqQcozYuEAAU7AcJxXHU5gOKrF5ayGet-jkfElCJEBrDhNt+VgCkQm9ElGGnHop0SVjDL9Z8zVfd8oxqOovEnKjFPgbg1FdVy2lgdpUDIvDtRxEpWEITJYrSrlYDKbgaOQAB1d1EG1SAKD+YULAdHL5NseBmADS9KtSaqcF0OgXFq1pcvywryta9qoAAYlEf8AA5tHYUQP16kpYEQdB5zAHUhr9Rr4kQsDep25I9ogPawJs6wMFiGinNglzx1pHozouqi5z9BKku4dJgp5epLwLG84klHquUi6Lst6yAMqy1L5qgelL0EpD716ctzSiK11k2Hi5vm-1yrhnphIfZGemrV4PjM34LMx0GvJxnIjOidzjURx8en8uFyjfJsAappaVrWqqNsYLbIi5sY8p5QqSo0MqWv5mrHXq9BGuDQbZY6rqRYE-rYoq1XRvGqaZspsY+guFW2r9MoKlgWxYkUwcDtAnEjuskBsSAAl)
More than, looks like `"width"` and `"height"` become `1` on export

**Comment by domoritz** [comment]
Hmm, I get this

<img width="995" alt="screen shot 2018-10-25 at 17 09 11" src="https://user-images.githubusercontent.com/589034/47510590-bc340100-d878-11e8-92ce-2aa3245712e2.png">

**Comment by iliatimofeev** [comment]
As you don't see this?
![image](https://user-images.githubusercontent.com/11561581/47520289-7a1ab780-d898-11e8-8f08-3a4fae3e6ca8.png)

**Comment by domoritz** [comment]
Got a link?

**Comment by iliatimofeev** [comment]
This from https://github.com/vega/vega-lite/issues/4229
[vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAuCW0BsCmkBcZiQGYHsB20AyrAF4roCMAHADRTRIAe0aUhcAtgK4JcDOYAEoBDBpAC+NcFADusACbQAFqwDMABnVSIkDsIBOAa1aR9SAMYttUJUlgBzJS3Qat0yOfxYHrTPuF49uQYkLaiegAOvpB85rYcwZAAbrD6CrB8EuKS7kh4nvKwgb7SOp68HHglEDVQfDj6zmAA2pAACkhpEbb+CJB0kADCDXDmwn0DAPIARgBWFiwAuta12LBICPImyEkb-aU1MACeEYl4OBxF45AHOauM1bVQwowZ0XCIiQCywvZ48Fx5EgwDgsGAAILyYQRaCiWD4CQrQ7eDZbdAeAD6wn2T3oJ0SDUKeGutyRHhwCAaj1WKM2Jj4nAx-jESJ00HxJgAjlwAh84bscU9IL97GZ7KJEgkAoLVsggng0SEPsgTOxYNwELAwAB6MCECz4LbiUkHSBHamHF5vdCYZXfX7-aCA4GgsAASTwSngsGmcARdyFtMVmI4MsO7NOJkJVz6t2kAcgUNhFuS4y4SEy6GaBwgoFxZQxofQbnzUHMWNYJfzMUZzOCqgAdNQKAAmAAsAHZVFRu22WwA2Vusw47PbojpdHok3EB2p56vlotgajDgvY4uruq1iWsNsNjsd6iH9QdgCsHf7qgAnCucyOkLs+uPOrBup1p09ZzV57iQ2oW5umLrmAVa-gy6pMjuxYNj2h4duoqj9m2FD9je6hUG2gGjk+UATq+U6xjOw4-kKi6sKe-aAeWwGgUK4EcJBYjQQebbdi2p5UP2VAUX2p4AXeOjYSYeFvr0NxEXeJGrGRlCaFRFYbgJW4QXWlYNqebbIf2J6IfBV5Xi26inlhD5jrhL6iR+tRfrmSl-oppZAeRgH0YxwTqDBqhwQhSEoWhGEmY+wkWQR4mfsRdkycutCRQpYDGXZrmqege4caop4nh2rFUOxnHcYFZntCF76EeFkmxUuqj8Y51HOYl25MWAjb6VlVAYW1V4nm2BmYXZQnPpOJVhdZEU1YW5GUbFwEJY5SVQWALYNpoBnoVQWWaBx2nVdW-XmYNYl3jZGAVawFByVNdWzQ1wQUA2nVthR7Edu1nYthQM07aZOFFftVk1EdUmHFFtHSXFFAUC511qRRGVUPpV4cRQyFtjlBXfSJoWHaNC7jZQMVjcB4OQyp82NuDGGnle2n9nx+ktpxaPBb9pUjeVY2Vdtv61ZQEP1STjWLReA79i2hkUGeVBGWejMDfhQ1Y2zONLhR8mE7zV388Ep5LS2Gii9QGVIzTMt7XLB0SbigMFkuZ0g0DYPq9Wc0Cw2mlrbrqjvRQV5tkhnNCrtP1m39EAAydDk48B7HEwxyUgfuCOe9QD1U+oNOqCbQeWSz-3Y1zuPRarrDR3zsfzbdl7tjlb3qK2V4XkjmcY-LFtPFbZYF1VRfoCXGtly7A4IZTV49uxNNXhnfVfUzwc56HeekQXKsXT3H1gVDPd3QZbVtkZ3vqA9ItrwH0+y9nw254r+c2+dBPF8fqzO1rDYtll4tVT7A6nt2k+OYHzfmzKpbcOIFu7xUmn3NyalfYH1YvBdQLYJ7LUvE3YqgDWbAPZqdfGkcJoxygdBZC3FuLUEMhTDS-tZSn1NufBWmClb-jAcvSBccPKbVrgZDSN5YKU1QczC+88r6L2VhA3B6BmFOw3vHFabV1pGU4hw3+n0gpn0xq3OcIDbZMNEevTWp0X6nnPIYjSR9EJHz4bPARYAw5YIjvnGi+C463Vfv2LiKMjLpWep1JRv5A7DEaLAMYc9rEL1BjbHB9jKyOPmotd654KCITWl2DSGlM7+NGCHEJQiwmMJXqA0uBCFrqXBqecG6hOE6V7sowq6TAmZJsQw8ROjF4OIKXHWJCTuKlNQnxVCI8OxpJGHU4JDTr6nVvmI-JLD5oeRgZpLymhEGuCpj4k+KioC1KCVY0Zwiol5IfocJ++j07ISNgZVQ144aUPvOsoYQytl0LbpoiJLTLqSL0Zvc8fYR6cRHoZTQLyqG3M2fU0J9sOZMOiS7QxFzUKDhPO9Z6adBkBIeeo78ICJGRPEVC+sL9iET37B2QlXkMqrKBTU+5oLsngvGXbNcbzdH92CItQe6V9KjxhhPFFGSRlgutnsu+PNcXFwbIOQc55uyS3pr7Xqf9qF3NRdS+hYy8ZgKJm0mJMFfZeXOVQcW3U3E8uGds-lHcIV5I1dMxqjZuqlM4q-A+acEEHmNWioBTzbHgPVY7JlhS9zOpccLUWtcLxuuVZ6xpy4JnYuXL6uiUjGzXg8S1FG7U4bhr5TSgVdjXmrxFS4V2WUnq1wSaG-SzSKXfRBVmlVuy1V5KqX69pL9tLspHlVLl5KbmUqVbWyNqqmrXIZfmzVNr1JeIQhoLiosJ4MynsCql-aNFeqxXmhaBydBHPEQ2LybVvYcXrpxPiw6oB+KXaa7N5q6VgKbQmj5YA9yuI7KLTs0q+wHivJmy9dacm5tBtNSthypG3U0HMuBiykHxqrSYGtP6B31sLvsoDW7E27s6t-VNO8OrfseSuqNXdkMFqajBbefZvYXM4ulOV1Tq0Xrwxi1dKGO6AeI3uM85SiEoXHqhXD6LbJeq0URsdwR2Pb00BclGXEkabrPQquDDHcz2VASxqJylmWioRmddi39EJUzOgMuTtyZjzEsIiSSymtCqZxep-1L807PQM-pbqrqjOFRMwsczltLMDG5nGgY27H2u3PBPN6VyNoIIGIHDzZmAY+esxugLUi9wXN1hRS8D0zwJMom576MWWBxeBr5uKKtbNxyfb7RBhi3qdMMRDXLJh8tebbsplcCWrM1gfY2Wu3YElJwBcSqLCqmuFYLm1pyNnOsaZSndfVKEzFcTTgeobxm5iedG+E4rasksPr3D2X2HFuIaAvNperkBotrdi2a1rgL7ZR1k1NuzrZp271Yt-emHEHsXdMywRTIQorjb86Vx75Wlr6sMtV97mkEIrfc5dgrxFlNd3azt6bJGEKdl4vBcGGhxaGfO8N+HzW5xI4Agl4yZXSbqQ5Z28er9uOw7y0TjbjCEtE0p41J9sCFkIKQeUnLBPVs-eJ9+UnW376o7s8+19SL2yv0Gw19EI3EdRWRxN71HPRNg9bEZPiUPd4Z0V1AZXFmorA78x1wLi1OJdnQi51+N4qYU8F3D4XLOmni8m4Fxsa1vZ11UH2HKrYkKM8a8z67ZvmPq6te8tHtqtMOvgrvLarqF2u8839zAkfPeJc17udSWluqiwogahJoelfh9N0vAXQOBeBb3AbEhOU7eGL7OX43lff20tkvSlHInRUvvQj5HsXCtrdsEoT4XmfWtyXJ5L0HKEi9j1L57Z3331sR7GzG9dMfm3zT3AOBGXFuIvpFg9cfRvIBNcz5o7fAGJf95m1XS8CMR7vWrl9yfGf+PHUE3fu7eCj+JGE8nYmgh470PsksVMmc1+M4Bwiw8YIA4gQAA)
You said that you cannot reproduce it. But I see non natural order of Y. If is so it could mean that Y vega differently interpret range of Y scale.
```javascript
 "scales": [ 
     {
      "name": "y",
       "range": [0, {"signal": "child_height"}],
      ....
      }
```

**Comment by domoritz** [comment]
Works fine for me.

<img width="1241" alt="Screen Shot 2019-03-16 at 10 52 14" src="https://user-images.githubusercontent.com/589034/54479409-97b1d480-47d9-11e9-8686-dad0ea546d63.png">
