### ISSUE TITLE
Editor does not set mode from URL

### ISSUE THREAD

**Issue by domoritz** [vega/editor#176]
See https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAuCW0BsCmkBcZiQGYHsB20AyrAF4roCMAHADRTRIAe0aUhcAtgK4JcDOYAEoBDBpAC+NcFADusACbQAFqwDMABnVSIkDsIBOAa1aR9SAMYttUJUlgBzJS3Qat0yOfxYHrTPuF49uQYkLaiegAOvpB85rYcwZAAbrD6CrB8EuKS7kh4nvKwgb7SOp68HHglEDVQfDj6zmAA2pAACkhpEbb+CJB0kADCDXDmwn0DAPIARgBWFiwAuta12LBICPImyEkb-aU1MACeEYl4OBxF45AHOauM1bVQwowZ0XCIiQCywvZ48Fx5EgwDgsGAAILyYQRaCiWD4CQrQ7eDZbdAeAD6wn2T3oJ0SDUKeGutyRHhwCAaj1WKM2Jj4nAx-jESJ00HxJgAjlwAh84bscU9IL97GZ7KJEgkAoLVsggng0SEPsgTOxYNwELAwAB6MCECz4LbiUkHSBHamHF5vdCYZXfX7-aCA4GgsAASTwSngsGmcARdyFtMVmI4MsO7NOJkJVz6t2kAcgUNhFuS4y4SEy6GaBwgoFxZQxofQbnzUHMWNYJfzMUZzOCqgAdNQKAAmAAsAHZVFRu22WwA2Vusw47PbojpdHok3EB2p56vlotgajDgvY4uruq1iWsNsNjsd6iH9QdgCsHf7qgAnCucyOkLs+uPOrBup1p09ZzV57iQ2oW5umLrmAVa-gy6pMjuxYNj2h4duoqj9m2FD9je6hUG2gGjk+UATq+U6xjOw4-kKi6sKe-aAeWwGgUK4EcJBYjQQebbdi2p5UP2VAUX2p4AXeOjYSYeFvr0NxEXeJGrGRlCaFRFYbgJW4QXWlYNqebbIf2J6IfBV5Xi26inlhD5jrhL6iR+tRfrmSl-oppZAeRgH0YxwTqDBqhwQhSEoWhGEmY+wkWQR4mfsRdkycutCRQpYDGXZrmqege4caop4nh2rFUOxnHcYFZntCF76EeFkmxUuqj8Y51HOYl25MWAjb6VlVAYW1V4nm2BmYXZQnPpOJVhdZEU1YW5GUbFwEJY5SVQWALYNpoBnoVQWWaBx2nVdW-XmYNYl3jZGAVawFByVNdWzQ1wQUA2nVthR7Edu1nYthQM07aZOFFftVk1EdUmHFFtHSXFFAUC511qRRGVUPpV4cRQyFtjlBXfSJoWHaNC7jZQMVjcB4OQyp82NuDGGnle2n9nx+ktpxaPBb9pUjeVY2Vdtv61ZQEP1STjWLReA79i2hkUGeVBGWejMDfhQ1Y2zONLhR8mE7zV388Ep5LS2Gii9QGVIzTMt7XLB0SbigMFkuZ0g0DYPq9Wc0Cw2mlrbrqjvRQV5tkhnNCrtP1m39EAAydDk48B7HEwxyUgfuCOe9QD1U+oNOqCbQeWSz-3Y1zuPRarrDR3zsfzbdl7tjlb3qK2V4XkjmcY-LFtPFbZYF1VRfoCXGtly7A4IZTV49uxNNXhnfVfUzwc56HeekQXKsXT3H1gVDPd3QZbVtkZ3vqA9ItrwH0+y9nw254r+c2+dBPF8fqzO1rDYtll4tVT7A6nt2k+OYHzfmzKpbcOIFu7xUmn3NyalfYH1YvBdQLYJ7LUvE3YqgDWbAPZqdfGkcJoxygdBZC3FuLUEMhTDS-tZSn1NufBWmClb-jAcvSBccPKbVrgZDSN5YKU1QczC+88r6L2VhA3B6BmFOw3vHFabV1pGU4hw3+n0gpn0xq3OcIDbZMNEevTWp0X6nnPIYjSR9EJHz4bPARYAw5YIjvnGi+C463Vfv2LiKMjLpWep1JRv5A7DEaLAMYc9rEL1BjbHB9jKyOPmotd654KCITWl2DSGlM7+NGCHEJQiwmMJXqA0uBCFrqXBqecG6hOE6V7sowq6TAmZJsQw8ROjF4OIKXHWJCTuKlNQnxVCI8OxpJGHU4JDTr6nVvmI-JLD5oeRgZpLymhEGuCpj4k+KioC1KCVY0Zwiol5IfocJ++j07ISNgZVQ144aUPvOsoYQytl0LbpoiJLTLqSL0Zvc8fYR6cRHoZTQLyqG3M2fU0J9sOZMOiS7QxFzUKDhPO9Z6adBkBIeeo78ICJGRPEVC+sL9iET37B2QlXkMqrKBTU+5oLsngvGXbNcbzdH92CItQe6V9KjxhhPFFGSRlgutnsu+PNcXFwbIOQc55uyS3pr7Xqf9qF3NRdS+hYy8ZgKJm0mJMFfZeXOVQcW3U3E8uGds-lHcIV5I1dMxqjZuqlM4q-A+acEEHmNWioBTzbHgPVY7JlhS9zOpccLUWtcLxuuVZ6xpy4JnYuXL6uiUjGzXg8S1FG7U4bhr5TSgVdjXmrxFS4V2WUnq1wSaG-SzSKXfRBVmlVuy1V5KqX69pL9tLspHlVLl5KbmUqVbWyNqqmrXIZfmzVNr1JeIQhoLiosJ4MynsCql-aNFeqxXmhaBydBHPEQ2LybVvYcXrpxPiw6oB+KXaa7N5q6VgKbQmj5YA9yuI7KLTs0q+wHivJmy9dacm5tBtNSthypG3U0HMuBiykHxqrSYGtP6B31sLvsoDW7E27s6t-VNO8OrfseSuqNXdkMFqajBbefZvYXM4ulOV1Tq0Xrwxi1dKGO6AeI3uM85SiEoXHqhXD6LbJeq0URsdwR2Pb00BclGXEkabrPQquDDHcz2VASxqJylmWioRmddi39EJUzOgMuTtyZjzEsIiSSymtCqZxep-1L807PQM-pbqrqjOFRMwsczltLMDG5nGgY27H2u3PBPN6VyNoIIGIHDzZmAY+esxugLUi9wXN1hRS8D0zwJMom576MWWBxeBr5uKKtbNxyfb7RBhi3qdMMRDXLJh8tebbsplcCWrM1gfY2Wu3YElJwBcSqLCqmuFYLm1pyNnOsaZSndfVKEzFcTTgeobxm5iedG+E4rasksPr3D2X2HFuIaAvNperkBotrdi2a1rgL7ZR1k1NuzrZp271Yt-emHEHsXdMywRTIQorjb86Vx75Wlr6sMtV97mkEIrfc5dgrxFlNd3azt6bJGEKdl4vBcGGhxaGfO8N+HzW5xI4Agl4yZXSbqQ5Z28er9uOw7y0TjbjCEtE0p41J9sCFkIKQeUnLBPVs-eJ9+UnW376o7s8+19SL2yv0Gw19EI3EdRWRxN71HPRNg9bEZPiUPd4Z0V1AZXFmorA78x1wLi1OJdnQi51+N4qYU8F3D4XLOmni8m4Fxsa1vZ11UH2HKrYkKM8a8z67ZvmPq6te8tHtqtMOvgrvLarqF2u8839zAkfPeJc17udSWluqiwogahJoelfh9N0vAXQOBeBb3AbEhOU7eGL7OX43lff20tkvSlHInRUvvQj5HsXCtrdsEoT4XmfWtyXJ5L0HKEi9j1L57Z3331sR7GzG9dMfm3zT3AOBGXFuIvpFg9cfRvIBNcz5o7fAGJf95m1XS8CMR7vWrl9yfGf+PHUE3fu7eCj+JGE8nYmgh470PsksVMmc1+M4Bwiw8YIA4gQAA

It should be vega-lite but it is vega if that was set before.

**Comment by ganeshpatro321** [comment]
This seems to be happening in this particular URL,
When I am creating share URLs of examples in my local machine, then it's updating the mode correctly.
@domoritz

**Comment by domoritz** [comment]
It does not work for me. Can you give steps to reproduce?

**Comment by ganeshpatro321** [comment]
What was happening is, when you select the above URL the mode was not set to vega-lite, it was dependent on the mode of the previous spec.
But, what happens now is, when you click a URL, it will read the mode, and update the redux state.

You can run the above URL locally, and it will update the mode correctly.
@domoritz

**Comment by domoritz** [comment]
I see. #243 fixes this issue then, right?

**Comment by ganeshpatro321** [comment]
Yes, it does! @domoritz

**Comment by domoritz** [comment]
Merged.
