### ISSUE TITLE
Don't show shortened link

### ISSUE THREAD

**Issue by kanitw** [vega/editor#179]
https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkD...1iQM4AAM9ogcaq8cNSrAVQAuiAFUA

This one opens fine in Chrome but not in Safari.

**Comment by kanitw** [comment]
(In Safari, the spec isn't loaded.)

**Comment by domoritz** [comment]
The link does not work since it uses ...
Can you paste a working link?

**Comment by kanitw** [comment]
Oh, then we have UX problem, not a Safari problem.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/111269/48515208-032c6b00-e815-11e8-8457-d495e5b0cb67.png">


If we don't expect users to copy the text, don't show the text.  Just show the copy button.  
What I did is I naturally drag to select the text and then do cmd+C, so I get the url with ...  ><"

**Comment by domoritz** [comment]
No, you have to click the copy button or click the link. the link can be long.

**Comment by domoritz** [comment]
Fair, let's hide it!
