### ISSUE TITLE
Clear button doesn't preserve the undo history

### ISSUE THREAD

**Issue by kanitw** [vega/editor#182]
When I click clear by mistake, there is no way to bring my code back.

**Comment by domoritz** [comment]
Yeah, undo is not supported well in general because of https://github.com/vega/editor/issues/12. I'm not sure how this interacts with clearing, though.

**Comment by ayushnawal** [comment]
@domoritz if you don't mind , can i give it a try to fix the problem of user clicking clear button "by mistake".

**Comment by domoritz** [comment]
Go ahead. Make sure to read #12!

**Comment by ayushnawal** [comment]
@domoritz i think we can tackle this issue of clicking clear by mistake in fol;lowing 2 ways : 

1) By generating a warning for user like " Are you sure you want to clear ?" and let user handle this query maunually.

2) We can clear the code , user edited but if we find a solution for preserving the history of edits by the user , we can add functionality to clear button like chrome does with the back button , on holding the clear button you can view last 5-6 history states . We can aware user about it by showing a small text message like "Click to Clear , Hold to see history "

Your Opinion

**Comment by domoritz** [comment]
First, let's tackle #12, which will resolve the biggest problem here. Then we can think about more support for history.

**Comment by domoritz** [comment]
Fixed now.
