### ISSUE TITLE
Why is this broken?

### ISSUE THREAD

**Issue by domoritz** [vega/editor#183]
Reported by @kanitw 

Why is this example just `{}`?

https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSlWStITHcAnqmRK8I9PCPdYsEYyWarLB4RozIsPKKKgC+6hCQIehKsABm3EaoZgDaBimMYnjIRmaQ2nisqHSwRWGwALwNAOQAkkppGTo8So2Q0QC6cVAu8Nya-tRmoBDxAB6TkHnIYpolZchqUHgOhOs4Cbbp6KaxGvEO84vLJSPWeBsJ27tQAI6sSXjMnVS9GifxYugHEVsqcwFNpvEMEYANbzLY7EoSGz3eDGRTFPaEbj+QrFVRQPJiMTIFY4FJHap-CFDJQjMZKCb6UEQyDBLzQ5AAeUIHmY5yZ1OpkBGAWYXUmzMFm3CdwFUsFkCSpLAWUl8v+LmoLAAFGV0NqADqspbIeCFtopTQAfWC6WQRoAlHa1Gr1QYlNxZWDjcSzeK9tVvebetFnYK+iHplT1VAKEdWE8AAx0ADM4eD8rT1IzEEjYMlkABQIxKud4PlkChsLlUYeCMx2NcTqj8VRRnRJSxOOBg2r3B58D5ZgAjN31ayQtwOSV2AD4LCR2XCaY9gBiAAs8AA7AAOdBbyCp+dC-2mj7KCVNqDHs0kuGPEqoVgFRi9Q8KxCMaiICSfwNVps1p5WXGYlGwvIZUEILYSjdZFXylSAzz2VBuCCZBuCoPFwxZGx0CMGUzBCOMsLALMpRzBVhlGcZz3-XteSgv9qxFMZTxURj-0KYIaLA6YEKLVUeMFAwr1Ykp30-b98BvcjBNLQSWSVEF5LLYkGR1PVDS9E8SStPAbXtR04Pk4STR9RDL1MwNSOUsAwxs7NiNDRyIyM+CYzEOMh2cmSy3czycHjYifKPccOQAdUYTQWG4-9mLFcy5IvfYuPYpLFJwAT7PzTV1IsTSRJ0608IM0CbJMgNfQsgNpOciE7ME4LfNjJ5pG81yWT8p5ByC1NnWs2zQQzAYNGFZQ8kZXMWQ7Bt9CAgAvJ4ADZVwzYNoiAA

<img width="1223" alt="screen shot 2018-11-28 at 17 08 43" src="https://user-images.githubusercontent.com/589034/49192577-6eeff700-f330-11e8-8bf3-d8cc50f6972d.png">

**Comment by domoritz** [comment]
There is no error.

**Comment by siddhant1** [comment]
Is this still causing an error , I can work on it now

**Comment by domoritz** [comment]
It looks like it is still an error. Thank you!

**Comment by algomaster99** [comment]
@domoritz When I click the link, it's working as expected.
![Screenshot from 2019-03-10 13-07-59](https://user-images.githubusercontent.com/35191225/54071855-7c563f00-4298-11e9-8d72-1761c2207b1e.png)
I maybe misunderstanding the bug because I can't seem to understand the issue as of now. Please help me with this.

**Comment by siddhant1** [comment]
For me  , it is still giving an error , I will look into this today , thanks for reporting :)

**Comment by siddhant1** [comment]
@domoritz Can you look into this , sometimes it gives an error and sometimes it loads perfectly

**Comment by domoritz** [comment]
Right now, this does not seem to load anything. I'm not sure whether or why there is a problem.

**Comment by ganeshpatro321** [comment]
@domoritz @siddhant1 
I think I have figured out what's happening,
Whats happening now is, it not rendering the data of the present URL, rather it is rendering the data stored by the browser state previously.

I think the it is not getting the data from this particular URL.

We have also come across another major Bug.

**Comment by domoritz** [comment]
Thanks for debugging. It would be great to figure out what's going wrong and fix it.

**Comment by siddhant1** [comment]
I will have a look at this one today

**Comment by bryik** [comment]
@domoritz do you expect that URL to work? 

The encoded portion of it does [not decompress properly](https://repl.it/@bryik/Vega-viewer-URL-bug-issue-183).

```js
let brokenData = 'N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSlWStITHcAnqmRK8I9PCPdYsEYyWarLB4RozIsPKKKgC+6hCQIehKsABm3EaoZgDaBimMYnjIRmaQ2nisqHSwRWGwALwNAOQAkkppGTo8So2Q0QC6cVAu8Nya-tRmoBDxAB6TkHnIYpolZchqUHgOhOs4Cbbp6KaxGvEO84vLJSPWeBsJ27tQAI6sSXjMnVS9GifxYugHEVsqcwFNpvEMEYANbzLY7EoSGz3eDGRTFPaEbj+QrFVRQPJiMTIFY4FJHap-CFDJQjMZKCb6UEQyDBLzQ5AAeUIHmY5yZ1OpkBGAWYXUmzMFm3CdwFUsFkCSpLAWUl8v+LmoLAAFGV0NqADqspbIeCFtopTQAfWC6WQRoAlHa1Gr1QYlNxZWDjcSzeK9tVvebetFnYK+iHplT1VAKEdWE8AAx0ADM4eD8rT1IzEEjYMlkABQIxKud4PlkChsLlUYeCMx2NcTqj8VRRnRJSxOOBg2r3B58D5ZgAjN31ayQtwOSV2AD4LCR2XCaY9gBiAAs8AA7AAOdBbyCp+dC-2mj7KCVNqDHs0kuGPEqoVgFRi9Q8KxCMaiICSfwNVps1p5WXGYlGwvIZUEILYSjdZFXylSAzz2VBuCCZBuCoPFwxZGx0CMGUzBCOMsLALMpRzBVhlGcZz3-XteSgv9qxFMZTxURj-0KYIaLA6YEKLVUeMFAwr1Ykp30-b98BvcjBNLQSWSVEF5LLYkGR1PVDS9E8SStPAbXtR04Pk4STR9RDL1MwNSOUsAwxs7NiNDRyIyM+CYzEOMh2cmSy3czycHjYifKPccOQAdUYTQWG4-9mLFcy5IvfYuPYpLFJwAT7PzTV1IsTSRJ0608IM0CbJMgNfQsgNpOciE7ME4LfNjJ5pG81yWT8p5ByC1NnWs2zQQzAYNGFZQ8kZXMWQ7Bt9CAgAvJ4ADZVwzYNoiAA';

let brokenDataDecoded = LZString.decompressFromEncodedURIComponent(brokenData);
console.log(brokenDataDecoded);
// >>> null
```

**Comment by domoritz** [comment]
I guess that's a problem. @kanitw what was the URL for? Are you sure you copied the whole URL?

**Comment by domoritz** [comment]
@bryik We should throw an error when we can't decode the data. Can you send a PR?

**Comment by bryik** [comment]
> Can you send a PR?

I can try :-)

Do you just want the error logged to the console? Or an alert? 

I'm not super familiar with the codebase, but I'm guessing the code to change would be here:

https://github.com/vega/editor/blob/e511878ecda9df4edf8b54b28683482dab9f707a/src/components/input-panel/spec-editor/renderer.tsx#L108-L111

**Comment by domoritz** [comment]
`throw new Error('text')`
