### ISSUE TITLE
Can't load editor after deadlock in vega

### ISSUE THREAD

**Issue by iliatimofeev** [vega/editor#184]
I’ve got a suggestion to the vega editor:
I bumped into vega deadlock bug https://github.com/vega/vega/issues/1464 while the editor was on auto render mode. As result, I couldn’t load vega editor anymore. Magick links with empty document didn’t help.

I have worked it by cleaning local storage of paused the site.

So I suggest to somehow check on editor load that the last render of stored data was successful and if not switch to manual rendering.

**Comment by ganeshpatro321** [comment]
Hey @domoritz , can you explain how to reproduce this, so that i can get an insight of what is happening. I can work in it.
Thank You.

**Comment by domoritz** [comment]
Just put in an invalid spec and see how the editor renders it again when you load the page again.

**Comment by ganeshpatro321** [comment]
@domoritz Ya, its clearing the editor, shouldn't that be the case? Because there is not input?

**Comment by domoritz** [comment]
What if the spec is valid but too large. We could have a timeout, or a separate url that clears the state before opening the editor. Do you want to add the latter?

**Comment by ganeshpatro321** [comment]
@domoritz 

I was looking into this, and I don't think anything can be done here. 
This is going into deadlock due to vega package.

Please correct me if I am misleading.

**Comment by domoritz** [comment]
We'll, what we can do is have a URL to reset the state before loading the editor. That at least would allow a user to use the editor again.

**Comment by iliatimofeev** [comment]
I expected that if I reload editor with broken spec it will switch to
manual rendering.
 I

вт, 19 мар. 2019 г. в 16:04, Dominik Moritz <notifications@github.com>:

**Comment by domoritz** [comment]
Even then the initial rendering will lock the editor.

**Comment by ganeshpatro321** [comment]
Exactly @domoritz @iliatimofeev

**Comment by domoritz** [comment]
So, the fix is to have a URL to clear or reset the editor state completely before loading anything. Can you add that?

**Comment by ganeshpatro321** [comment]
Do we want to reset the state after certain time of loading? @domoritz

**Comment by domoritz** [comment]
no

Just make `https://vega.github.io/editor/#/reset` work.

**Comment by ganeshpatro321** [comment]
I have made a route which clears the localStorage, but still not able to access the route when the editor goes into deadlock

I also tried avoiding the App component and created  a new component, that too didnt work.

Do you have any idea from where can I access things if the editor goes into deadlock. @domoritz
