### ISSUE TITLE
Add a link to directly create an issue with the editor URL

### ISSUE THREAD

**Issue by domoritz** [vega/editor#190]

**Comment by ganeshpatro321** [comment]
This is solved in #229 right?  @domoritz

**Comment by domoritz** [comment]
The UX is not quite right yet but the pr is trying to address this issue, yes.

**Comment by algomaster99** [comment]
@domoritz #260 solves this

**Comment by domoritz** [comment]
Not really. This is to create Vega and Vega-Lite issues.

**Comment by domoritz** [comment]
I think it's easy enough now that we have the copy markdown link button.
