### ISSUE TITLE
Connect the link generator (for sharing) to a URL shortening service

### ISSUE THREAD

**Issue by kanitw** [vega/editor#193]
The URL that we generate are super long.  Having a shortened URL can improve UX when users paste them on Github issue / stackoverflow.

**Comment by domoritz** [comment]
Yep. We just need to make sure that we use a service that supports long URLs. Also, at this point we might better support storing in gists.

**Comment by RandomFractals** [comment]
I think doing both could be prudent. Not every dev is going to post a gist.

**Comment by RandomFractals** [comment]
why not use tinyurl? It is free and been around for some time. I've seen some vega devs using it on this slack already. Should be easy to add to Vega Editor for sharing in slack and on stackoverflow.

bit.ly is another good option. quick comparison of both: https://www.slant.co/versus/2591/22693/~bitly_vs_tinyurl

**Comment by RandomFractals** [comment]
better yet, I would suggest vega rolls out a site with posted examples preview just like blocks and other online dataViz sites do. That would eliminate all breaking points and provide a better way to share vega examples for learning and troubleshooting.

**Comment by domoritz** [comment]
> better yet, I would suggest vega rolls out a site with posted examples preview just like blocks and other online dataViz sites do. That would eliminate all breaking points and provide a better way to share vega examples for learning and troubleshooting.

That's the goal but it's a bit of work. See https://github.com/vega/editor/issues/49

**Comment by domoritz** [comment]
We could use the tinyURL API: `https://tinyurl.com/api-create.php?url=https://vega.github.io/`

**Comment by RandomFractals** [comment]
true, launching a full-on examples and experiments site is not a simple chore.

I do like tinyurl a lot b/c they let you dish custom urls beyond just shortening.

why don't we just go with that for now, and gists!

I can plug that in VV next week and hopefully VE can keep up and help us connect those dots too

**Comment by domoritz** [comment]
I'm okay with using tinyURL as an option but I am concerned that if we automatically share the spec with tinyURL, we are exposing user data. It should be an option in the sharing dialog.

**Comment by RandomFractals** [comment]
I don't think public examples sharing can solve private data exposure.

For those gists could probably work best.

I'm just trying to find a better solution for the 80% sharing base64 vega links :)

**Comment by algomaster99** [comment]
@domoritz Can you please elaborate your concern? I am misunderstanding something here probably. I can work on this issue if you give a thumbs up.

**Comment by domoritz** [comment]
Let's defer this for a bit. This needs some thought before we can go ahead.

**Comment by domoritz** [comment]
I'm concerned about leaking information to an external service. Instead, I prefer saving to Gists. Let's focus on that for now.

**Comment by RandomFractals** [comment]
that's fine. Quick note on this: Vega Viewer has added support for vega gists since Dec 2019 via gistPad: https://github.com/RandomFractals/vscode-vega-viewer/issues/59

You guys should try it! :)

**Comment by domoritz** [comment]
Nice. Can I save to gist as well? The editor supports loading from gist already.

**Comment by RandomFractals** [comment]
yeah, gistPad provides save/create gist feature. I just enabled loading vega previews via custom gistfs gistpad uses. So, if you have both installed you should be able to easily create/star, update and preview vega and vega-lite gists :)

**Comment by RandomFractals** [comment]
in fact, I am going to make it easier for devs to use gists with Vega Viewer.

will push this update in the next release to automatically install gistPad with it:

https://github.com/RandomFractals/vscode-vega-viewer/issues/89

GistPad has nice data viz playgrounds and I think most devs using Vega should check it out too.
