### ISSUE TITLE
Show /examples popup when no example link provided

### ISSUE THREAD

**Issue by RandomFractals** [vega/editor#197]
Instead of displaying a blank page for the following links:

https://vega.github.io/editor/#/examples

https://vega.github.io/editor/#/examples/vega

https://vega.github.io/editor/#/examples/vega-lite

Display the Vega Examples gallery popup you get when clicking on Examples

**Comment by domoritz** [comment]
Sound like a great idea.

**Comment by ganeshpatro321** [comment]
Hello @domoritz , Can I take up this issue, please assign me this if this issue is not been worked on. Thanks.

**Comment by domoritz** [comment]
That would be great! Thanks.

**Comment by domoritz** [comment]
I can't assign it to you since you're not part of the project yet but I can add you after your first pr.

**Comment by RandomFractals** [comment]
@ganeshpatro321 thx for volunteering your time cycles looking into this.

I think it will be very cool if we can link direct to vega and lite examples in editor with that fix.

**Comment by ganeshpatro321** [comment]
Okay @RandomFractals  I will look into it

**Comment by ganeshpatro321** [comment]
Hwy @RandomFractals can you help me out with, where are the routings done in the app

**Comment by domoritz** [comment]
https://github.com/vega/editor/blob/master/src/components/app-shell.tsx

**Comment by ganeshpatro321** [comment]
Yeah, I found it , I was thinking of creating these routes for the above routes and calling app component by sending a optional props which will open the portal.
Will it be good?

**Comment by RandomFractals** [comment]
that could work. give it a go!

**Comment by ayushnawal** [comment]
I think i can resolve this issue by updating routes .
@domoritz @RandomFractals if you don't mind sir , can i give it a try ?
Thanks !

**Comment by domoritz** [comment]
Sure, if @ganeshpatro321 hasn't started on it yet.

**Comment by ganeshpatro321** [comment]
@domoritz Sorry for being late, I will submit a PR today. I had problems with my laptop.
