### ISSUE TITLE
new Vega-Lite Invaild spec

### ISSUE THREAD

**Issue by RandomFractals** [vega/editor#198]
When selecting Vega-Lite in editor to create new vega-lite spec I get:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json"
}
```
in the code panel, and 'Invalid Spec' error display in the Vega chart preview panel

Expected:

- latest v3.json vega-lite scheme reference in json
- and blank vega-lite chart preview display without errors.

**Comment by domoritz** [comment]
Can you send a PR to fix 1 here and create an issue in Vega-Lite for 2?
