### ISSUE TITLE
Update webpack and react router

### ISSUE THREAD

**Issue by domoritz** [vega/editor#2]
Using https://github.com/facebookincubator/create-react-app

**Comment by codeShaurya** [comment]
Hello @domoritz, I am a GSoC aspirant and I would like to help.

**Comment by domoritz** [comment]
@codeShaurya Fantastic. You can join our slack community at https://communityinviter.com/apps/vega-js/join. 

If you are already familiar with webpack and react, feel free to just send a PR for this issue. However, I can imagine that it's not straightforward and I don't want you to get frustrated with your first contribution. I'm happy to talk more if you have questions/ comments.

**Comment by zhirzh** [comment]
Is there an existing plan on how to update the project?

**Comment by domoritz** [comment]
No. But there are tons of tutorials online in how to update react apps that were created with react router. It may be an option to just start a new app and copy things from the existing editor piece by piece. 

Any help on this would be greatly appreciated!

**Comment by domoritz** [comment]
Done
