### ISSUE TITLE
SVG export is hard to download. Switch to "Download SVG"?

### ISSUE THREAD

**Issue by jheer** [vega/editor#201]
The export option for SVG does not provide usable download support. Instead it says "Open SVG" and opens the exported SVG in a browser tab. However, this tab has "about:blank" as the URL, which does not allow "Save Page" to work in either Chrome or Safari.

I think a better export functionality is to support "Download SVG" just like we support "Download PNG". I believe this is both more useful and more consistent.

**Comment by domoritz** [comment]
I agree that we should allow SVG downloads. However, I often view the SVG to print it as PDF (e.g. https://vega.github.io/vega-lite/tutorials/figures.html). Ideally, we would support both.

**Comment by jheer** [comment]
That works for me! I just think the Download is more important. The issue came about because I watched a user try to export an SVG for local modification in Illustrator and get frustrated with our tool.

**Comment by domoritz** [comment]
Fixed. I also added experimental PDF support.
