### ISSUE TITLE
Switch from CSS to SCSS

### ISSUE THREAD

**Issue by domoritz** [vega/editor#204]
SCSS supports nested CSS, which is incredibly useful.

**Comment by jshreyans551** [comment]
Hi @domoritz! Can I work on this issue?

**Comment by domoritz** [comment]
You're very welcome to do that. However, we have https://github.com/vega/editor/pull/169 open right now so to avoid conflicts, we should try to merge that first. @ydlamba what's the status of the PR?

**Comment by siddhant1** [comment]
@domoritz is this already being worked on?

**Comment by domoritz** [comment]
Let me try to get https://github.com/vega/editor/pull/169 in first. I'll ping you.

**Comment by siddhant1** [comment]
sure

**Comment by domoritz** [comment]
I think we should first refactor the css significantly. I started using css variables but we should cleanly convert the styles to use spacing units and color variables.

**Comment by domoritz** [comment]
Feel free to send PRs towards that goal.

**Comment by algomaster99** [comment]
@domoritz I am interested in working towards this issue. Shall I first in change it for one component then put a work-in-progress PR?

**Comment by domoritz** [comment]
Just send small PRs to refactor the CSS one by one. Let's wait with the conversation until the CSS is cleaner.

**Comment by ganeshpatro321** [comment]
Hey @domoritz I looked into CSS files of two components and checked for vulnerabilities, I dint find anything which is to be changed, can you tell exactly what kind of changing/refactoring are we talking about?

**Comment by domoritz** [comment]
We should use CSS variables for the spacing and make buttons consistent for example. There is a lot to do to make the CSS cleaner.

**Comment by domoritz** [comment]
I'll close this for now as we have more important refactoring to do.
