### ISSUE TITLE
export of png file saves not the same as shown in preview

### ISSUE THREAD

**Issue by iliatimofeev** [vega/editor#206]
Export of png file saves not the same as shown in the preview. 

When I open downloaded png it contains an image with the previous version of a specification.

**Comment by domoritz** [comment]
Hmm, I haven't had any issues and can't reproduce this problem.

**Comment by iliatimofeev** [comment]
It's stable on my configuration. 
Can I provide some extra information?

OS Type | Mac OSX 10 (Unknown
-- | --
OS Version | Version)
Browser Type | Chrome 72.0.3626.121
IP Address | 178.70.55.94
Javascript Enabled | Yes
Cookies Enabled | Yes
Color Depth | 24
Screen Resolution | 1280 x 800
Browser Window Size | 1280 x 649
Flash Version | Not Installed
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36   (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by domoritz** [comment]
Can you give me the exact steps to reproduce it?
