### ISSUE TITLE
Add CONTRIBUTING.md file.

### ISSUE THREAD

**Issue by ganeshpatro321** [vega/editor#207]
Proper documentation of how to make a development setup and start contributing would be very good for newcomers to this project.

**Comment by domoritz** [comment]
Good idea. Can you make a list of things you want included? The readme has a few small details already.

**Comment by ganeshpatro321** [comment]
Yes, the contributing.md file can contain information about:
- How to setup a proper environment.
- Details about version restrictions of different packages and stuffs.
- Proper way to create a PR or contribute to the project

**Comment by domoritz** [comment]
> * How to setup a proper environment.

See readme. 

> * Details about version restrictions of different packages and stuffs.

This is already in the yarn.lock file

> * Proper way to create a PR or contribute to the project

I'll link to https://github.com/vega/vega-lite/blob/master/CONTRIBUTING.md

**Comment by ganeshpatro321** [comment]
Ok cool.

**Comment by domoritz** [comment]
Thanks for helping me clarify!
