### ISSUE TITLE
Issue while setting up the codebase for development in a linux platform

### ISSUE THREAD

**Issue by ganeshpatro321** [vega/editor#208]
![screenshot from 2019-02-21 13-13-58](https://user-images.githubusercontent.com/30416891/53163987-4ad14880-35f5-11e9-9cc6-107682e17d30.png)

**Comment by ganeshpatro321** [comment]
This issue is getting solved after running the following command:

sed -i -e 's/\r$//' vendor.sh

in the appropriate directory.

**Comment by domoritz** [comment]
Can you send a PR? We're actually using Travis, which is Linux to run our tests.

**Comment by ganeshpatro321** [comment]
Hey @domoritz , we need to find a way where during installation, it should go into the scripts directory and run the above command.

**Comment by domoritz** [comment]
What does it do? Why do things work on travis>

**Comment by ganeshpatro321** [comment]
My system configurations are satisfying the requirements and constraints as required by the project. I am not able to figure out why this problem is occuring.

**Comment by domoritz** [comment]
Can you use docker?

**Comment by ganeshpatro321** [comment]
@domoritz , yes I can use docker but we need to solve this issue and find the reason for better accessibility of the project

**Comment by domoritz** [comment]
It works for me locally and on travis so I'm not sure what the issue is. What does `sed -i -e 's/\r$//' vendor.sh` do?

**Comment by ganeshpatro321** [comment]
The problem is with dos line ending for different OS
I have used the Sed command to search and replace the dos line ending characters to UNIX format for that file.

**Comment by domoritz** [comment]
How do line endings cause the error you posted? The file is still in the same place so why can it not be found?

**Comment by ganeshpatro321** [comment]
@domoritz 
I searched throughout google and found this. Please refer to this link: https://stackoverflow.com/questions/14219092/bash-my-script-bin-bashm-bad-interpreter-no-such-file-or-directory

**Comment by domoritz** [comment]
When I run `dos2unix` I have no changes in git. Can you send a PR with the fixed file?

**Comment by ganeshpatro321** [comment]
@domoritz I am also not finding any change in the file, though git is saying there are modified files.

**Comment by domoritz** [comment]
Does it work, though? Can you still send a PR?

**Comment by ganeshpatro321** [comment]
This issue is no longer relevant, couldn't find the appropriate reason, but the problem no longer arises after re-installing Ubuntu.
I am closing this issue.
Sorry for the trouble. @domoritz

**Comment by domoritz** [comment]
I'm sorry for your trouble.
