### ISSUE TITLE
Install script fails in windows

### ISSUE THREAD

**Issue by siddhant1** [vega/editor#213]
![image](https://user-images.githubusercontent.com/30566406/53660227-5e2e8480-3c83-11e9-8cd2-4de3da57eb60.png)

Fixing and sending a Pull Request

**Comment by siddhant1** [comment]
also generate-example-images fails in windows.
These scripts are os specific and should be changed

@domoritz

**Comment by domoritz** [comment]
I don't have the resources to support windows as well and suggest that you use the Linux subsystem or docker. However, I'm happy to review pull requests that help with Windows support.

**Comment by siddhant1** [comment]
Oh ! No Problem
