### ISSUE TITLE
Bug : Open Svg does not work (in export section)

### ISSUE THREAD

**Issue by siddhant1** [vega/editor#216]
Open SVG button does now work.
It opens a new tab and immediately closes it.
The expected behavious is to open a new tag showing generated svg.

I can investigate and send a Pull Request

**Comment by domoritz** [comment]
Is that in all browsers? Definitely something to look into and fix!

**Comment by siddhant1** [comment]
Checked in chrome , I will check in other browsers too , I can also send in a fix after investigating

**Comment by domoritz** [comment]
Thank you!

**Comment by siddhant1** [comment]
Fixed ! Closing

**Comment by domoritz** [comment]
🎉🎉🎉
