### ISSUE TITLE
Enhancement : Add contributing guidelines

### ISSUE THREAD

**Issue by siddhant1** [vega/editor#217]
Since this project is coming is gsoc-2019, I think we should add contributing and raising issues guidelines.

**Comment by domoritz** [comment]
Yeah, probably mostly linking to the Vega-Lite guidelines.

**Comment by siddhant1** [comment]
I was thinking of adding pull request templates alongside too.
Like



#### Nature of issue?



- Found a bug
- Existing feature enhancement
- New feature request


#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:




#### Feature enhancement details:



#### New feature details:


and pr templates


I have verified that this pull request:

* [ ] has no linting errors (`npm run lint`)
* [ ] is from a uniquely-named feature branch and has been rebased on top of the latest master. (If I was asked to make more changes, I have made sure to rebase onto master then too)
* [ ] is descriptively named and links to an issue number, i.e. `Fixes #123`

**Comment by domoritz** [comment]
Thanks for pushing forward. I think a contributing guide is great! I don't think we need PR templates but issue templates would be great. I would also love to have a link in the editor to directly report a bug similar to what https://prettier.io/playground/ has in the bottom right. 

<img width="370" alt="screen shot 2019-03-02 at 10 11 38" src="https://user-images.githubusercontent.com/589034/53685742-9d84c180-3cd3-11e9-99e9-42aebc2e74ec.png">

**Comment by siddhant1** [comment]
Yes , I think this is a great improvement I will surely work on this later today
