### ISSUE TITLE
Enhancement : Implement Route based code splitting

### ISSUE THREAD

**Issue by siddhant1** [vega/editor#218]
I think we should implement route based code splitting ,this will be easy to implement but will serve great improvements for the performance of the app.

Links :- https://medium.com/@addyosmani/the-cost-of-javascript-in-2018-7d8950fbb5d4
https://reactjs.org/docs/code-splitting.html
https://github.com/jamiebuilds/react-loadable
https://medium.com/airbnb-engineering/server-rendering-code-splitting-and-lazy-loading-with-react-router-v4-bfe596a6af70

@domoritz 
I can work on it and send a pr if approved

**Comment by domoritz** [comment]
I don't think it's really necessary for us since we essentially have a single page app. I think there are more important issues like having a single editor instance.

**Comment by domoritz** [comment]
I'd be glad to make this change if you can show significant benefit.

**Comment by siddhant1** [comment]
Looks like you are right , we definitly not need this one since we are running an SPA, 
also can you tell me about the single editor instance ? I would love to work on it

**Comment by domoritz** [comment]
https://github.com/vega/editor/issues/12

**Comment by siddhant1** [comment]
Should I close this one?

**Comment by domoritz** [comment]
It might help but so far bundle size has not been an issue our users raised.
