### ISSUE TITLE
Enhancement : Add a keyboard shortcut (cntrl/cmd+enter) to run in manual mode

### ISSUE THREAD

**Issue by siddhant1** [vega/editor#219]
Most of the editors have this feature that by pressing cntrl/cmd + enter the editor executes the latest saved code.
We should also add a keyboard shortcut in this editor.

**Comment by domoritz** [comment]
We already have cmd+b, I think. It would be great to make it more discoverable, though.

**Comment by siddhant1** [comment]
We can add a tab that opens a modal to show all the keyboard shortcuts.

**Comment by domoritz** [comment]
We should at the very least have a modal that shows up on cmd+?. A general help modal would be great.

**Comment by siddhant1** [comment]
I think we should add a link along with export that will open the modal and show all the keyboard shortcuts available

**Comment by domoritz** [comment]
That sounds good. One issue is that the top bar should also work when you resize the window. Make sure that is still true. Maybe all we need is a small `(?)` icon button.

**Comment by siddhant1** [comment]
Sounds good

**Comment by siddhant1** [comment]
![image](https://user-images.githubusercontent.com/30566406/53694056-25032b00-3dcf-11e9-9d2c-157e02082c7b.png)
We can do something like this

**Comment by domoritz** [comment]
Yeah, I like it.

**Comment by siddhant1** [comment]
Can you give me a list of all the shortcuts available?

**Comment by domoritz** [comment]
You can look in the code. Note that Monaco also has shortcuts. It might already have a way to show them so make sure to not interfere with that. 

It'd be great to have a general help modal with usage instructions and links to Vega and Vega-Lite.
