### ISSUE TITLE
Accidentally closing editor while editing

### ISSUE THREAD

**Issue by ayushnawal** [vega/editor#220]
While playing or editing with the json data , if the editor gets accidentally closed by the user , a warning must be generated before closing the window to save the unsaved changes , as user's last edit will not be preserved automatically .

I have solved issue and now our editor will ask you to save changes you have edited before closing the window .
The "Leave Site ? " dialog box will only appear if you have edited some data in the input panel .

I am attaching a screenshot how it will appear if you have edited something : 

![screenshot from 2019-03-03 04-42-36](https://user-images.githubusercontent.com/36100944/53688790-47fdf280-3d6f-11e9-8788-c650bbd331f5.png)

@domoritz if you don't mind , can i send my PR , so that you can review it :)

**Comment by domoritz** [comment]
> as user's last edit will not be preserved automatically

We actually do save the last state. I think we want this dialog only if there are unsaved changes for example when you have manual parsing on.

**Comment by ayushnawal** [comment]
@domoritz i was actually trying to convey that only if the user have any unsaved changes , than a pop-up should appear before the editor's window gets closed accidentally . I think every editor generate a warning before leaving the site with any unsaved changes .

**Comment by domoritz** [comment]
Go ahead and send a PR to fix this issue. I agree that we should behave like any other editor.

**Comment by domoritz** [comment]
We are actually saving the editor content and preserve it across refreshes.
