### ISSUE TITLE
Invalid URLs

### ISSUE THREAD

**Issue by ayushnawal** [vega/editor#225]
On Navigating any invalid url with editor , no 404 component is rendering .

Till now when we type any invalid url for example : https://vega.github.io/editor/#/abc

it's displaying a blank page (not rendering anything) which should not be the case as it is quite confusing !

@domoritz  if you don't mind i am resolving this issue and will send a PR asap .

Thanks!

**Comment by domoritz** [comment]
I don't think this is a huge deal.
