### ISSUE TITLE
Padding in "chart" results in irrelevant whitespace

### ISSUE THREAD

**Issue by ArexJambusarwala** [vega/editor#231]
![issue13](https://user-images.githubusercontent.com/35253743/53699737-9c59ae80-3e11-11e9-84c2-28aaeecad876.png)
The padding of 10px given to "chart" leaves a white space. 
We can either remove the padding itself or only apply it when the canvas is actually displayed.

**Comment by domoritz** [comment]
It's nice to see that something is missing. It would be interesting to have a way to configure the background color, though. Most charts have a transparent background so it would be cool if users could try their charts on different backgrounds. 

Not the most pressing issue, though.

**Comment by nandinirai** [comment]
Hey @domoritz shall I give it a try?

**Comment by domoritz** [comment]
Which part? I want to keep the padding.

**Comment by algomaster99** [comment]
@domoritz In that case, this issue can be closed.
