### ISSUE TITLE
Gist url validation

### ISSUE THREAD

**Issue by ArexJambusarwala** [vega/editor#232]
Entering an invalid gist URL and pressing load doesn't do anything. It would be better to show an error message so that the user knows something has actually happened.
![issue14](https://user-images.githubusercontent.com/35253743/53711219-1bc59d00-3e67-11e9-8e51-6ad28b05132f.png)
A simple check on fetch can do the job.
Should I proceed with it?

**Comment by domoritz** [comment]
How do you plan to show the error?

**Comment by ArexJambusarwala** [comment]
There is already an error message but it is never displayed because the state is never changed. If the "invalidUrl" is changed this is displayed:
![issue15](https://user-images.githubusercontent.com/35253743/53723272-66f2a680-3e8d-11e9-91d7-5ff6d0e7c121.png)
