### ISSUE TITLE
Enhancement : Add Help and Feedback Section

### ISSUE THREAD

**Issue by siddhant1** [vega/editor#237]
Since the use of editor is growing fastly we have to find a way to give newcomers help and cater their issues when they find one.

Tasks
- [ ] Add a section named "Help and Feedback" which will be a dropdown
- [ ] Add references along with links to the dropdown list
- [ ] Add reporting bugs to the list
- [ ] Feedback section which holds link to the slack channel
- [ ] Keyboard SHortcuts

I will be providing and a mockup and working on this 
@domoritz please update if you fell something is missing

**Comment by siddhant1** [comment]
For now we have to close #219 , #228 and #229 since everything is covered in this one

**Comment by domoritz** [comment]
"help and feedback" is a bit long for a title

**Comment by siddhant1** [comment]
What should be the title then?

**Comment by domoritz** [comment]
Try it out and see how much space we have. I said earlier we could just have an icon.

**Comment by siddhant1** [comment]
Ok ! I will try it out

**Comment by ganeshpatro321** [comment]
Hey @siddhant1 Have you started working in this issue?

I had some inputs.

**Comment by siddhant1** [comment]
Yes ,  I am working on it :)

**Comment by siddhant1** [comment]
Hey @ganeshpatro ! Sure you can present give your inputs here , would love to hear them

**Comment by g3o2** [comment]
A `?` should do for that purpose.

**Comment by siddhant1** [comment]
Closing fixed !
