### ISSUE TITLE
Incorrect error line number for the editor

### ISSUE THREAD

**Issue by kanitw** [vega/editor#240]
For example, it's line 9, not 382 for the following app.  

![image](https://user-images.githubusercontent.com/111269/53993713-05c51000-40e5-11e9-8cb8-5c91bd2708a0.png)

**Comment by domoritz** [comment]
It's character 382. There is no way to access the line number unfortunately.

**Comment by algomaster99** [comment]
@domoritz I have added a feature which will also the number of line where the error exists. :)

**Comment by domoritz** [comment]
Thank you @algomaster99! This is awesome!
