### ISSUE TITLE
Remember location/section when clicking the examples of previous time

### ISSUE THREAD

**Issue by mattijn** [vega/editor#247]
I see lots of work on the editor. That's great. So let me add one from a users perspective.

When I click on the example button I hope it can remember the place where I previously clicked one of the examples. Everytime I need to scroll a long way down and search for the section of examples where I was looking right before.

**Comment by domoritz** [comment]
Just as an idea for now. Can you have one window with the examples open and then use CMD+click to open the examples in a new window?

Still, this is a good idea.

**Comment by ganeshpatro321** [comment]
I can work in this issue, assign it to me @domoritz if it is not been picked up by anyone else.

**Comment by domoritz** [comment]
@ganeshpatro321 I sent you an invite (welcome to the team!). You can assign it to yourself now.

**Comment by ganeshpatro321** [comment]
Thank you @domoritz

**Comment by ganeshpatro321** [comment]
Closed via #249
