### ISSUE TITLE
Wrong Data rendered!

### ISSUE THREAD

**Issue by ganeshpatro321** [vega/editor#250]
If there is any invalid/broken URL, or any invalid spec, the browser is rendering the previously stored data, regardless of the mode.

**Comment by algomaster99** [comment]
@ganeshpatro321 Can I take this issue?

**Comment by domoritz** [comment]
Duplicate of https://github.com/vega/editor/issues/183?

**Comment by ganeshpatro321** [comment]
@domoritz 
No, its not.

In #183, its rendering nothing, but now its rendering the previously loaded spec/data.

**Comment by siddhant1** [comment]
I feel its duplicate of #183.

**Comment by ganeshpatro321** [comment]
Yes, we can somewhat say that, the root problem is "whats rendered" @siddhant1

**Comment by siddhant1** [comment]
@ganeshpatro321 I have opened #252 explaining what is happening . Please check if they are similar and close this one .
I will fix this one later today or tomorrow

**Comment by ganeshpatro321** [comment]
Solved in #254
