### ISSUE TITLE
Bug : Invalid urls rendering previous data

### ISSUE THREAD

**Issue by siddhant1** [vega/editor#252]
#250 and #183 have already reported it but let me explain it clearly.|
The issue is not with particular urls , its with invalid urls.
Vega doesn't check if a particular url is valid or invalid , i just tries to fetch the url and fails.
Then it gets the last item fetched (have to check the code) and renders that .

Try this 
Open https://vega.github.io/editor/#/url/vega-lite/123 , we know it is a completely fake url , but it will open and will render the previously opened editor instance.

I will look into this today , this will solve both #250  and #123.

@domoritz Can you please test and confirm this behaviour.

**Comment by ganeshpatro321** [comment]
Yes, they are, and I am also looking into this issue, I was into it trying to figure out what's happening. @siddhant1 
And, I think #123 is fixed, I see no CORS error in my system.

Thank You.

**Comment by ganeshpatro321** [comment]
I think PR #254 solves the above-mentioned issues, we can close this.
