### ISSUE TITLE
No validation of 'add by gist' form

### ISSUE THREAD

**Issue by saurabh0402** [vega/editor#26]
Submitting the 'add by gist' form with empty field causes this error
![1](https://user-images.githubusercontent.com/12875685/36408563-2282dee6-162c-11e8-931d-ed46d152395c.png)
Also, there's no validation on it currently to check whether the submitted data is actually an URL.

**Comment by saurabh0402** [comment]
I would like to work on this issue.

**Comment by domoritz** [comment]
Great catch. I'm looking forward to your contributions.

**Comment by domoritz** [comment]
Done in #28
