### ISSUE TITLE
Rename a visualisation before downloading

### ISSUE THREAD

**Issue by algomaster99** [vega/editor#265]
Currently, whenever a visualisation is exported, it automatically gets downloaded as `visualisation.*`. Renaming it before downloading would be a good feature to add.

**Comment by domoritz** [comment]
Better, use the name of the example by default. 

You can then rename it in the save dialog. No need for anything else, is there?

**Comment by algomaster99** [comment]
@domoritz Yeah that is fine too. Was just a suggestion :)
