### ISSUE TITLE
UI/UX fixes in help modal

### ISSUE THREAD

**Issue by algomaster99** [vega/editor#267]
### Current UI
![Screenshot from 2019-03-12 16-31-39](https://user-images.githubusercontent.com/35191225/54195537-f549d680-44e4-11e9-9254-1b4e333b0486.png)

### Suggested fixes
- Unnecessary scrollbar
- Alignment of icon and text in feedback buttons
- Tips can be written with better alignment
- Spacing between characters and line-height can be more consistent

**Comment by nandinirai** [comment]
@domoritz I'll fix it and send a PR asap

**Comment by siddhant1** [comment]
I was looking at it in the night and dom pushed it with new changes , I have fixes ready for nearly all of them , will push now

**Comment by siddhant1** [comment]
Closing fixed
