### ISSUE TITLE
Improve method to display error line number

### ISSUE THREAD

**Issue by algomaster99** [vega/editor#278]
To find the error line number displayed (in Google Chrome), we don't have a very promising way instead it's a hack.
Currently this [function](https://github.com/vega/editor/blob/master/src/reducers/index.ts#L65) finds out the line number.
A better approach would be to get the errors using the monaco api itself. This api [function](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#getmodelmarkers) might be a better approach to find the line numbers but it can't be accessed inside [`handleEditorChange`](https://github.com/vega/editor/blob/master/src/components/input-panel/spec-editor/renderer.tsx#L101).

**Comment by joshpoll** [comment]
Closed by #1150, since the JSONC parser provides detailed error span info.

**Comment by domoritz** [comment]
If this is closed, can we delete https://github.com/vega/editor/blob/dfa71a1e2242e5ff279549dc96900b585717245d/src/reducers/index.ts?rgh-link-date=2019-03-13T15%3A58%3A32Z#L75?

**Comment by domoritz** [comment]
Ahh, I see you remove it in https://github.com/vega/editor/pull/1150/files.

**Comment by domoritz** [comment]
Closed by https://github.com/vega/editor/pull/1150
