### ISSUE TITLE
Data viewer makes the browser crash

### ISSUE THREAD

**Issue by mattijn** [vega/editor#282]
I see that https://github.com/vega/editor/issues/173 is merged, but if I try this locally with example https://vega.github.io/editor/#/examples/vega-lite/bar it doesn't perform well. Actually my browser just crashes. 
See the following screencast
![Kapture 2019-03-14 at 20 52 06](https://user-images.githubusercontent.com/5186265/54387438-b611b600-469b-11e9-8328-a70380fa389b.gif)

Not sure if I miss something?

**Comment by domoritz** [comment]
@ganeshpatro321 could you look into this? This is important.

**Comment by ganeshpatro321** [comment]
Yeah, I will look into it, @domoritz

**Comment by domoritz** [comment]
I see the same issue. This should take highest priority.

**Comment by ganeshpatro321** [comment]
Does this bar chart have any signals listeners? @mattijn @domoritz

**Comment by domoritz** [comment]
Not the default one. I crashed the browser with https://vega.github.io/editor/#/examples/vega-lite/selection_layer_bar_month. Which example did you use when you tested this feature?

**Comment by ganeshpatro321** [comment]
population-pyramid in vega mode.
