### ISSUE TITLE
Signal viewer

### ISSUE THREAD

**Issue by mattijn** [vega/editor#283]
Next to the "data viewer" it would be useful to have a tab with a "signal viewer". 

Especially when developing Vega spec I have to use the JavaScript Console to check the signals under `VEGA_DEBUG.view.data._signals.{x/y/z}`. If this is possible with a tab next to the "data viewer", that would be great.

**Comment by domoritz** [comment]
you can do `VEGA_DEBUG.view.signal('x')` btw. But yes, a signal viewer would be nice. @jhoffswell has done some work in the old editor on actually showing the history of signals. It would be nice to bring some of it back to the editor.
