### ISSUE TITLE
Formatting data viewer

### ISSUE THREAD

**Issue by mattijn** [vega/editor#284]
See screencast:
![Kapture 2019-03-14 at 21 11 45](https://user-images.githubusercontent.com/5186265/54388438-012cc880-469e-11e9-814d-38977282cdf1.gif)

It would be tiny slightly better if the table formatting is optimised when the scrollbars are present. Preferably the scrollbars are placed outside the table so the values are still completely visible and I hope that this makes the horizontal scroll bar disappear as well.

**Comment by domoritz** [comment]
This is a CSS issue. Thanks for flagging it.

**Comment by siddhant1** [comment]
Started working on it , thanks for reporting

**Comment by algomaster99** [comment]
@mattijn Can you please send the spec? I am unable to reproduce this error.

**Comment by domoritz** [comment]
This might be a max os specific issue.

**Comment by mattijn** [comment]
Yes probably got this with Safari on Mac

**Comment by algomaster99** [comment]
@domoritz is this still a problem?

**Comment by domoritz** [comment]
Safaris still looks bad, yes. Can you fix it? 

Chrome
<img width="318" alt="Screen Shot 2019-05-05 at 11 00 05" src="https://user-images.githubusercontent.com/589034/57192130-fadffd80-6f24-11e9-883c-731b198772d0.png">


Safari
<img width="282" alt="Screen Shot 2019-05-05 at 10 59 59" src="https://user-images.githubusercontent.com/589034/57192126-f74c7680-6f24-11e9-9473-3548837a5a83.png">

**Comment by algomaster99** [comment]
@domoritz I will look into this as soon as possible. I am assigning it to myself.

**Comment by domoritz** [comment]
This doesn't seem to be an issue anymore, right @mattijn?

**Comment by mattijn** [comment]
The scroll bars are gone now, even when the table is too big to fit (vertically). Scrolling is then the only option for inspection.
