### ISSUE TITLE
Inconsistent indentation in Warning and Error

### ISSUE THREAD

**Issue by neeraj3029** [vega/editor#287]
![Screenshot 2019-03-15 at 6 32 11 PM](https://user-images.githubusercontent.com/31539812/54433513-051a2280-4752-11e9-90a5-6449ab3c9bcc.png)
Warning and Error come in uneven indentation, I'm not sure if it's intentional or not. It would look better if they come at same indentation.

**Comment by algomaster99** [comment]
@neeraj3029 #248 fixes it. Please pull your code to the latest commits.

**Comment by neeraj3029** [comment]
I found this issue on https://vega.github.io/editor . My bad.
