### ISSUE TITLE
What is the consistent behaviour of creating a new visualisation?

### ISSUE THREAD

**Issue by zhirzh** [vega/editor#29]
When creating a new viz, the user should be redirected to `/custom/:mode` and the editor should *reset*, except if the user is on `/edited`.

https://github.com/vega/editor/blob/f4c7d44c1382ca8912a303d7fbbfd8d7a2865d8d/src/components/app.tsx#L54-L64

However, when the user is on `/edited`, the editor **does not** reset but does get redirected. This is inconsistent with the behaviour of creating a new viz.

Should we stop redirecting the user? Thoughts?

**Comment by domoritz** [comment]
Yes, I just saw this issue in the editor as well. Good catch. 

We should redirect and load the right example.
