### ISSUE TITLE
Back button not redirecting when in full-screen mode

### ISSUE THREAD

**Issue by algomaster99** [vega/editor#292]
### Actual
![back](https://user-images.githubusercontent.com/35191225/54478677-f5c2d400-483a-11e9-9167-37cfd86b59e2.gif)

### Expected
Back button should redirect to the edit page.

**Comment by domoritz** [comment]
I think this is an instance of a larger number of problems with the back button. It is generally hard to get navigation to work with state in React.

**Comment by algomaster99** [comment]
@domoritz Will see to it soon. Currently, I'm working on #172
