### ISSUE TITLE
Add feature to upload code to editor from a local file

### ISSUE THREAD

**Issue by ArexJambusarwala** [vega/editor#294]
Many editors have the feature to upload a local source code to the editor. We can create a button in the header for the same.
We can accept only .json files.
Should I work on this?

**Comment by domoritz** [comment]
So far i have not heard of anyone asking for this.

**Comment by ArexJambusarwala** [comment]
I have seen this feature in other editors...

**Comment by domoritz** [comment]
Yeah, it makes sense for other editors but not so much here. For example, observable doesn't have an uploader either. Or even. The p5 editor doesn't have it. let's close it for now.
