### ISSUE TITLE
Signal tab viewer overflow-y scroll missing

### ISSUE THREAD

**Issue by mattijn** [vega/editor#297]
I was checking this new signal viewer tab (great btw!) on a laptop, but noticed there is no `overflow-y: scroll` functionality like there is in the data viewer. If there are many signals the current implementation is little hard to use on smaller screens.

See screencast:
<img src="https://user-images.githubusercontent.com/5186265/54556430-23358c00-49b9-11e9-8815-3eb899a24ace.gif" width="250">

**Comment by ganeshpatro321** [comment]
I will look into it @mattijn
