### ISSUE TITLE
[object object ] showing in signal viewer

### ISSUE THREAD

**Issue by siddhant1** [vega/editor#298]
![image](https://user-images.githubusercontent.com/30566406/54582913-7bf83980-4a38-11e9-903b-2faf422473de.png)
I don't think we want [object object] in signal viewer. 
If this is not the desired behaviour , I will have a look

**Comment by domoritz** [comment]
Thanks

**Comment by algomaster99** [comment]
@siddhant1 `JSON.stringify` should solve this. If you still can figure out let me know. I have written the code for this, I know where to fix it.

**Comment by siddhant1** [comment]
Yup , had the solution up but forgot to push , will send a pr asap

**Comment by domoritz** [comment]
`JSON.stringify` is not enough when the object has cycles or when it's too large. Please use the same methods we use in the data table.

**Comment by siddhant1** [comment]
Looks like @domoritz your pr solved it , I think  we can close this now
