### ISSUE TITLE
Use bindActionCreators everywhere

### ISSUE THREAD

**Issue by domoritz** [vega/editor#310]
See https://github.com/vega/editor/blob/master/src/components/input-panel/spec-editor/index.tsx

**Comment by domoritz** [comment]
Follow https://github.com/piotrwitek/react-redux-typescript-guide#redux-connected-components

**Comment by ganeshpatro321** [comment]
https://github.com/vega/editor/blob/master/src/components/input-panel/spec-editor/index.tsx

This file is correct right?

**Comment by algomaster99** [comment]
> The only use case for bindActionCreators is when you want to pass some action creators down to a component that isn't aware of Redux, and you don't want to pass dispatch or the Redux store to it.

This is written in [Redux docs](https://redux.js.org/api/bindactioncreators#bindactioncreatorsactioncreators-dispatch)
@domoritz What's the use exactly?
I think it will just decrease readability by not letting the programmers know what kind of arguments these action creators can take. For that they will have to navigate to `editor.ts`.

**Comment by ganeshpatro321** [comment]
Yeah I also have the same doubt @domoritz @algomaster99 
Any ways I made the asked changes, forgot to refer it here. #311

**Comment by ganeshpatro321** [comment]
Actually those can be referred in the interface props right? @algomaster99

**Comment by algomaster99** [comment]
Yeah, that's also true. I think we should follow the convention only and use `bindActionCreators`.

**Comment by algomaster99** [comment]
Sorry, accidentally closed it.

**Comment by domoritz** [comment]
The advantage is that we can have better typescript typings automatically because the types of the action functions gets used directly.

**Comment by domoritz** [comment]
Done in https://github.com/vega/editor/pull/311
