### ISSUE TITLE
signal-viewer not interactive when selected upon rendering

### ISSUE THREAD

**Issue by mattijn** [vega/editor#315]
See screencast:
![Kapture 2019-03-24 at 21 03 43](https://user-images.githubusercontent.com/5186265/54885088-d0f0e100-4e78-11e9-8d2f-44fd6d899244.gif)
Only after changing tabs and going back to the signal viewer it becomes interactive.

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/editor/pull/314
