### ISSUE TITLE
Cannot open vega panel

### ISSUE THREAD

**Issue by domoritz** [vega/editor#316]
![editor](https://user-images.githubusercontent.com/589034/54889960-5a49e880-4e64-11e9-9b80-01d1693b000a.gif)

**Comment by algomaster99** [comment]
Even I'm facing this bug in Firefox though not in Google Chrome.

**Comment by siddhant1** [comment]
I am facing this bug after the pr , I tried solving it and faced some issues , I will have a look at it again and generate a fix

**Comment by domoritz** [comment]
We don't yet have a clean fix.
