### ISSUE TITLE
A change in spec makes the data viewer jump to the first entry in the list

### ISSUE THREAD

**Issue by mattijn** [vega/editor#320]
Often I'm working on a certain data transformation where the source is another data object.

Now this data-viewer is updating automatically, which is great, but with every change in my spec it jumps back to the first data object in the list. 

I was hoping the selected data source could be remembered in the state, especially when the data sources are rather similar it can lead to confusion.

**EDIT**: [editor-spec](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KAHdGAExbYwAFgAMuxREgpG1fFoBM+w1ELo1axjOpbRNyGvR5MOANpKIUAhgqBl0VGQtSAAndGUFAODICnQAG1ZkWC1-EJDgSHgvGm5ogE8ogEEFKHDuVhk8SwAOAF8bXLB8wrxisqiAIWrIWvrGnFFRNsS8gqLqEvKcSABhIZGGrW0AZimOwNme+b6lgBE11DqNnABOAEZdva65haiAUXPLsbAm+-bcp8OLyWADEPqNXDs-jNur1FlAAOJgq5gW7XB4dAGwqIACSRXyaAHYWtMwABdRLozokyBhCJRbzsVKRKFQaSsaLwSJLWLxFmQPCxGSwABmJVQ2RJgUlSTwpUIXKg8G4qSZ8EaLJCkGk0S++WFjGQqTU2WGF3BpPkUBKamQ0RN6AQyBkjmckFJxL2YA9uXJIW9FqUWtMYVSWT8iSCuRp4QV-O4yrwjEICQ6yTSGS0wEpRlkEs9+WQVAaYag0WQaqwZtgyG4VDtlsgrEInh6URbrHF2eCBaLeBLMXLeErdWrdXVUCbLdjWcg3pCvuC-vcCDSmTz3eptNjAA8V0yU1HZfKoux0M6D5q1NwME5Mx4vD4oAz9w39YbjUsYUdyl2YmfqLGqgaIgF5JHYDhOC4OC6HQuhuNS0SXB+YAChkFJ-JGmpblEpR7sy1JXjecg4PkLaPvy6CMsyUBvkaUTrI0v4yIwnJaKhyB8oKAFRCYZiNBSSgBkY6Dbmu4YzCUBrIpA7DcAQ15DHhUS7oU+6UvkklOl8kBMsK45aqpsa4YZs6Ce4GDRAA1iWOQbqmR6xmWaqgUYwqIeKJH3t49KUWpfJOkqNqZtKkBabawWekY253kpSwqauQy0chBxYl2mpAZonmxVA8UvlAp7njgvzSkYcL5NlkDGQlr4GnRSwMbOGpJKUFgxSZSxVXlabpAquhzrkaUTs2RR3vqKp3ikPVRLAPSGoyGYtINxi1uFnljakE3po5yDGotJL9ep1IOfSyDbuq1IBdwQUkSFYV2jdkU1KkwabVNn53Y1JX5Q6hpOAq+STRmSyyfJnZNa5jDjZ5gOxgAxFsCOmZ6S2TiND2RZA0VZe1OVKQ2sDBmk9LxqkiaEHQX4vA2BXITBkzg1AZUGQlHV46yhMbUseAk2TdANQ23DCsK1ZfAAtBYg1GD0Z0xRzxMJkmfNmhsks0ZDqQAPJ2PAzBwrZj35D0M1tl4HZgAAvJbKE80mQww1ofUM-s9tFf1HQLh0btegJEDki0QA)
See screencast, here I'm changing the ordering of a field in the data object `table`, but once I check the result of the ordering I first have to change the data object from `raw` to `table`:
![Kapture 2019-03-25 at 21 10 53](https://user-images.githubusercontent.com/5186265/54951026-f34f3100-4f42-11e9-9959-a726d24c1ffd.gif)

**Comment by domoritz** [comment]
Yeah, that would improve the usability quite a bit. Right now, we reset the list when the view changes but it would be better to check whether the previous table exists first.

**Comment by domoritz** [comment]
Done
