### ISSUE TITLE
Debug pane header tabs getting squeezed when resized vertically

### ISSUE THREAD

**Issue by algomaster99** [vega/editor#321]
### Problem
![Screenshot from 2019-03-26 01-54-01](https://user-images.githubusercontent.com/35191225/54951605-104b2a80-4f6a-11e9-8ccf-de4a8e480ffd.png)

This can be fixed by giving the style `min-height: 25px` to  class `debug-pane-header`.

**Comment by domoritz** [comment]
Can you send a PR?

**Comment by domoritz** [comment]
I don't see the problem in master.

**Comment by algomaster99** [comment]
@domoritz I was on master only when I posted this issue(updated with upstream/master). This issue also exists with the [editor](https://vega.github.io/editor/) running on production server.

**Comment by domoritz** [comment]
How do you reproduce it on master?

**Comment by algomaster99** [comment]
![bug](https://user-images.githubusercontent.com/35191225/54956133-3aeeb080-4f75-11e9-8ca3-31be49d176b7.gif)

This is reproduced when you're on the tab signal-viewer or data-viewer.

**Comment by domoritz** [comment]
I don't see that problem in Chrome 74.0.3729.28.

**Comment by algomaster99** [comment]
Oh okay. Then this issue can be closed I guess.

**Comment by domoritz** [comment]
Let me try some other browsers.

**Comment by domoritz** [comment]
I can't reproduce it.
