### ISSUE TITLE
Deploy different versions of the editor 

### ISSUE THREAD

**Issue by kanitw** [vega/editor#325]
e.g.,  https://vega.github.io/editor/0.28/

or https://vega.github.io/editor-archive/0.28/

This would be extremely useful for trying a spec with multiple versions to isolate bugs.

**Comment by ganeshpatro321** [comment]
@domoritz 

Do we have any lead on how to proceed with this?

**Comment by domoritz** [comment]
I don't think we want multiple versions of the editor. Instead, it would be nice if be able to choose the Vega and Vega-Lite versions dynamically, no?

**Comment by kanitw** [comment]
> Instead, it would be nice if be able to choose the Vega and Vega-Lite versions dynamically, no?

That would be better UX.  If it is not much more work, we should do it. 

I just mention vega editor versions as it's a workaround if the ideal UX is too much work.

**Comment by domoritz** [comment]
I think it's easier to support multiple versions of Vega than it is to figure out which version of the editor corresponds to a particular Vega version.

**Comment by kanitw** [comment]
> I think it's easier to support multiple versions of Vega than it is to figure out which version of the editor corresponds to a particular Vega version.

For sure! I've run binary search __manually__ several times today to find the right version to revert to.  TT

**Comment by domoritz** [comment]
Wait, if you need to check vega versions, then you did binary search with a locally deployed editor, right?

**Comment by kanitw** [comment]
Yes, by checking out tags

**Comment by domoritz** [comment]
Why? You can just link to Vega and Vega-Lite and use the version you want that way, no?

**Comment by kanitw** [comment]
Well, it's the same thing if I want to find the newest version that doesn't break to revert to.  Still have to do binary search and re-build multiple times.  Running yarn to install the version is actually faster.

**Comment by domoritz** [comment]
I see. Either way, the use case is switching Vega and Vega-Lite versions so I think we should try to automatically load these libraries from jsdelivr (maybe based on the version in the schema?). That doesn't seem too hard and is easy to use.

**Comment by domoritz** [comment]
Instead, let's do #336
