### ISSUE TITLE
Clicking Signal View clashes the editor

### ISSUE THREAD

**Issue by kanitw** [vega/editor#327]
Try this [spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2XAWJkhtBszace10dt2xkeWKRfpSAMwnU+LAiAEwA1vKKKgC+6hCQeEboSrC+3EaoZgDaBvDoYvCsYjrIZpCI3MawABQurKh0LsgAlGpQ6LBleIyopdEAunFQFPDKeXjZGhCgELNQAO6MmixmAIwArAAMQ3PlyIyBEzhbO7OQyEqjmoxK1GYzc2cAHvdTj-HsN-eQGE+fKWYQptYm93pBfIxkGJNGVrrBdJdSqcwXgAJ6EUo4SAAR1YyW6um6VEgoNmIPe8VR33Q1GoRmEeExUFGrCUE1UUDRGLKuPxzB0jGJHISzDETMgAGFKmzINFSeTHpBiqjkEZJhSwA8NT90EYwmV2Lq1KTdm4xfBuspXhrduwjKxYIhvlzxTdGUYKPk2udLtxrrdOjgspAXoMoGhCGiykplH0TWT4wr3lqKQkkik0hlsgYIWJ3d8zcgLTwVFi7Q6ndEBsjFRg9c70eLDWrhaMxOkytRuNCLkY-bLE6T+m8k5rSeVRpcdOqKSmwSMxtOg-G5nObZBFssnTgNtsV4qUAd8GYTvvdhcrjc7voz4qXjebev-t9fv9A2AgaPH7sIVCYVjNChdAqRrb9OUbHk8TZfkiVKW85i-b9ICpB8wMVGk6QZcUWRlUCkJdSC+UJQUkXgxUCTFMopVZCYyIgOU0LARDtWVVUZ0YtcwJ1esyyNPDH0gQtiytVDGNte1HWtMSUQgrE3VVT1TH4tCfUvANshDSBBjo1MIyjLEYyUODpIQnT6J05ibU4-D01SdJMiDHNGDzNj9EEqEi0tUsoHLSSq20kyoDrfU3II3iW2ZbsOyxLseyUPsYQYsSkrA4cwMs1cyI3JYVh3U9GL2I8jjAXdlPPX1-WvMdpM0tzf2hWEgJA8DuSxXloOI4kMtTFDNXBSEGoAxh4WSeAkRa8V2oJAUurI7rdlYtVl2k6yBOCsp4EYIx4EosrUyErypMCyBfO3PqwqgeSPS9YU9N6yBDL6PbtQqKgluqwKzguwSr12szFREoLKjcbg3uNT6zju6NYxJCGUuSizntmVb10SZI7KzZbPpRrjc3zUSIagaKwBydzzUOssJMrDkDAOksyletiBn+0y4f+gKTO4kLztk5ktp28bIDbYnIFiwD4v7eH0rItLvylx5ZfeSyUcgBcp2KrJbxxs5N1ykr8pUw9DhPPcCovP0ryOlT7w+mrnzc18bnfT8kZ-Ab-05HpSOO76ppgkjYeS12oF67WwQw+laEZDbpXZf6El5nEoOm2Dwc5ijxWomULLmpGlWA1ySZ0sPa11bmTr4+O6cBkuwVOq2fcTq7FLTiHVIt9Sg00jm26hgyYZZpj-vlx95seWuvtszMHJJpyXPe2mPOE7yTqp2Vq3j9bQsT5tvWF97Re7cWEoHaSR4pRWbTHkvsq3NYDa4o3jzy02VPNyqG6Qm2nL-Love9X2yd-ZdWDshb49UPaQDhAiMaADE5+06nGRiY94iLXYmhCe8Qt5822n9Y61dvKYLOPXberVLpsgUjdcMqBIz3UerKYOuxGYL0HvEb6sBfre0JpAQGPxgbIFBmxDkrDqG0OhkZQOgVz6j0RsXeOaMMz2XQStER-V56f2OsTUmBCDRr1iH1HRWJmGykvlIwe0ibQ9zElzBsZChb812pFdsB8xa9kljnRipiKQWK8eZd4l8koc0gPSRQYhiRuTFNQC4HtaaMAAF6uiUIBDESSLjsicSLG4yTolpPXiAaIQA).

![image](https://user-images.githubusercontent.com/111269/55114628-b056a000-509f-11e9-815a-1ce2e47ba05a.png)

**Comment by algomaster99** [comment]
@kanitw @domoritz This is happening since one signal value is a function which isn't handled by `formatValueLong`
```
console.log(formatted, this.props.signal)

>>> var f = function(t) {
    var v = field(t);
    if (v == null) {
      return null;
    } else {
      v = Math.max(start, Math.min(+v, stop - step));
      return start + step * Math.floor((v - start) / step);
    }
  };
"concat_1_concat_0_concat_0_layer_1_bin_maxbins_20_delay_bins"
```

How should we handle this? Any suggestion?

**Comment by domoritz** [comment]
We should serialize it as `function` and also, we should not crash if we get undefined in the react component.

**Comment by algomaster99** [comment]
@domoritz I think that will be a change in `formatValueLong`. Should I submit a PR there?
