### ISSUE TITLE
Use JSON request service

### ISSUE THREAD

**Issue by domoritz** [vega/editor#33]
right now, we hard code which schemas are used for completion. We completely ignore the schema from the spec. This is not good. 

To understand this issue, use a specific version of the schema and note how completion doesn't work anymore.

**Comment by nesterone** [comment]
Hi, @domoritz  
I see it at https://github.com/vega/vega-editor/blob/bfb3c59d03cdbbacdf6a8a4639767121e7aaa644/src/utils/validate.js#L10

If you don't mind I can take this one, play around and send PR for review

**Comment by nesterone** [comment]
After a playing with validator I can propose next solution:
- put schemas in redux store (for example with key as url) 
- provide separate redux action `UPDATE_VEGA_SCHEMA` and `UPDATE_VEGA_LITE_SCHEMA`
- keep `validationSchema` in actions which trigger validation 
- map current schema to the component through connect

**Comment by domoritz** [comment]
Thank you for looking into this. I'm not sure I understand why the schema needs to be stored in the redux store. This issue is about the json request service that is available in vscode but not by default in Monaco.

**Comment by nesterone** [comment]
Looks like I've mixed up validation with autocomplete. Let me take a look on how monaco editor manages autocomplete ... 

P.S.: 

Is it ok that editor won't take to account vega spec`s schema during validation (as far as I see validation is hardcoded )

**Comment by domoritz** [comment]
Yeah, the autocomplete and validation in the editor component are separate from the validation outside the editor component. Ideally, they would be together but I haven't gotten round to fixing it. Thanks for looking into this!

**Comment by nesterone** [comment]
Hi, @domoritz 
I have found a way to make Monaco editor to load schemas on-demand 

https://monosnap.com/file/hlvnvQQCFUedZFb3jDm93aaPe1b4nJ

It's based on the same functionality as VSCode

However, it  requires to modify Microsoft/monaco-json. My current changes here https://github.com/nesterone/monaco-json/commits/custom-request-service

If you don't mind I'm going to make a pull request to Microsoft/monaco-editor with my changes and references to that issue in vega/editor

**Comment by domoritz** [comment]
Oh sweet. Thanks for looking into this. Since we will still only load the latest vega or vega-Lite version, we will have to show a warning if the versions are not compatible but that should be easy. 

If you are rewriting the JSON request service, it would be great to also address an issue with conflicting formatters (https://github.com/vega/editor/issues/93). The problem is that the default formatter and our compact formatter conflict and there is no easy way to disable the formatter in the json module. However, if we have our own version, it should be straight forward.

**Comment by nesterone** [comment]
As far as #33 depends on Microsoft/monaco-json/pull/7 I can cast a glance in #93,

I think we can close #135  for now

**Comment by domoritz** [comment]
Thank you @nesterone

**Comment by domoritz** [comment]
Have you learned something new @nesterone?

**Comment by nesterone** [comment]
Hi, @domoritz 

Not much. Looks like MS guys are ok with my enhancement in general, however, I'm waiting for some remarks to my PR. 

From browsers point of view feautre with on demand loading would work only in Chrome because, other browsers doesn`t support `fetch` API in Worker env.

**Comment by nesterone** [comment]
My PR to monaco-json plugin was merged in master, so in next release of vs-code/monaco-editor it would be available

**Comment by domoritz** [comment]
Sweet. Thanks for keeping track of it!

**Comment by domoritz** [comment]
There has been a new release @nesterone
