### ISSUE TITLE
Crashing of the editor

### ISSUE THREAD

**Issue by mattijn** [vega/editor#331]
If I paste the following spec in an empty Vega-lite editor and go to the signal viewer tab the editor crashes:

```json
{"transform":[{"filter":"datum.Rotten_Tomatoes_Rating!==null"}],"mark":{"type":"circle"},"data":{"url":"data/movies.json"},"encoding":{"x":{"field":"Rotten_Tomatoes_Rating","type":"quantitative","bin":{"maxbins":20}},"y":{"type":"quantitative","aggregate":"count"}}}
```

See screencast:
![Kapture 2019-03-29 at 22 18 46](https://user-images.githubusercontent.com/5186265/55263418-3544e380-5271-11e9-870c-3321d7306637.gif)

After removing the local storage the website can reload again. I tried it on both Chrome and Safari and saw the same behaviour

**Comment by algomaster99** [comment]
#### Cause
`bin_maxbins_20_Rotten_Tomatoes_Rating_bins` signal's value is a function.

@mattijn This issue has been resolved in the development server in this [commit](https://github.com/vega/editor/commit/dc69ee79d6016eb98f63a9e7f7a9e46673529766). This patch will soon be applied to the application in production. :)

**Comment by ganeshpatro321** [comment]
@mattijn you can use [this](https://vega.github.io/editor/#/reset) to reset the local storge. It is a new feature added to the editor.
