### ISSUE TITLE
Load Gist feature rejects valid Gist URL

### ISSUE THREAD

**Issue by iaindillingham** [vega/editor#340]
I've tried a few, but the following Gist URL is rejected with "Please enter a valid URL." I can't see anything in the console to suggest what's invalid; it follows the pattern in the example.

https://gist.github.com/iaindillingham/7b5862f57cfef9a1459a60428985b49d

**Comment by domoritz** [comment]
Hmm, The problem is that your streamgraph file is not recognized as a JSON file.

**Comment by domoritz** [comment]
Try reaming the file to end in `.json`

**Comment by iaindillingham** [comment]
Thanks! That works. Couple of things:

* I'd assumed that adding the filename in the filename field would have overridden this.
* The `.vl` and `.vg` extensions are the default for the Vega Viewer VS Code extension.

It's certainly no bother to rename a file, though.
