### ISSUE TITLE
provide simple input UI to search vega examples by chart type

### ISSUE THREAD

**Issue by RandomFractals** [vega/editor#341]
I think it would be 😎 if instead of showing all 100+ #vegaLite examples gallery popup https://vega.github.io/editor/#/examples/vega-lite  
1 could search online examples by #chartType, as I do it in #VegaViewer :)

see this twitter post for more info:

https://twitter.com/TarasNovak/status/1117843212033568769

**Comment by ganeshpatro321** [comment]
Yes, we have plans to implement this.

**Comment by RandomFractals** [comment]
let me guess: same release as #vegaThemes? 

https://twitter.com/TarasNovak/status/1115363634585264128

🤗

**Comment by domoritz** [comment]
We release as soon as a feature is in Master so I suspect these feature will be in different releases.

**Comment by domoritz** [comment]
I use it but to use it as a dev, I need to be able to use the locally installed version, not just the latest version.

**Comment by RandomFractals** [comment]
@domoritz Dom, good to hear that you are using it. I did look into supporting different vega and vega-lite json specs based on $jsonSchema when I pushed out my v4.x and found that most examples worked with that update to vega 5 & vega-lite v3.x with my ext.

If there is more to it, please elaborate in this issue, or open new one in my repo.

I'd love to support all vega json versions, if you could provide more info how those $jsonSchema refs in vega specs map to your vega and vega-lite libs major releases

https://github.com/RandomFractals/vscode-vega-viewer/issues/19#issuecomment-478597166

**Comment by domoritz** [comment]
It would be nice to have a search but first, we would want to have a larger set of examples with community examples.
