### ISSUE TITLE
Gist loading should not ignore non-json files

### ISSUE THREAD

**Issue by domoritz** [vega/editor#347]
It would be good to support non-json files as Vega or Vega-Lite specs when the user explicitly specifies them. I have seen people trying to use `.vega` files and they don't work because we limit ourselves to JSON in https://github.com/vega/editor/blob/97e150be24f5e881e7abe53ef56c2be077af6068/src/components/header/gist-modal/renderer.tsx#L115.

**Comment by algomaster99** [comment]
@domoritz I think we have applied a filter to get only `JSON` files. https://github.com/vega/editor/blob/a49647733c7a7498cb8c7097d83398cb4a88e283/src/components/header/gist-modal/renderer.tsx#L187. Should we close this issue then?

**Comment by domoritz** [comment]
No. https://gist.github.com/domoritz/3ab075a60cf92b8c19eb8a312e7b08b3 still doesn't work.

**Comment by domoritz** [comment]
http://0.0.0.0:8080/#/gist/3ab075a60cf92b8c19eb8a312e7b08b3/spec works now.

**Comment by domoritz** [comment]
It would be nice if I could just paste `https://gist.githubusercontent.com/domoritz/3ab075a60cf92b8c19eb8a312e7b08b3/raw/ad920266b18cc7885b5c1b9a809907882084543a/spec` in the URL field of the GIST loader btw.
