### ISSUE TITLE
improve code quality

### ISSUE THREAD

**Issue by zhirzh** [vega/editor#35]
As of now, the codebase doesn't follow any coding style-guide and isn't consistent in writing. I recommend using something like [prettier](https://github.com/prettier/prettier) for automatic code formatting. Once in place, it can be [integrated with editors](https://prettier.io/docs/en/editors.html) for automatic format checks "on save".

**Comment by zhirzh** [comment]
Also, there should be eslint config to enforce rules that prettier can't fix.

The project currently uses [eslint-config-react-app](https://www.npmjs.com/package/eslint-config-react-app) but it isn't geared for large-scale projects. A better fit would be the [airbnb config](https://www.npmjs.com/package/eslint-config-airbnb).

**Comment by domoritz** [comment]
We already use tslint: https://github.com/vega/editor/blob/master/tslint.json and test it on travis: https://github.com/vega/editor/blob/master/.travis.yml#L6. So "doesn't follow any coding style-guide" is a bit strong ;-) But yes, it can be improved.

**Comment by domoritz** [comment]
Do you want to add prettier? I think that's a great idea.
