### ISSUE TITLE
Weird line breaks in data viewer

### ISSUE THREAD

**Issue by domoritz** [vega/editor#358]
In https://vega.github.io/editor/#/examples/vega-lite/trellis_barley

<img width="459" alt="Screen Shot 2019-05-29 at 12 03 26" src="https://user-images.githubusercontent.com/589034/58583886-d74d6180-8209-11e9-8054-0006497c14a2.png">

**Comment by siddhant1** [comment]
Will try to investigate and resolve

**Comment by siddhant1** [comment]
![image](https://user-images.githubusercontent.com/30566406/58612787-66717c80-82d1-11e9-9171-be676b0bf5a7.png)
Mine is working fine!

**Comment by siddhant1** [comment]
![image](https://user-images.githubusercontent.com/30566406/58612828-899c2c00-82d1-11e9-84fa-faa9d7f4fda9.png)
Mine is working fine!

**Comment by algomaster99** [comment]
Works fine for me too on both firefox and chrome.

**Comment by domoritz** [comment]
Hmm, I cannot reproduce it anymore.
