### ISSUE TITLE
[HIGH PRIORITY] Latest Published Editor does not always update Vega spec

### ISSUE THREAD

**Issue by kanitw** [vega/editor#359]
Try opening https://vega.github.io/editor/#/examples and select simple vega-lite bar example and then select another Vega-Lite example.  You'll see that the Vega spec doesn't change anymore!

**Comment by kanitw** [comment]
Note that my local branch at d5dde7c124a933bcda27774d7b97fde3f9bb8e05 works fine.

**Comment by domoritz** [comment]
I cannot reproduce this.

**Comment by domoritz** [comment]
Just to highlight, look at the **Vega** output.

**Comment by domoritz** [comment]
This is probably caused by https://github.com/react-monaco-editor/react-monaco-editor/issues/215

**Comment by domoritz** [comment]
I reset gh-pages. We need to fix this before we can make other releases.

**Comment by kanitw** [comment]
Fixed?

**Comment by domoritz** [comment]
In gh-pages, yes. Not in master since we are waiting for react-monaco-editor/react-monaco-editor#215

**Comment by kanitw** [comment]
Why not reverting the version in the master for now?

**Comment by kanitw** [comment]
In general it’s better to make master usable

**Comment by siddhant1** [comment]
@domoritz should I revert?

**Comment by domoritz** [comment]
Yes, that would be good.
