### ISSUE TITLE
Revise menu bar

### ISSUE THREAD

**Issue by domoritz** [vega/editor#369]
Our menu bar is getting a bit cluttered. Let's revise it. Here is a list of functionalities we want somewhere in the UI with proposals for changes. 

* Switch between Vega and Vega-Lite
* Format -> move to editor or edit menu
* Clear -> move to editor or edit menu
* Run (with switch between auto and manual)
* Export (download as image/json/pdf)
* Share (share editor state via URL)
* Save (to GIST, not yet implemented)
* Help
* Examples -> move to "open/load"
* Load from GIST -> move to "open/load"
* Settings (not yet implemented)
* Docs (Vega or Vega-Lite) -> move to help
* Log in

Thanks to @arvind for input on this.

**Comment by arvind** [comment]
Thanks for getting this started @domoritz! All of the above makes sense to me except I would maybe keep Examples in the top-level, just to give newcomers a super easy jumping off point. (I associate open/load with past visualizations I've already created/worked on.)

**Comment by algomaster99** [comment]
Docs are already there under export modal so we can simply remove the button.

**Comment by domoritz** [comment]
I'm okay with removing the docs. Let's revise the style of the help modal, though. The header margins are off.
