### ISSUE TITLE
Add format button

### ISSUE THREAD

**Issue by domoritz** [vega/editor#37]
Depends on #36

**Comment by apollonian11** [comment]
Taking up this issue. ✌️

**Comment by apollonian11** [comment]
@domoritz If the button position looks fine, I can go ahead and submit a PR.

![feature-format-button](https://user-images.githubusercontent.com/2150306/36946788-6266b0b2-1fe8-11e8-91cd-ff564709b94f.gif)

**Comment by domoritz** [comment]
Sweet. The only issue is that we don't see this in the automatic parsing mode but I'm okay with that for now. 

Just wondering: is it possible to override the formatter that's used for right click -> format document?

**Comment by apollonian11** [comment]
When automatic parsing mode is on the button aligns to the right margin.
Ref.
![screen shot 2018-03-05 at 12 39 17 am](https://user-images.githubusercontent.com/2150306/36949387-adc6847c-200d-11e8-997e-fe5df870c375.png)

Secondly, I do think it might be possible via: https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#registerdocumentformattingeditprovider

**Comment by domoritz** [comment]
We should probably improve the style. The current buttons were a quick hack.

**Comment by apollonian11** [comment]
Sounds good! 
I'll come up with a few subtle designs to choose from.

**Comment by apollonian11** [comment]
@domoritz Some explorations

https://codepen.io/abhi/pen/qxGNMZ

**Comment by domoritz** [comment]
I like the last one but does it work on white background? Let's have one style for all buttons in the UI.  Look at the button in the gist modal and the toolbar in the bottom right.

**Comment by apollonian11** [comment]
Sure, I chose the background color based on the header's light gray background. I'll tweak it a little to work on a white background.
