### ISSUE TITLE
Workflow of loading Gists

### ISSUE THREAD

**Issue by algomaster99** [vega/editor#371]
This issue will discuss how the loading of gists will work.

Firstly, I am thinking of to divide the modal into two parts using a vertical divider. Something like this:
![Screenshot from 2019-07-05 16-07-00](https://user-images.githubusercontent.com/35191225/60717628-fe512e80-9f3f-11e9-85e2-77141ccccb6b.png)

#### Left
- The left portion will simply have input fields which will load any gist whose ID is available. (No need to enter the full URL). Can be achieved using [this reference](https://developer.github.com/v3/gists/#get-a-single-gist) from the guide.
- We can look for the `$schema` attribute in the content and find the visualization type. This will not enforce a user to add an extension to their gist.

#### Right
- If authenticated, it will show the list of all the gists the user has created. I have created the API for fetching the list. The response will look something like this:
![Screenshot from 2019-07-05 16-51-20](https://user-images.githubusercontent.com/35191225/60719402-28591f80-9f45-11e9-9d7d-94e4920663fa.png)
- This will be displayed as a list and upon clicking one of them, we can request the source code using the `raw_url`.
- It will further follow the same process to find the gist type.

**Comment by algomaster99** [comment]
@domoritz Please suggest some ideas.

**Comment by algomaster99** [comment]
### Mock-up of header
![Header](https://user-images.githubusercontent.com/35191225/60757596-5c5a4080-a02a-11e9-8eaf-20132ecfe45d.jpg)
The circular button on the leftmost side will show user profile.

### Load GIST
![Load GIST](https://user-images.githubusercontent.com/35191225/60757697-78aaad00-a02b-11e9-908c-cdeb948379f0.jpg)

### Save GIST
![Save to GIST](https://user-images.githubusercontent.com/35191225/60757700-82ccab80-a02b-11e9-9019-007feaee9d67.png)

Let me clarify the `File Name (auto-filled)` field. If the gist is already loaded from some file, its name will be filled there. Otherwise, you may change the name and chose the following two buttons. **Add a file** will add another file to the cuurent gist (make sure to rename the file name). **Edit the current file** will edit the content in the file or if the name is changed, it will be renamed.

### Figma Link
Please check [this link](https://www.figma.com/file/CoRMRbayr2OJ87aXlqmThd2Q/Vega-Header?node-id=0%3A1) for prototyping of the header. I have also created a design for **Save GIST** and **Load GIST** button which are attached above.

@domoritz @arvind

**Comment by domoritz** [comment]
Why did you decide to put help on the left and load on the right? I would have swapped them.

**Comment by algomaster99** [comment]
@domoritz There is no particular reason. I will change it.

**Comment by domoritz** [comment]
Looks good. What else do you want to put into the Edit menu.

**Comment by algomaster99** [comment]
@domoritz I don't know. Do you have any suggestions?

**Comment by domoritz** [comment]
Can we open the command menu:

<img width="462" alt="Screen Shot 2019-07-06 at 5 30 10 PM" src="https://user-images.githubusercontent.com/589034/60758116-bdc2e500-a013-11e9-91fa-316af3b911bd.png">

**Comment by algomaster99** [comment]
@domoritz In the edit button? Will have to look. The monaco editor API must provide one function to do so.

**Comment by domoritz** [comment]
Works now.
