### ISSUE TITLE
Revise the layout for vega /config

### ISSUE THREAD

**Issue by kanitw** [vega/editor#372]
Putting config in the same location as compiled vega is a bit confusing.

Basically, we have two inputs (the vl spec and config) and vega is the output.   Putting one of the input in the place of the output mixes two things together.  

In the future, once we have https://github.com/vega/vega-lite-to-api for getting vega-lite-api and altair outputs, then it will be quite confusing.  (It would be natural to group vega output with vega-lite-api and altair, but not with the config.)

**Comment by domoritz** [comment]
The reasoning was that you always want to see the Vega-Lite or Vega input. To me, the Config and Vega output are less important so I decided we group it together. Once we add more inputs, we should revise how we lay things out.

**Comment by kanitw** [comment]
> To me, the Config and Vega output are less important so I decided we group it together.

We should group things by their semantics rather than importance.  

The fact that we label it as "compiled Veg and Config" is quite confusing since config is NOT a compiled output.  It is an input. 

![image](https://user-images.githubusercontent.com/111269/60748729-d9f85080-9f45-11e9-8ea0-3d2490e47d2c.png)



I like @arvind's suggestion on Slack: 

> I could imagine the top editor(s) being the writeable ones (i.e., input), and the bottom being readonly (i.e., output). So, a simple change might be to move the “config” tab to the top.
