### ISSUE TITLE
Make the export button clearer

### ISSUE THREAD

**Issue by kanitw** [vega/editor#373]
The design of the big buttons in the new export screen is a bit unconventional — in the sense that it’s blending a bounding box with a button.
Thus, without knowing that the big boxes are button, and without moving mouses around, I didn’t realize at first that they are clickable.

**Comment by domoritz** [comment]
It's actually not new but we merged export and sharing into one dialog ;-)

In https://github.com/vega/editor/issues/369, we are discussing how we will change this soon, though. 

Do you have specific ideas for how we can make the buttons look more like buttons?

**Comment by kanitw** [comment]
As mentioned on Slack, making the text for the header smaller and make them an actual button will make them look like a button.

This is a quick sketch (but you should also change the font size + add background colro for the button):

<img width="324" alt="Screen Shot 2019-07-05 at 4 52 01 PM" src="https://user-images.githubusercontent.com/111269/60748693-7e2dc780-9f45-11e9-885b-70efa666621f.png">

**Comment by kanitw** [comment]
Also a button may include visual cue on click  

![image](https://user-images.githubusercontent.com/111269/60748788-5be87980-9f46-11e9-9e3c-9f783ef036d1.png)
