### ISSUE TITLE
Data viewer should scroll rather than wrap?

### ISSUE THREAD

**Issue by mcnuttandrew** [vega/editor#382]
![Screen Shot 2019-07-11 at 11 47 05 AM](https://user-images.githubusercontent.com/6854312/61076741-c891c700-a3d1-11e9-8ee4-0da15f307a1e.png)

It seems like it should be the case that the data viewer should scroll rather than wrapping each of the cells (as in screenshot above). I find wrapping single numbers across multiple lines to be pretty confusing. That said this is a fiddly ux-issue, so I understand if this is how it's meant to be, just thought i raise a concern

**Comment by domoritz** [comment]
Thank you for writing up the issue report. This is by design. Horizontal scrolling is difficult so we decided to prefer vertical scrolling. I think at some level we enable horizontal scrolling, though. I'm happy to revise the thresholds.
