### ISSUE TITLE
Invalid json in config editor breaks editor

### ISSUE THREAD

**Issue by siddhant1** [vega/editor#395]

**Comment by domoritz** [comment]
Please describe the steps to reproduce this issue.

**Comment by domoritz** [comment]
We should be careful with invalid JSON like we do for normal specs.

<img width="601" alt="Screen Shot 2019-07-20 at 10 15 24 PM" src="https://user-images.githubusercontent.com/589034/61583707-fe564e80-ab3b-11e9-8475-7c4d3604cd95.png">
