### ISSUE TITLE
Use compact stringify for formatting

### ISSUE THREAD

**Issue by domoritz** [vega/editor#41]
@apollonian11

**Comment by domoritz** [comment]
Follow up for https://github.com/vega/editor/pull/40

**Comment by apollonian11** [comment]
A little late. Will be trying it a try now. Ref: https://github.com/Microsoft/monaco-editor/issues/690

**Comment by domoritz** [comment]
Any updates on this?

**Comment by domoritz** [comment]
Actually, I like https://prettier.io/ for JSON formatting much better. 

I think it's really nice. Check out this example: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6IAkBnMALOAWwEMMkM8YYAHbJAenoDc4BzYgOlYEsY8BXAEYduEergIlmbYswDMHAFbZoGADQYA7twAmfMgFYADEY0gC3VpTJyTZ6sR07uUVmXQgYEamQCMpjAAbOAAzGDIAFgCQQQgqCEIyACZogCdLa2R-AF8zYn4vbG4ALzgyDChoMpAzSCgQy3cMYgAPbmwmkB0E4hcyEOJA7DgzGG4wAGsAZRLqpDlR8YmAYQhAiFTykABiAA599SDiQThAgDFocOQMAFloYkg1AAJV-nS4VKeAOThNDGzchgiqwoIMOsgANoeUGEOYYEipHhQQ4gJiDfhzFK5aHEWFbPAQFibGoYVSQjxwFiwcHkEAAKiQhAg-GGhI+KIQkB0cPMbOJ2IwlIQMBpGAZTJZcGZVzMnIg3K2wWILH+agpVJFW3FzOG3U0yJJIDlCuuIGGwTAVwFRo1ovpjJ1cH4PkNxp5qVOcGIw3+AF1rTCeS0ICEQsMZRhnTpiPAtgBaAAUFisMCeAGong4nC5WBxYvFCABKVU4vGmgCeIbDcAjICjMZ5ie0ejw6czjmcrg4wTCxZAAdxQdSxFc1TM9djpohpiezb4vpLFUHW3Lw9HKInPIhycozyMC-7aqXZdpeoNZjRgQxZCg-ECgTMZKQUMFtq2Xn4+AQOg31Gjk9pW970XG1hTtCVdQgfVng-fBsBgYhUlrTcthacsEz7bJ-SPEBA1QsA3hRS9r2QICH1JA1n3VMCtgguAzxg5k4IQpDGM-AgoB-Q0UNNbBAnGOAExaboiz9AcTwwcsCOJC90TmMjH0ol9QOpWjHQYp5YLweDEJgNiv0439-x5PiBITcsRMw7DSx5blAgQoi5LIac1H3RTnOo1TySBZlUjAHltE4qCURgctqB5OimRVQ06mwfgTxgVIMTME4YE0OAEA8jBQvCtTJTPECVDefytkCvUQrCiLHWdMScJynktKiscMFi+K5kS5KMAaez2VNIVYA4LS4GwbsEFYPgngAXmmp5fD9cc-wbLYzyeAB+J4ITPadfTjFoMOedDCzjLbfF9X0niQDbTH3WqbK2Ed8A2RyrzmFy3IorKVM1U1NAIU4jKWqcXCJGAEwAchaXBBjgMHnj2wtC2eYGPlBsHyyh4JYaeQ7CwPa1+u+pAPHq98mO0lja26+BiVpAnBrJ4bRtcPhpsmpJVUjRaAIwCEhJE7a22EhIIVOwsnnoJ4kmecz+f3NsLOF0XxclvHrOPHliggBJnpIpBfHc7yvrtX6MsCABCFEQg2ErkA6kZOeMrZqCghNfA4Ex9aeOm7IQgBNJ46UzF3fAANmeb3TgQu5uQRkCCZpDxgVBQJlvaGB2cPLrrfapL7brLnbLT3xleceCM6w8TC-gubDWIuZoifZT486EnTS0nSkMt7gepp19hXp9jGeCZm8FZ8uFsd01qBcfAABE04ewSCcwnDm+QRPLGT1Oy45-PJ9PNPy7V3Dl1NUv051+uDaovuvKJ7LKtJ9impRVqEtzswqd62mNQHr8RuHuNUe01x4O0BrSaeUA54LygUvDUVlK6oREgDbmZp+L+SEnAFoMA+xmA9A8K4SABhDDzo3TyhMN4gkGMtSOpBM573ATzFo0kBYZmwA4KAQlpJi0Dj7YgAsJZzjwHDFhp02zsJHFwt4PCnh8IEbOXQ8445vnXkCTe1DTSa21vQnitIIQPQJKkVhTw+bCzlnGJ4BiNjbRkVowgzwrFGLlhmUxhARbnQsY4mxAcnh2NVogisyDuIFy2KZDB5YsE4JRPgy0-QwSkKUuQhOaiqEpzPrQ3euieZSTeMYiRnCcmpBkXIsREsdx6WxqI86bCOHmW4T4kp50ylwAyDAPGq8VH3zNOotJtI7GZJCVOLxYiXEKzceYyxUDDHuNsVrexkzHpGJGSYsZ7inieKmdYpWgc-G3XVqE2YKCeRgECLiagCYUjK3ya4xGs1nj+BMFZMw-46E3xPhJEAzsXDfXHKkXpGAXn0EqKkEggQ4xJB0EoFQ55sprmwFbEFn1W602wcKLupwuK0n4CiJOGjaQtEiSBZFgpUWwHRYETFGAmA4p6SuQl-Z-S+jMBjYan08KmkhmAaGKJSipAgHEkhzyeh9FUd01JSDtGAhAGuVgcxKFbw5TK6oAIcLstpOjLlwQeUfH5cgYhwwhUkBFV03F-yQBjN3kqzopqVxWv7FhPIBKaTKRZahV1hoNjcDRW3bwKIqzhmtbSjl-qaz-GtO69V7rHzvDJaadIKY-WhgDaKm1FYQ1WgdfCRCExnXE0frxcshBYhpM-nyxIoqXlOwgN88EUqTncBdEgO2sooHyjlYKWA38PDdUCAAeQcGAXg5ZOh1zIEYDgIcpU9pHU5Xi8BTiCBemGie4CPAtGtZqoMUaupeopVsbF9Dh0ps3SubdIAGgYq2NS+hRRSiBvFbxQ59qzAEiJJ0adorR2mgaB6QQ6RJjLqCF6aKXSP1dK-bSeCptF0kRVUCT0sSU1PpNUGyDT6zCEDvIQgwcHpWem9O27pd6kMPrQ8RgEAJ-Q1BAN4MY0BsDr0+ekWAAB1RReBkC7FMJ4Y4bGWzIClt01wwQACK-A4hwD1fEtQnhhzdxzKsQgJBkC4SqNRv9DwJg1imAOnMtsP4gGUC0AAQsOSY2nBwABkXCSaIdJz5iFhipBU8oaA1HhiEG4Pp5KdZhgABVjgMbs4KkALgnMwAAArDlYMp4LBq8MAEd+DcA9FF4gMXiBSZC9QPlwwWPDmoCpnLw0PgsGo4hPlmgIuIQQEFkAypq06Go90MAWX4vehgG1kYNGCjUAKEkLrAIgA. 

@kanitw if you like this as well, we can apply the same formatting in our Vega-Lite examples.

**Comment by kanitw** [comment]
I like this too, with `--no-bracket-spacing`. 

We should apply this to our autogenerated output (normalized vl specs, output vg specs), but not to normal vl specs.

**Comment by domoritz** [comment]
Yep, let's do that. 

It's nice out have a single library to take care of all formatting so we should use prettier in all Vega related projects.

**Comment by domoritz** [comment]
I'm having a hard time to get prettier to compile and it's also a huge package. https://github.com/lydell/json-stringify-pretty-compact looks like what we want, though.
