### ISSUE TITLE
Sharing dialog has no button to copy URL

### ISSUE THREAD

**Issue by domoritz** [vega/editor#431]
<img width="1055" alt="Screen Shot 2019-08-04 at 6 45 20 PM" src="https://user-images.githubusercontent.com/589034/62426669-13a8ac80-b6e8-11e9-8f72-f36c6221ec64.png">

**Comment by siddhant1** [comment]
![image](https://user-images.githubusercontent.com/30566406/62426753-89bc0c00-b706-11e9-84a7-54194a87ff23.png)
Working fine for me

**Comment by domoritz** [comment]
Oh no, it's my adblocker.

**Comment by siddhant1** [comment]
🙃

**Comment by siddhant1** [comment]
Still an issue?

**Comment by domoritz** [comment]
Yep
