### ISSUE TITLE
menubar doesn't collapse icons on small screens

### ISSUE THREAD

**Issue by domoritz** [vega/editor#432]
<img width="843" alt="Screen Shot 2019-08-04 at 6 55 50 PM" src="https://user-images.githubusercontent.com/589034/62426767-88301b00-b6e9-11e9-88d0-046d3e7f5f5c.png">

**Comment by domoritz** [comment]
Intorduced in https://github.com/vega/editor/commit/c969f3fdd49e9f38b95345b4a3152f3ba0283709#diff-c4c1c0acbe8bc7d53bcb98f17b4ab439

**Comment by siddhant1** [comment]
I made a pr lol !

**Comment by domoritz** [comment]
Thanks. I used your code as it's a bit cleaner.
