### ISSUE TITLE
Sometimes the editor just shows [Error]

### ISSUE THREAD

**Issue by domoritz** [vega/editor#434]
<img width="258" alt="Screen Shot 2019-08-05 at 12 01 48 AM" src="https://user-images.githubusercontent.com/589034/62429842-4799c700-b714-11e9-925e-2eab4da9fca7.png">

Now very useful :-P

**Comment by domoritz** [comment]
Reproduce with https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSl46I7HmKVAX3URIFeMut4zAbQ0RQCCCoADN0eGRvfUgQxmQxTTNIAHkjRiYVVSg8AE9CZCSlblRGJXRTZ38gyFh8+DNA4OqMIwBrJMJuUu8XJtdkJQ9NUuoGqr7IAA8GmLiEpIAJbltkToB3ZCM1bLyCnEgAR1Z0JTxmHUYqSEq+4Mgcmdj4xP2AWUYxZFgAfXyjb4A4uUxMptpBcvkkkcTmddGcro5xkFEX0UcjegEkTFwpFHnMXlBUulSmCIXsoEUSmUKhjqrVkPV9EjXC12vszvB2rS7gMhiMxrdqtNok95vslit1ptSbsocdTud4QU0aikSqwGiALogRFAA

**Comment by siddhant1** [comment]
https://github.com/vega/vega-lite/blob/389e94b386b0a9455c72a8b19d9767f6d42524d5/src/compile/compile.ts#L206

The compiler does not return errors

**Comment by domoritz** [comment]
Vega-Lite throws errors, we log warnings. 

The one above is coming from Vega (look at js console).
