### ISSUE TITLE
Lazy loading code

### ISSUE THREAD

**Issue by domoritz** [vega/editor#443]
We should consider using https://reactjs.org/docs/code-splitting.html#reactlazy for code that is not always needed like the sharing via URL. This could reduce the startup time of the editor.

**Comment by siddhant1** [comment]
Lets do it!

**Comment by domoritz** [comment]
We need to be careful and profile whether this makes a difference.

**Comment by domoritz** [comment]
Let's not do this until we have proof that code splitting actually helps.
