### ISSUE TITLE
remove unsafe react lifecycle methods

### ISSUE THREAD

**Issue by domoritz** [vega/editor#446]
<img width="553" alt="Screen Shot 2019-08-11 at 1 51 59 PM" src="https://user-images.githubusercontent.com/589034/62833457-56660980-bc3f-11e9-943a-02b9b416a4e3.png">

**Comment by RisingGeek** [comment]
hey @domoritz can we use getDerivedStateFromProps lifecycle instead of componentWillReceiveProps and store the props in state as we cannot access this inside getDerivedStateFromProps?

**Comment by domoritz** [comment]
Do you want to give it a shot and send a PR?

**Comment by RisingGeek** [comment]
yes, sure!

**Comment by domoritz** [comment]
https://wattenberger.com/blog/react-hooks is a beautiful intro to react hooks.

**Comment by shakti97** [comment]
hey @domoritz is this issue still open ? if no, I would like to give it a shot

**Comment by domoritz** [comment]
It is and we would love your contribution.
