### ISSUE TITLE
Warn about incompatible versions

### ISSUE THREAD

**Issue by domoritz** [vega/editor#447]
We should warn users about versions mismatches like Vega-Lite does: https://github.com/vega/vega-embed.

**Comment by adrijshikhar** [comment]
@domoritz I would like to contribute on this issue, can you help me out?

**Comment by domoritz** [comment]
This is a good issue to start with. Start with setting up your local development and see where we are parsing the Vega spec. Then add a check similar to https://github.com/vega/vega-embed/blob/34b84b913c82066705df1535804741d812462672/src/embed.ts#L144

**Comment by adrijshikhar** [comment]
I have already setup the repo. I will start working on the issue as directed. Thanks

**Comment by adrijshikhar** [comment]
can I add .vscode in .gitignore and make a new PR, because my vscode generates settings.json file whenever I open it in the directory.

**Comment by adrijshikhar** [comment]
src>index.tsx
line 29 : `window.VEGA_DEBUG.VEGA_VERSION = vega.version;`
Is this the place you were talking about?
@domoritz

**Comment by domoritz** [comment]
It's already there: https://github.com/vega/editor/tree/master/.vscode

**Comment by domoritz** [comment]
> line 29 : window.VEGA_DEBUG.VEGA_VERSION = vega.version;

No, that's where we add the version to the global namespace so you can debug.

**Comment by adrijshikhar** [comment]
ok, so is this the version against which the version check should work?
`vega.version`

**Comment by domoritz** [comment]
You want to compare vega.version and vl.version to the versions extracted from the $schema property of the spec.

**Comment by adrijshikhar** [comment]
where should I call the function to console log the version mismatch?

**Comment by domoritz** [comment]
Try to step through the code to find it. Also, we don't just want to log it but show a proper warning in the editor panel.

**Comment by adrijshikhar** [comment]
when should we show the error for version mismatch?
as soon as editor is opened?

**Comment by domoritz** [comment]
Show it as a warning in the log panel when a spec is parsed. Just like other warnings.

**Comment by adrijshikhar** [comment]
`Invalid specification {"$schema":"https://vega.github.io/schema/vega-lite/v4.json"}. Make sure the specification includes at least one of the following properties: "mark", "layer", "facet", "hconcat", "vconcat", "concat", or "repeat".`
what does this mean?

**Comment by domoritz** [comment]
It’s not a valid spec. Select an example instead.

**Comment by adrijshikhar** [comment]
`parseVega` calls `validateVega` and `parseVegaLite` calls `validateVegaLite`, with `currLogger` being passed which adds warnings, which are then rendered in the `error-pane` component.

Now how should I add the check to render the warning for mismatch version?
In the `parseVega` function?

**Comment by domoritz** [comment]
> Now how should I add the check to render the warning for mismatch version?

Does https://github.com/vega/editor/issues/447#issuecomment-586757261 answer your question?

**Comment by adrijshikhar** [comment]
Not the check, I get the check.
I am asking whether I should add the check in `parseVega` function itself, or somewhere else?

**Comment by domoritz** [comment]
I'll leave that decision up to you.

**Comment by adrijshikhar** [comment]
@domoritz thank you for helping me out. It was nice working with you.

**Comment by domoritz** [comment]
Thank you for implementing this feature!
