### ISSUE TITLE
Saving to GIST

### ISSUE THREAD

**Issue by algomaster99** [vega/editor#448]
A button can be added inside export modal which will create a GitHub gist with the current vega/vega-lite specification written in the editor. (GSoC target)

Further, we can add forking and updating functionalities.

**Comment by ashu8912** [comment]
Hey @algomaster99 can i takedown this issue

**Comment by domoritz** [comment]
https://github.com/vega/editor/pull/489 is a start but needs to be finished.

**Comment by domoritz** [comment]
Works now
