### ISSUE TITLE
Use simpler UI element for renderer picker

### ISSUE THREAD

**Issue by domoritz** [vega/editor#475]
Instead of a dropdown, we could just use a simple https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio input.

**Comment by RisingGeek** [comment]
@domoritz Which dropdown you are talking about?

**Comment by domoritz** [comment]
If you open the settings, the first drop-down is there to change the renderer but we only have two.

**Comment by RisingGeek** [comment]
I would love to work on this.

**Comment by domoritz** [comment]
I look forward to a PR.

**Comment by RisingGeek** [comment]
I think we can close this issue as it is completed.
