### ISSUE TITLE
Improve loading from gist

### ISSUE THREAD

**Issue by ydlamba** [vega/editor#48]
Instead of taking gist type directly from the user, we can get its type from `$schema` (or any method) then render according to it. I think we should remove gist type.
_OR_
Let's take gist type input, now if we select different type than the actual gist then it should show error on modal itself.

Looking forward to any suggestions, which one should be implemented?

**Comment by domoritz** [comment]
Loading https://vega.github.io/editor/#/gist/vega/domoritz/455e1c7872c4b38a58b90df0c3d7b1b9/3c293816596d087b12c01bed93ffc8963ccf0fc2/bar.vl.json shows a warning and then when you hit parse, we automatically use the correct type. 

I think I'd like to render the above example correctly but show a warning ("The spec specifies Vega-Lite in its $schema but the gist loader is set to Vega. We render this spec as Vega-Lite"). What do you think?

**Comment by ydlamba** [comment]
How about removing types from gist load then [https://vega.github.io/editor/#/gist/domoritz/455e1c7872c4b38a58b90df0c3d7b1b9/3c293816596d087b12c01bed93ffc8963ccf0fc2/bar.vl.json](https://vega.github.io/editor/#/gist/domoritz/455e1c7872c4b38a58b90df0c3d7b1b9/3c293816596d087b12c01bed93ffc8963ccf0fc2/bar.vl.json) will automatically use the correct type?

**Comment by domoritz** [comment]
There are specs without `$schema`. How would we support those?

**Comment by ydlamba** [comment]
We are getting spec (which have `$schema`) from the gist and `$schema` contains whether it is vega or vegamite :wink:.

**Comment by domoritz** [comment]
Let's focus on #49 instead.
