### ISSUE TITLE
Add error handling

### ISSUE THREAD

**Issue by domoritz** [vega/editor#483]
We probably don't want to ignore errors here:

https://github.com/vega/editor/blob/1b2cbcf4d48bbf6871e16787d2fe51dae3ae20b8/src/components/header/renderer.tsx#L79

While you're at it, can you replace the code with async?

**Comment by algomaster99** [comment]
@domoritz make `componentDidMount` async? There is no point since react lifecycle methods don't await for the promise to resolve or reject.

**Comment by siddhant1** [comment]
Yeah , you can make component 
didmount async ans use await inside it to await promises. After you get the value , set it inside the state

**Comment by algomaster99** [comment]
@siddhant1 What is the point if `fetch` comes with `then` function which let us do the same?

**Comment by siddhant1** [comment]
It just makes it cleaner

**Comment by RisingGeek** [comment]
@algomaster99 are you working on this issue?
