### ISSUE TITLE
Is the online editor working in vega-lite mode?

### ISSUE THREAD

**Issue by tmori3y2** [vega/editor#500]
From yesterday it seems that the online editor is not working in vega-lite mode.

The following message appears.

  Cannot access 's' before initialization

<img width="718" alt="vega-editor" src="https://user-images.githubusercontent.com/18054170/64924566-205d0c00-d821-11e9-9e1e-124c8a90c536.PNG">

This issue is occurred ...

1. When click [Try online] from offical vega-lite page.

1. When click [View this example in the online editor] from official vega-lite examples page.

1. When click [Open in Vega Editor] from official vega-lite tutorials and documentation page.

1. When click [Open in Vega Editor] from vega-lite embeded page.

1. When input something in editor after reset editor.

Vega mode is no problem.

Chrome (76.0.3809.132); Windows 10 Pro 1809 17763.720
Chrome (76.0.3809.132); Android 6.0.1

**Comment by domoritz** [comment]
I'm looking into it. I made an update yesterday and it looks like it broke the Vega-Lite mode.

**Comment by domoritz** [comment]
Very odd. It works locally even in production mode. I'll try to make another release.

**Comment by domoritz** [comment]
Works again.

**Comment by tmori3y2** [comment]
Now the editor is working in vega-ite mode.
Thank you !!
