### ISSUE TITLE
Number and overflow-y of personal-gists

### ISSUE THREAD

**Issue by mattijn** [vega/editor#501]
The access to your own gists within the vega-editor is nice! 

But:
a) It only shows a limited number of gists. Maybe default to show the first 100 available charts within a persons gist repo?
b) This `div.personal-gist` element has no overflow-y. Now when scrolling down in the overview of gists the `div.load-gist` becomes out of sight.

**Comment by algomaster99** [comment]
@mattijn 
- I am working on adding pagination to solve this problem.
- can you share a screenshot?

**Comment by mattijn** [comment]
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/5186265/65266124-b5f2e700-db12-11e9-8dbe-d63cd6ce27d6.png">
