### ISSUE TITLE
Vega 5.7.0 Dot Plot examples "View in Online Vega Editor" 

### ISSUE THREAD

**Issue by roying** [vega/editor#518]
Dot plot examples:

https://vega.github.io/vega/examples/dot-plot/
https://vega.github.io/vega/examples/quantile-dot-plot/

Need fixing ("View in Online Vega Editor"):

https://vega.github.io/editor/#/examples/vega/dot-plot
https://vega.github.io/editor/#/examples/vega/quantile-dot-plot

**Comment by domoritz** [comment]
Please wait for the next Vega-Editor release. The latest Vega version was just released last night.

**Comment by domoritz** [comment]
Ahh, unfortunately, we need to make a new Vega-Lite release with support for some of the new Vega features first. It will be a few days. Thank you for your patience.
