### ISSUE TITLE
Fix size of gist list container

### ISSUE THREAD

**Issue by domoritz** [vega/editor#520]
To make the size more consistent, let's resize the container with the list in it to take the full width and more height (look how much space is wasted in my screenshot).

<img width="1098" alt="Screen Shot 2019-09-30 at 23 47 49" src="https://user-images.githubusercontent.com/589034/65940227-d0fc0b80-e3dc-11e9-9f39-2061a81a8abb.png">

**Comment by algomaster99** [comment]
@domoritz if I increase the width, only the scrollbar moves to the left. How do you want me to show it?

**Comment by domoritz** [comment]
I think the container that has the list in it should take up the available size so that the scrollbar is further to the right.
