### ISSUE TITLE
merging the config into the spec should navigate to /edited

### ISSUE THREAD

**Issue by domoritz** [vega/editor#529]
Right now, we stay on the same page, which may be an example page.

**Comment by domoritz** [comment]
Awesome, thank you.

**Comment by siddhant1** [comment]
I tried this and shouldn't navigate to /edited , navigating to /custom/vega launches a new vega/vega-lite empty spec

**Comment by domoritz** [comment]
Sorry, my mistake. Yes, navigate to https://vega.github.io/editor/#/edited. I updated the title.
