### ISSUE TITLE
Charts are rendered twice

### ISSUE THREAD

**Issue by domoritz** [vega/editor#536]
Right now, we parse Vega-Lite specs twice every time someone hits the `run` button.

**Comment by siddhant1** [comment]
Sure!

**Comment by nik72619c** [comment]
@siddhant1 are you still working on this or shall I fix this up ?

**Comment by siddhant1** [comment]
Sure , pick it up!

**Comment by domoritz** [comment]
Thanks!

**Comment by domoritz** [comment]
@siddhant1 Are you still working on this?

**Comment by siddhant1** [comment]
@nik72619c any updates on this?

**Comment by domoritz** [comment]
It would be great not to parse the spec twice. It makes debugging with breakpoints a bit annoying to use.

**Comment by ashu8912** [comment]
Hey, @domoritz I am not able to reproduce this issue is this fixed??

**Comment by domoritz** [comment]
No, we are still parsing the Vega spec twice. You can check by adding a logging statement in the code. Do you want me to show you where?

**Comment by ashu8912** [comment]
Yes @domoritz that will help.

**Comment by domoritz** [comment]
```patch
diff --git a/src/components/renderer/renderer.tsx b/src/components/renderer/renderer.tsx
index 8d1dee01..85615138 100644
--- a/src/components/renderer/renderer.tsx
+++ b/src/components/renderer/renderer.tsx
@@ -125,6 +125,7 @@ class Editor extends React.PureComponent<Props, State> {

  // Initialize the view instance
  public initView() {
    console.log('init view');
    let runtime: vega.Runtime;
    if (this.props.mode === Mode.VegaLite) {
      // In vl mode, we compile Vega-Lite spec along with config to Vega spec
```

<img width="665" alt="Screen Shot 2020-02-13 at 10 57 02" src="https://user-images.githubusercontent.com/589034/74468400-9f498580-4e4f-11ea-938c-61b3699febab.png">

Notice how we create the chart twice when we only need to do it once. I would love for this to be fixed.

**Comment by domoritz** [comment]
Looks like the second bug is gone so I updated the issue.

**Comment by ashu8912** [comment]
Hey, @domoritz I couldn't get this line 'No, we are still parsing the Vega spec twice'.
I added a console log for vega editor and it was working fine where is the problem can you explain more.

**Comment by domoritz** [comment]
When you add the console.log statement, you notice that it's called twice (see command line output). We should only render once (for performance reasons).

**Comment by ashu8912** [comment]
The console.log is shown on multiple clicks of Run I think this is a desired behaviour coz At first it is called on mount of component and than each time an update occurs(if props change and run is clicked)
Are You talking about the switch from vega-lite to vega console output?

**Comment by domoritz** [comment]
Very odd. I am 100% sure that this was an issue but now I only see that we are compiling Vega-Lite twice.

<img width="964" alt="Screen Shot 2020-02-16 at 14 00 36" src="https://user-images.githubusercontent.com/589034/74613608-c066dc00-50c4-11ea-8dbc-e31c85701e73.png">

```diff
diff --git a/src/components/renderer/renderer.tsx b/src/components/renderer/renderer.tsx
index 8d1dee01..c9af9b63 100644
--- a/src/components/renderer/renderer.tsx
+++ b/src/components/renderer/renderer.tsx
@@ -126,6 +126,7 @@ class Editor extends React.PureComponent<Props, State> {
  // Initialize the view instance
  public initView() {
    let runtime: vega.Runtime;
    console.log('parse vega');
    if (this.props.mode === Mode.VegaLite) {
      // In vl mode, we compile Vega-Lite spec along with config to Vega spec
      runtime = vega.parse(this.props.vegaSpec);
diff --git a/src/reducers/index.ts b/src/reducers/index.ts
index 715cffe8..ae288062 100644
--- a/src/reducers/index.ts
+++ b/src/reducers/index.ts
@@ -217,6 +217,7 @@ function parseVegaLite(
    };
    validateVegaLite(vegaLiteSpec, currLogger);

    console.log('compile vl');
    const vegaSpec = spec !== '{}' ? vegaLite.compile(vegaLiteSpec, options).spec : {};

    extend = {
```

**Comment by ashu8912** [comment]
I am able to reproduce this for vega-lite parsing will soon send a pr that will fix this.

**Comment by adrijshikhar** [comment]
@ashu8912 are you still working on this?
If not, then i would like to work on this one. Thanks.

**Comment by ashu8912** [comment]
@adrijshikhar go ahead

**Comment by adrijshikhar** [comment]
I went through the flow and I found that when i click run button this 
```javascript
  onClick={() => {
          this.props.parseSpec(true);
        }}
```
is called and set parse to `true`. Then in spec-editor , this

```javascript
if (this.props.parse) {
      this.editor.focus();
      this.editor.layout();
      this.updateSpec(this.props.value);
      prevProps.setConfig(this.props.configEditorString);
      prevProps.parseSpec(false);
    }
``` 
get executed, which calls `updateSpec` which rendered the config in the editor and generates the output and calls `parseVega` or `parseVegaLite` on the basis of spec
```javascript
 public updateSpec(spec: string) {
    let parsedMode = this.props.mode;
    try {
      const schema = JSON.parse(spec).$schema;

      if (schema) {
        switch (parser(schema).library) {
          case 'vega-lite':
            parsedMode = Mode.VegaLite;
            break;
          case 'vega':
            parsedMode = Mode.Vega;
            break;
        }
      }
    } catch (err) {
      console.warn('Error parsing JSON string', err);
    }

    switch (parsedMode) {
      case Mode.Vega:
        this.props.updateVegaSpec(spec);
        break;
      case Mode.VegaLite:
        this.props.updateVegaLiteSpec(spec);
        break;
      default:
        console.exception(`Unknown mode:  ${parsedMode}`);
        break;
    }
  }
```
`setConfig` on the other hand calls this
```javascript
export function setConfig(value: string) {
  return {
    configEditorString: value,
    type: SET_CONFIG,
  };
```
which in turns does this in the reducer
```javascript
 case SET_CONFIG:
      return state.mode === Mode.VegaLite
        ? parseVegaLite(state, action, {
            configEditorString: action.configEditorString,
          })
        : parseConfig(state, action);
```
Here `parseVegaLite` is called again and thats why charts get rendered twice in vega-lite.
@domoritz please verify and let me know what changes are to be made. Thanks

**Comment by domoritz** [comment]
Yes, you found the issue. I haven't had the time to think of a solution yet. Can you come up with one and send a pull request?

**Comment by adrijshikhar** [comment]
I just wanna know why another condition is specified for vega-lite in this
```javascript
 case SET_CONFIG:
      return state.mode === Mode.VegaLite
        ? parseVegaLite(state, action, {
            configEditorString: action.configEditorString,
          })
        : parseConfig(state, action);
```
Any suggestions or discussion is welcome. Till than I will try to fix it on my own.

**Comment by domoritz** [comment]
I think it’s because Vega-Lite needs to be recompiled when the config changes. You can try by removing the condition.

**Comment by adrijshikhar** [comment]
ok
