### ISSUE TITLE
Config theme is merged into spec when vega-lite spec is compiled into vega

### ISSUE THREAD

**Issue by tmori3y2** [vega/editor#538]
- Open vega-lite example in the online editor.
- Select config theme.
- Select [Compiled Vega] and [Edit Vega Spec]

The config theme is merged into spec and config theme is cleared.

Is it correct?

- Vega-lite's original config is overwritten
- Even if you choose another theme in vega, it is easy to conflict with merged theme (especially color theme)

I think it's better not to merge automatically.

**Comment by domoritz** [comment]
We need to do this because the theme has some Vega-Lite specifics that have to be compiled into the spec. This may change in the future but right now this is the expected behavior.

**Comment by tmori3y2** [comment]
I understand. Thank you.
