### ISSUE TITLE
I get logged out after short time

### ISSUE THREAD

**Issue by domoritz** [vega/editor#545]
I wish I would stay logged in for a few days at least.

**Comment by siddhant1** [comment]
@shakti97 @aloksingh3112 would you like to check this out?
The backend repo is https://github.com/vega/editor-backend

**Comment by shakti97** [comment]
working on this

**Comment by algomaster99** [comment]
This is because we don't have a backing store for session storage. We completely rely on server's memory. Now when I started the server on localhost, it worked fine. So I think this is a problem with Now. Its memory would keep refreshing from time to time which clears all session stored.
To solve this problem permanently,  we might need a session-storage db like redis.

**Comment by algomaster99** [comment]
@shakti97 I had this discussion with @domoritz initially. He said he wants to keep minimal services so I never implemented one. But if @domoritz agrees, I can help you with this issue. :smile:

**Comment by algomaster99** [comment]
@shakti97 But you may debug this issue first. You can set a cookie for, let's say 5min,  on the development server and check if it expires exactly after five minute. I think it will. For checking on production, you may deploy the fork of https://github.com/vega/editor-backend to now and check after how long it expires.

**Comment by domoritz** [comment]
I now agree that we need a session store. Thank you!

**Comment by algomaster99** [comment]
@domoritz I have asked it here too - https://spectrum.chat/zeit/now/now-server-memory-management~1a9ea7c9-bd8d-4e5f-9863-e8847a497345

**Comment by algomaster99** [comment]
@domoritz They have answered it. They suggest to setup a store. We may use `redis` because it's the most popular :sweat_smile: 
We can, although, have a discussion over it.
Also, which version do you use for deployments? Please answer them in chats.

**Comment by domoritz** [comment]
Redis sounds good. 

Where do you want me to reply?

**Comment by algomaster99** [comment]
@domoritz oh I replied to it. 😅
@shakti97 do you want to work on this?

**Comment by shakti97** [comment]
if you are working go ahead, i have some opened PR i need to complete them before working on this
