### ISSUE TITLE
New example from Vega 5.9 not appearing in editor

### ISSUE THREAD

**Issue by mattijn** [vega/editor#559]
This example from the documentation:
https://vega.github.io/vega/examples/annual-precipitation/

Is not loading in the editor (neither in Chrome nor Safari)
https://vega.github.io/editor/#/examples/vega/annual-precipitation
<img width="549" alt="image" src="https://user-images.githubusercontent.com/5186265/70392910-c49bbc80-19e4-11ea-8c84-6c8686396c90.png">

It refers to unavailable data sources here:
https://vega.github.io/data/annual-precip.json and https://vega.github.io/data/world-110m.json. Adding a vega before the /data work make the file loads, but chart is still not appearing.

I see an error in the console window: `ERROR TypeError: t is not a function. (In 't()', 't' is undefined)` referring to this line https://github.com/vega/vega/blob/master/packages/vega-projection/src/projections.js#L57. Not sure if that is related.

**Comment by domoritz** [comment]
The editor uses different base URLs to work even if a dataset if not available in the Vega datasets. This is why you get the 404s. The problem is somewhere else. I'm not sure yet but it could be something with the bundle. Maybe a rebuild with refactored dependencies will fix it.

**Comment by domoritz** [comment]
It didn't fix it. I'm not sure what's going wrong. Can you help debug this issue?

**Comment by mattijn** [comment]
Must be something in the editor as it works ok in an observable notebook: https://observablehq.com/@mattijn/geo-contour-test

**Comment by mattijn** [comment]
I vaguely remembered that in v5.9 also some stuff happened surround projection `naturalEarth1`and `mollweide`:

> vega-projection

> 
> Add mollweide projection to default set.
> Update dependencies.
> vega-projection-extended
> 
> Add hyperElliptical, interruptedQuarticAuthalic, nicolosi projections.
> Drop naturalEarth1, mollweide projections (move to vega-projection defaults).

And indeed, changing the default projection to something as `mercator` fix it in the editor.
![B7089392-E550-4802-A938-6C1340BF1DB8](https://user-images.githubusercontent.com/5186265/70751760-6e56b280-1d31-11ea-8d9a-d2fcd74c2d4c.png)

I hope it isolates the issue
Conclusion: take more showers.

**Comment by domoritz** [comment]
Does it work in the notebook without extended projections? Maybe they are missing.

**Comment by mattijn** [comment]
Got it. I can reproduce the behaviour from the editor in the [notebook](https://observablehq.com/@mattijn/geo-contour-test). It's because the `naturalEarth1` projection is loaded twice and then causing conflicts. Once part of the Vega-projections and once in the extended projections. Removing them from the extended-projections list solves the issue. 

PR incoming

**Comment by domoritz** [comment]
Thanks for the fix. I updated all projections and made a release. It should work in a few minutes.
