### ISSUE TITLE
Editor UI

### ISSUE THREAD

**Issue by domoritz** [vega/editor#57]
We could improve the UI based on some inspiration from https://webassembly.studio/. 

Made in https://app.moqups.com/yashdev18@gmail.com/lkfmF6icEv/edit/page/aa1276c8b

<img width="1240" alt="screen shot 2018-05-19 at 11 53 41" src="https://user-images.githubusercontent.com/589034/40272029-5bf19a22-5b5b-11e8-947f-33d92ad85a58.png">

**Comment by siddhant1** [comment]
@domoritz anything more the needs to be changed?

**Comment by domoritz** [comment]
We're getting there. There are still some features we don't have so let's keep this open. Also, this is just an idea and not exactly how we might do things.
