### ISSUE TITLE
A few thumbnails are broken / missing in the examples

### ISSUE THREAD

**Issue by donghaoren** [vega/editor#571]
**Vega:**

- [ ] Projections
- [x] Annual Precipitation

**Vega-Lite:**

- [x] Stacked Bar Chart with Corner Radius
- [ ] Isotype Dot Plot with Emoji
- [x] Faceted Density Plot
- [x] Interactive Legend
- [x] Multi Series Line Chart with Tooltip

**Comment by domoritz** [comment]
I fixed all of them except projections, which is trickier because vg2png does not use extended projections.

**Comment by domoritz** [comment]
We are now generating images my hand instead of Travis so this should be fixed when I build images locally.
