### ISSUE TITLE
Support themes

### ISSUE THREAD

**Issue by domoritz** [vega/editor#58]
https://github.com/vega/vega-themes

**Comment by ydlamba** [comment]
Working on this. I think adding a drop-down option in the toolbar (or anywhere in the chart area) will work.

**Comment by siddhant1** [comment]
Looking into this , @domoritz , @kanitw any UI designed for this?

**Comment by domoritz** [comment]
Not yet. I think we should have a place where we can configure the renderer, tooltips, and themes. Maybe a settings panel.

**Comment by RandomFractals** [comment]
you guys can see how Vega Viewer does it here :) https://twitter.com/TarasNovak/status/1113069510112788480

![vega-viewer-4 2](https://user-images.githubusercontent.com/656833/55820623-2526d280-5ac1-11e9-90bc-de1179f7a73f.png)

cheers!

**Comment by siddhant1** [comment]
Will have a look at it !

**Comment by domoritz** [comment]
Done
