### ISSUE TITLE
Button style collision

### ISSUE THREAD

**Issue by domoritz** [vega/editor#592]
Notice how the button style is incorrect because we apply our own `button` style rather than using the default style from monaco. 

<img width="689" alt="Screen Shot 2020-01-26 at 20 43 07" src="https://user-images.githubusercontent.com/589034/73150740-a2392d80-407c-11ea-9133-b5f9da0b192e.png">

**Comment by IamRavikantSingh** [comment]
I think this issue should be closed now! @domoritz
