### ISSUE TITLE
Docs integration in the Vega editor

### ISSUE THREAD

**Issue by mattijn** [vega/editor#60]
It would be nice to have a searchable tree-structure of the documentation within the Vega editior. 

Sometimes wish to have detailed information next to the spec while playing around.

**Comment by mattijn** [comment]
Something like the docs integration within the editor of code.earthengine.google.com
![91c3f690-9f19-46dd-a1a6-9ce48007e778](https://user-images.githubusercontent.com/5186265/39086248-12505dea-458f-11e8-8822-8a4d24f5b30f.png)

**Comment by kanitw** [comment]
This would be useful, but is beyond the scope of Vega-Editor.   We definitely don't have enough resource to implement this.   So I'll close this for now. 

That said, if you or anyone else would like to contribute, feel free to draft a design proposal and we can collaborate on this.  

I think another alternative that's equally useful but require less work would be creating a Vega and Vega-Lite documentation package for [dash](https://kapeli.com/dash), [zeal](https://zealdocs.org/), and http://devdocs.io/.

**Comment by domoritz** [comment]
The schema has comments, which are automatically shown in autocomplete. I think that's the extent to which we can provide docs. Note that this only works for Vega-Lite right now.

**Comment by algomaster99** [comment]
@domoritz I can try implementing it for vega too

**Comment by domoritz** [comment]
How do you propose to do that?
