### ISSUE TITLE
Config Editor Transferring Focus To Vega Editor

### ISSUE THREAD

**Issue by ashu8912** [vega/editor#602]
Steps To Reproduce This Bug
1.Change Something In the config.
2.Press Run 
3.Now Start Changing then Config again 
4.Anything you type now is typed in the vega editor and not in the config editor (The Config Editor has Lost Focus somehow and transferred to vega editor).

**Comment by domoritz** [comment]
Thanks for the bug report. Can you send a fix?

**Comment by ashu8912** [comment]
Yes @domoritz Will Send a pr that fixes this
