### ISSUE TITLE
Typo In Share Modal

### ISSUE THREAD

**Issue by ashu8912** [vega/editor#607]
<img width="583" alt="Screenshot 2020-02-17 at 3 14 43 AM" src="https://user-images.githubusercontent.com/30126128/74613376-d790e280-5133-11ea-9404-bacb0551ef37.png">

**Comment by domoritz** [comment]
Ahh. Good catch. Do you want to send a pull request to fix it?

**Comment by ashu8912** [comment]
@domoritz done
