### ISSUE TITLE
Providing tooltip for heading text looks redundant

### ISSUE THREAD

**Issue by shakti2379** [vega/editor#609]
![Screenshot from 2020-02-18 01-30-35](https://user-images.githubusercontent.com/59553591/74683519-38312580-51ef-11ea-914d-26d8febf19fb.png)

**Comment by shakti2379** [comment]
if this issue looks fine, would like to work on it:)

**Comment by domoritz** [comment]
Is the tooltip needed when there are a lot of columns? Otherwise we can remove the tooltip.

**Comment by ashu8912** [comment]
Yes, @domoritz tooltips are generally applied to icons or buttons and not to obvious texts, Removing The Tooltip, in this case, would be a good idea as the table headers already depict what they are for adding a tooltip that just conveys the same information doesn't make sense.

**Comment by ashu8912** [comment]
Here is a brief article that describes when and where to use tooltips.
https://www.nngroup.com/articles/tooltip-guidelines/

**Comment by shakti2379** [comment]
@ashu8912 if someone asked to work on any issue before you , i think its professional to let him work on it may be he also wanted to get into the project, that's the basic thing in contributing to oss.

**Comment by ashu8912** [comment]
Aah Sorry @shakti2379  Didn't notice that you were working on it As This was a minor fix i quickly jumped on it to fix.
Will take care of this next time. :)
