### ISSUE TITLE
This error screen makes Vega Editor unusable

### ISSUE THREAD

**Issue by kanitw** [vega/editor#61]
It appears whenever there is an error in the console, which sounds like a good idea.

But this means it disrupt my typing flow all the time!  (When I'm typing a spec, esp. expression, it would lead to console error all the time.) 

![image](https://user-images.githubusercontent.com/111269/39089312-f8a7036e-4578-11e8-9ace-56157b024b33.png)

**Comment by domoritz** [comment]
Does this happen in the deployed editor as well? I thought I added error boundaries to prevent errors from causing the whole page to crash.

**Comment by kanitw** [comment]
Not the deployed editor, but I need local editor to debug development version of VL

**Comment by ydlamba** [comment]
Is this still an issue? It might get fixed. Can anyone confirm this, please?

**Comment by domoritz** [comment]
Closing as this seems to be fixed.
