### ISSUE TITLE
should open to new tab

### ISSUE THREAD

**Issue by shakti97** [vega/editor#611]
clicking on vega view open the link on the same tab, i think it should open the link in another tab so that one should not have to leave vega app 
![Screenshot from 2020-02-18 10-08-10](https://user-images.githubusercontent.com/30585570/74704573-e1e7d500-5236-11ea-9e4e-ea35f6bb0fcd.png)

There are other links also like hover link in this image
![Screenshot from 2020-02-18 10-11-47](https://user-images.githubusercontent.com/30585570/74704688-528ef180-5237-11ea-8418-95958da5e6c5.png)

**Comment by shakti97** [comment]
if possible would like to work on it @domoritz

**Comment by siddhant1** [comment]
Thanks for reporting @shakti97 , you can go on and fix this

**Comment by domoritz** [comment]
Hmm, you can CMD+click on any link to open them in a new tab but as far as I know there is no way to do the reverse. I’m not yet convinced we want this change.

**Comment by siddhant1** [comment]
The other links do open in new tab , we should keep it consistent though

**Comment by domoritz** [comment]
Ahh, yes, we should. Let’s open them all in new tabs or the same tab then. I can go either way.

**Comment by ashu8912** [comment]
@domoritz  I would recommend opening every link in the same tab 
Here are the reasons why
1.If a user prefers that links open in a new tab, they can open the link in a new tab using a right-click or by continuing to press down on the link on a mobile device. This option is always available to users no matter how a link is set to open.
However, it doesn’t work in reverse.As you also mentioned.
2.The only time it is recommended that you open a link in a new tab is when opening in the same screen would interrupt a process (which in our case isn't the case or is it????)
3.From the usability point of view the decision to enforce opening links in new windows violates one of the fundamental principles of the user interface design: users should always be in control of the interface they are interacting with.
The above are the reasons why i think they should open in the same tab If any other suggestion or other outcomes of opening in same tab are there they are most welcomed for discussions.
Also as @siddhant1 mentioned there should be consistency all around(meaning it should not be as if one link opens in the same tab and other open in other tabs coz this leads users to a surprise to links clicking).

**Comment by shakti97** [comment]
When you open external links in the same tab, you create back-button fatigue for users. Every time the user goes to an external website they have to hit the back button to go back to your app. If they decide to click the links on the external page/website, they have to hit the back button even more times to get back to your site. This is a lot of unnecessary work for users. So I think it should be open in a new tab.

**Comment by ashu8912** [comment]
But a user can always open in new tab by right clicking on the link.But The other is not true.

**Comment by ashu8912** [comment]
@domoritz whats your thought on this

**Comment by domoritz** [comment]
I see both of your points. One issue is that we mostly preserve state even if you leave the editor page but there are some cases where we don’t preserve state. 

So let’s open all links in a new tab. 

Thanks for raising all these points in the discussion.
