### ISSUE TITLE
Weird spacing in firefox

### ISSUE THREAD

**Issue by domoritz** [vega/editor#62]
<img width="307" alt="screen shot 2018-04-25 at 22 54 16" src="https://user-images.githubusercontent.com/589034/39283301-a526d384-48db-11e8-81de-b41dff2e05d1.png">

**Comment by ydlamba** [comment]
I don't see anything weird in this. Can you mark the region which you are pointing to?

**Comment by domoritz** [comment]
See the white line below the purple line?

**Comment by ydlamba** [comment]
I can see this in chrome too. Well, I am removing this white line for now. Anyways this will be changed with new UI.
