### ISSUE TITLE
Monaco tooltips should be in foreground. 

### ISSUE THREAD

**Issue by domoritz** [vega/editor#620]
This is a regression coming from a recent refactor I did. 

<img width="423" alt="Screen Shot 2020-02-19 at 10 04 45" src="https://user-images.githubusercontent.com/589034/74861536-5dad5480-52ff-11ea-9810-8a8a4efd6e78.png">

**Comment by adrijshikhar** [comment]
@danmarshall can i fix this?

**Comment by adrijshikhar** [comment]
@domoritz can i fix this?

**Comment by domoritz** [comment]
Sure
