### ISSUE TITLE
Number of dispalyed Gist files

### ISSUE THREAD

**Issue by keckelt** [vega/editor#624]
I started to collect my Vega-Lite specs in [a Gist](https://gist.github.com/keckelt/83f0fdce4fcd5b758ba16e8570f76d92) and noticed that not all are displayed in the Vega Editor (9 out of 16)

I found the relevant part in the editor's backend code:
https://github.com/vega/editor-backend/blob/master/src/controllers/gist.ts#L61

And the part in the editor's code that handles pages: 
https://github.com/vega/editor/blob/master/src/components/header/gist-modal/renderer.tsx#L320

But I don't think that a Gist's files are paginated, so probably the graphql query only retrieves the first 9 files?

I'm not familiar with graphql and didn't find out which API Endpoint it uses to fetch the data to look into it myself.

**Comment by domoritz** [comment]
Odd. There is supposed to be pagination.

**Comment by keckelt** [comment]
Is it missing on my end or in general?

**Comment by domoritz** [comment]
Here is my page

<img width="408" alt="Screen Shot 2020-02-21 at 09 07 21" src="https://user-images.githubusercontent.com/589034/75055288-9711cb80-5489-11ea-9a3b-89b6f3978090.png">

**Comment by keckelt** [comment]
Both without any addons:

# Firefox Developer 74
![image](https://user-images.githubusercontent.com/10337788/75135454-d5092c80-56e1-11ea-92ea-6d8e95129511.png)


# Chrome 80
![image](https://user-images.githubusercontent.com/10337788/75135414-c02c9900-56e1-11ea-8c90-930968f58b99.png)

**Comment by domoritz** [comment]
Is there any difference between the browsers? 

Am I correct that the issue is that not all files inside a gist are shown?

**Comment by keckelt** [comment]
> Is there any difference between the browsers?

No, just tested with both to catch any browser specific errors

> Am I correct that the issue is that not all files inside a gist are shown?

yes

**Comment by domoritz** [comment]
I see. Yes, that’s an enhancement someone should implement.

**Comment by algomaster99** [comment]
@domoritz https://developer.github.com/v4/object/gist/#fields I think `limit` will fix it. What do you think its value should be?

**Comment by domoritz** [comment]
Let's make it 1000 and hope that it's enough for now. Do we make the list scrollable when there are many many files in a gist?

**Comment by algomaster99** [comment]
@domoritz yeah, i think it should be scrollable ideally

**Comment by domoritz** [comment]
Cool, can you set the limit to 1000 and make sure that the UI doesn't break when we have many files in a gist?

**Comment by domoritz** [comment]
@algomaster99 I don't know graphql. Do we just add a parameter to https://github.com/vega/editor-backend/blob/master/src/controllers/gist.ts#L66? Can you send a pull request?

**Comment by algomaster99** [comment]
@domoritz yeah it migh be possible to do so using limit under this [heading](https://developer.github.com/v4/object/gist/#fields). But increasing that to 1000 might require to add a pagination inside it too. Should we add a nested pagination?

**Comment by domoritz** [comment]
What if we just increase the limit to 100 and only show the top 10 but let people expand the rest in the ui by clicking on “view more...”.

**Comment by algomaster99** [comment]
Any idea where can show all the 100 files? Do you recommend a scrollable div? I think we can add a search bar to search over so many files.

**Comment by domoritz** [comment]
Just show them and make the whole list of all gists scrollable. I think if the files don’t take up too much vertical space, it’s fine.

**Comment by domoritz** [comment]
@algomaster99 do you plan to finish this issue?

**Comment by ashu8912** [comment]
![vega-editor-gist-list-view](https://user-images.githubusercontent.com/30126128/95018160-7e060580-067b-11eb-9032-9aeda47214f4.gif)

**Comment by ashu8912** [comment]
@domoritz i changed the limit at the backend from default 10 to 100 and it seems to work fine now, I wanted to discuss about the UI as you see by default we get a scroller on the gist with multiple files should i reduce the height of each gist file list view so that it don't try to cover the remaining entire height of the model view?

**Comment by ashu8912** [comment]
also a thing about limit the max no of files we can fetch per gist is limited to 300

**Comment by domoritz** [comment]
>  I wanted to discuss about the UI as you see by default we get a scroller on the gist with multiple files should i reduce the height of each gist file list view so that it don't try to cover the remaining entire height of the model view?

I'm not following. I want a single scrollbar for the entire list of gists and files. What are you proposing? 

> also a note about the limit of gist files => the max no of files we can fetch per gist is limited to 300

Let's set out limit to 300 as well then instead of 100.

**Comment by ashu8912** [comment]
@domoritz  if you want the single scroller than i think we don't need any changes at the frontend as its already adding that scrollbar, I was in an impression from the previous conversation that we can either add a view more for overflowing gist files list

**Comment by domoritz** [comment]
Let's go with the simplest solution.
