### ISSUE TITLE
Add shortcut for opening examples

### ISSUE THREAD

**Issue by nik72619c** [vega/editor#626]
@domoritz please let me know if I should go forward with this :)

**Comment by domoritz** [comment]
WHat does this mean?

**Comment by nik72619c** [comment]
@domoritz Currently there is no keyboard shortcut mentioned in the help section regarding opening the shortcut modal via some keystrokes.

**Comment by domoritz** [comment]
Sure. That sounds like a good addition.

**Comment by nik72619c** [comment]
Cool,  sending a PR for it soon .

**Comment by nik72619c** [comment]
@domoritz , I guess this code needs a refactor. Currently the `keydown` event listener is attached for adding the shortcut for the help modal. Now, if I want to write my logic on the keydown event for opening the Examples modal it cant be done since there has to be only one keydown listener.

**Comment by nik72619c** [comment]
Please let me know how shall I approach this ?

**Comment by domoritz** [comment]
Feel free to rename the function and support more than just the help modal.

**Comment by nik72619c** [comment]
okay

**Comment by nik72619c** [comment]
ref #636

**Comment by ashu8912** [comment]
@domoritz what's the status of this do we need it or not?

**Comment by domoritz** [comment]
I don't think it's the most pressing issue. I would rather enhance the features that we have and clean up the code (e.g. remove deprecated code, use react hooks, etc).
