### ISSUE TITLE
Typo issue in reset

### ISSUE THREAD

**Issue by shakti97** [vega/editor#627]
![Screenshot from 2020-02-23 03-05-00](https://user-images.githubusercontent.com/30585570/75099618-a871e980-55e9-11ea-8e06-7855343d3577.png)

## stuck instead of struck

**Comment by shakti97** [comment]
@domoritz , if possible can i work on this?

**Comment by domoritz** [comment]
Thanks. Feel free to just send prs for small issues like this.
