### ISSUE TITLE
Include Vega-Lite normalized spec output (in addition to Vega spec)

### ISSUE THREAD

**Issue by kanitw** [vega/editor#63]

**Comment by domoritz** [comment]
How do you imagine this? With a third panel, tabs, or some button?

**Comment by kanitw** [comment]
Probably a tab in the bottom panel.  (Three panels would be too much and we probably don't want to see full VL specs together with VG spec anyway.)

**Comment by domoritz** [comment]
We will look at this with @ydlamba

**Comment by ydlamba** [comment]
Yeah! We will start the work very soon.

**Comment by siddhant1** [comment]
@domoritz I don't think this needs any work for now

**Comment by domoritz** [comment]
Why not?

**Comment by siddhant1** [comment]
Oops mixed that with compiled Vega output , any particular UI you have in mind?

**Comment by domoritz** [comment]
Not yet.

**Comment by kanitw** [comment]
I think the Compiled Vega can be a dropdown for "Expanded Vega-Lite Spec"
and the button can become "Edit Expanded Vega-Lite Spec"

![image](https://user-images.githubusercontent.com/111269/55030001-9eee9480-4fc8-11e9-98c5-800b0cafb821.png)
