### ISSUE TITLE
Incorrect key stroke written for opening the help modal

### ISSUE THREAD

**Issue by nik72619c** [vega/editor#637]
#### Description of the bug
Inside the help modal which provides a list fo shortcuts cheat sheet, the shortcut for the help modal is written as `Ctrl+?` which does not seem to work. The correct keybinding for it is `Ctrl+Shift+/` as specified in the code.

**Comment by nik72619c** [comment]
@domoritz Let me know if I shall file a PR for this :)

**Comment by domoritz** [comment]
Can you link to the relevant code? I think we should implement the right shortcut.

**Comment by domoritz** [comment]
Needs more details.
