### ISSUE TITLE
Hint users about what they can do in console

### ISSUE THREAD

**Issue by kanitw** [vega/editor#66]
Currently, most users won't know how to use the console to debug unless they read https://vega.github.io/vega/docs/api/debugging/. 

Providing some affordance that this documentation exists is probably helpful.

**Comment by domoritz** [comment]
If you open the console, you see some hints. But I agree that we should point to some better debugging guide.

**Comment by domoritz** [comment]
Here is a screenshot:

<img width="625" alt="screen shot 2018-05-08 at 15 07 26" src="https://user-images.githubusercontent.com/589034/39785587-8fe59172-52d1-11e8-975b-60a20f99a114.png">

**Comment by kanitw** [comment]
Yes, but hint them that they can open console.

**Comment by domoritz** [comment]
Let's instead build a data viewer that is more user friendly.

**Comment by kanitw** [comment]
Vega VIEW isn't just for looking at data though.  

I think this hint would take <30mins to implement once we have a good design.

**Comment by domoritz** [comment]
Do you have a concrete suggestion? I'm not sure where to put this. I think we will add some more guidance to the editor over the summer. Maybe that would be a place to add this. I don't see a good place in the current editor.

**Comment by kanitw** [comment]
It could be as dumb as tips button and a modal.

**Comment by siddhant1** [comment]
@domoritz Since I was working on help and feedback modal in my latest patch , should I include a tips section which tells this or should we make a new separate modal which runs on startup and shows tips?
Just like eclipse does

**Comment by domoritz** [comment]
Yes!

**Comment by domoritz** [comment]
No startup modal.

**Comment by siddhant1** [comment]
Which one do you prefer?

**Comment by siddhant1** [comment]
Should I add it in #260 ?

**Comment by domoritz** [comment]
Just add it to the Modal we just added.

**Comment by siddhant1** [comment]
Sure

**Comment by siddhant1** [comment]
I think we can close this now
