### ISSUE TITLE
Cannot find module './package.json'.

### ISSUE THREAD

**Issue by kanitw** [vega/editor#67]
![image](https://user-images.githubusercontent.com/111269/39789681-35e8439e-52e6-11e8-9d20-9d23113bc45e.png)

[at-loader] ./node_modules/vega-lite/build/src/index.d.ts:26:25
    TS2307: Cannot find module './package.json'.

**Comment by domoritz** [comment]
Do you use linked vl?

**Comment by kanitw** [comment]
Yes

**Comment by kanitw** [comment]
(Why would I use local editor if I don't link VL)

**Comment by domoritz** [comment]
Run `yarn build:only`

**Comment by kanitw** [comment]
I have tried both `yarn build` and `yarn build:only` -- none of them helps.

**Comment by domoritz** [comment]
@arfulgarfunk add the json.d.ts from the Vega-Lite repo to your typings. I think TS 2.9 addresses this as well.

**Comment by artfulgarfunk** [comment]
Still getting the same error, with typescript updated...

I added the following line to my tsconfig.json which means no errors but the app doesn't load at all...
"include": ["node_modules/vega-lite/typings/*.d.ts"]

**Comment by domoritz** [comment]
What versions (git Sha) of Vega-Lite and the editor are you using?

**Comment by artfulgarfunk** [comment]
Vega-lite 2.5.2 & VSCode
That what you mean? :)

**Comment by artfulgarfunk** [comment]
Moved issue to appropriate area:
[3897](https://github.com/vega/vega-lite/issues/3897)
I was just posting here because it's the same error, however I'm not using the editor.

**Comment by domoritz** [comment]
Oh okay, I got super confused because the editor works fine for everyone in our lab. I'll respond to the other issue.
