### ISSUE TITLE
Mouse select doesn't work properly in Xorg

### ISSUE THREAD

**Issue by morehockeystats** [vega/editor#684]
If you select text in Vega Editor, either by dragging the mouse, or by double-clicking, and then click the middle mouse button, it would not paste the selection. It would paste the buffer selected before interaction with the editor instead - the one that was supposed to be overwritten.

Even when you right-click to "Copy" the selection, the middle-button paste still does not work.

This contradicts the normal behavior under Xorg/X11 window system.

Ubuntu 18.04.4 / Linux 4.15.0-88 / Xorg 7.7 / xdm 1.1.11 / AfterStep 2.2.12 / Firefox 75.0.

**Comment by domoritz** [comment]
Can you reproduce the issue here: https://microsoft.github.io/monaco-editor/playground.html?

**Comment by morehockeystats** [comment]
yes, I guess this is the bug. Microsoft product having a bug in X-windows...

**Comment by domoritz** [comment]
Please file an issue with Monaco then.
