### ISSUE TITLE
swap filename and filedescription in gist loading tree

### ISSUE THREAD

**Issue by mattijn** [vega/editor#692]
I've a small UI comment. When I'm working with vega(-lite) specs (and any other file on PC), I distinct them based on filenames and not on file descriptions. So once loaded in the vega editor, my gist specs looks like this:
![image](https://user-images.githubusercontent.com/5186265/81264314-79dcaa00-9041-11ea-91dc-c1e2cd20709c.png)
Almost none of them have a description, but all have a filename. Maybe I'm opposing design criteria, but would it be possible to swap this? So in bold, the filename and as child node (when provided) the spec description?

**Comment by algomaster99** [comment]
@mattijn hi! So a GitHub gist is a collection of multiple files but it has a common title. You are suggesting to swap the title and the filename but this will disturb the flow a little bit. Let me explain this briefly.

Suppose we load a gist and it has multiple JSON files. Which one are we supposed to chose for the title? In your case, there is only one so it makes sense but with multiple gist, I think the flow is unclear. One workaround for this could be to simply list all vega/vl files we find in all gist but that can make the file selector widget to large.

**Comment by mattijn** [comment]
Ah I see, thanks for teaching me how gists works:). 

I've never added multipe vega-specs to a single gist, but I just tried. If I copy the URL of a gist with multiple specs and parse it in the editor-load-gist dialog only the first spec is loaded. So there is already some selection happening in the editor.

If its a common routine for other gists to have multiple specs in one gist than current approach is OK.

**Comment by algomaster99** [comment]
@mattijn if you want to load some other file, please specify its filename.

**Comment by domoritz** [comment]
We can improve the highlighting to put more emphasis on the files. Wanna send a pull request @mattijn?

**Comment by algomaster99** [comment]
@domoritz I think #691 (https://github.com/vega/editor/commit/8ec9777996a0879325f2753cc030f1d919dabe88) resolves this.

**Comment by domoritz** [comment]
I'm taking care of it in my redesign.
