### ISSUE TITLE
Vega Editor’s data viewer not handling `DateTime` objects properly

### ISSUE THREAD

**Issue by yifanwu** [vega/editor#718]
In a spec described in this SO question: https://stackoverflow.com/questions/62351436/using-triggers-to-store-interaction-history-but-seeing-null-values, the data `selected` is not showing properly in the `Data Viewer` pannel. However, the data is recorded properly---verified via console access `VEGA_DEBUG.view.data('selected')`.

Thanks!

**Comment by domoritz** [comment]
Related to https://github.com/vega/editor/issues/716.

**Comment by domoritz** [comment]
Ahh, so you are creating a dataset that doesn't contain tuples but data directly. I don't think we thought of this use case before.

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/editor/pull/731
