### ISSUE TITLE
Vega editor showing multiple erros while it works on web

### ISSUE THREAD

**Issue by danielp3011** [vega/editor#736]
I got a vega spec running on a web page without any problems. However since some time I cannot edit the vega spec in vega editor anymore. When I enter the vega spec into editor, it gives the error "[Error] Cannot read property 'marktype' of undefined" multiple times. This error keeps coming again and again in the logs description, never stopping, like the error message is coming in an eternal loop.
Can anybody help me with that or give me a hint?

**Comment by domoritz** [comment]
Please add a link to the editor with the spec in it. Use the sharing dialog.

**Comment by danielp3011** [comment]
I figured out that there was something else wrong with my vega specification. Now I do not have the error anymore and cannot reproduce it. I will close this for now.

**Comment by danielp3011** [comment]
all right, I had the issue again. However it seems to happen on Chrome-Browser, while it does not happen on the chromium-based edge (beta version (I did not check other Edge versions yet)).
Here is the [link] (https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAB3GgBN6aABwAGNTPg0yWNADYNMnEgUKa4smlCY2ONAEZNIJm2xsEaAEzOANnAAzTDQAFmcAJx09VB8AXxkFJEwUVABtUHEkBDg0EGQcAH0oNjZw80zMOAhpEGIkXwYqtHSQTOzcpCYoGoAPNABaIQB2ByGAZkMHAQBOfRkATwGhyhCBFX0NhzG1aZkoBohK8LRnC32GBTgFR2M4SLZr9B9R-rUHGsTKk5kECWVUBwyCA0ABeOVQ0zUlC8AniGSy4JAlwCvTQQhUAm2MyGM0BIEWqHRIX0IWmAjU+mmKj2ByONxAZwal0eeJwd3YjxAzyGr3eCSS4Ocv3E-zxwLBjic0NhUnh7XQuhoqIBDkoY3WKhUswEawWA2mlB2Gy86p1NIYhzu3hkjIuV3pbPunO5vI+Au+eT+MHp4vBDilMNiAF0ZJhwkhxBAAqVPGkbPM2bk4D1KiKagEaHBfJy+kCdJlfLkesnMAVxG5y+FPHCQJgE4iS3A0zIM1nOYs82QC7l5iWyxWYyAa3XE+ho1WGL4UDIkNV0LmQMmcMd0P0nAACADU64AFJ8GAhKD1+sWU-3MJWEKk1EGAJQAKh3PgIO9PpfLF5jqQcQZPfY-l7Xnet5DrKtb1rk44IJO04gLOPY1EuK4gGuahbru+6HvM-S9meAFfjeD5PmoL64e+A5Vt+v5keegGESBw4QegjbNiArbZkWNTAl29RFiWoHxqOi4pk2wQtpmHHoB2IDcd2Un8cGNZtIi5yWuE1RAmwDDhFAiL5EUJRlBYAoabW4aRlBzSCYiSBkGQ4R8F8Mj2VpOBMASqQgKpdJBoxQlQTBNTwegymIT0y65AA5AAysw-QALJIOEADWcCYOukXoZhlDeVafkqWwvj+FAYkyaUwSoKA7GcrlxyxIpYGhegjocqZYjabpuT6cUpTlCZNRhhGUaDnG4FCbZ9mOTkznhK57nNCALUPCAvlgSOiIBVOQVzq0CJhRF6CRQAKjQ2TrktCgZVlSQHpQF1DqtcqIoNUCpQoBRMOZCimRIVlmToZBWugEAwGwshlntoZsHZ-i5MAymoOuINgxD2SUMpsQCf9dlA0iTC+PsNCvfaMgOb8pBoGGjTDpEOPIQoHhIBYBQQFmcAlSTtbQ2QsPoPDCKIwzyDM6zxWVAomMNU9uQQAeyDhNJ7U6XpSCFD1RkVE0obmcNVZ-etHR2Q5FBOWxEnfQtnzTUi7ohiAdhzp5CAWDUyB9L5j27fKi7EGwBSYKdWYWNbSudeg3WGX1lSmYNFkjS0BtjjQvh0jISG5BYnxIDukUvW9H1fRAkVSBlynF+u2XKQxa1MWbKdWmn4X0zdh62sy64ALwd+u7z5bkxRFezpViOEFVVebC2hbcTorfVntNbWMA0BAVtcVpytdarBm9cZ0cDTrlmjYndep8JB025gt1W533dQNpDkiqvUte4iy5wMQq+aR1Ktq5Hu9a2ZIah8E61wzPXY4jdz7ZWvl3dcd9wgP0wNffoSNKg4CfvPPaIUSyfzKt-Tev8d6axjgfeO1lILJ1PundA0CBQ3zgffUS19tyWnQe6Z+C8MzqSQe6L+G9w5b3VlHABsddaxhAf5ShDcz7N0voeGB3dnbiAwUpLBIApyHFwaHH+28Nb9W1kAshY0NpSIgTI3ItDKj0LdioxqajPoRgtnwsOeRBF-2IfvQxesj61wmsbXhIAXIMDch5F+s9MHewsEcHAhUAnaNyA45RJCvHiPIegXwJRkrBPTLNWMi9l64NSgSMJ4k2yOzCXbYKnl6DLxWgkQISBJxj3qjXISGS2BZPsC2XJuQ34fwCUU3IU8zZlMnntSp5S+l1KRA0pp1gWlpPUZk7J3SPBDJwQMuAxThnVXKaFCZk9+J22RI0lO8y+7pOWV0tiPSk7cMKVsoZkMRnZj2eMmc5SuGHGmScuZlUFnGNyO0zpOS1npNnDw02gyQrPN2WM9oBy0jqIhT82ZZz-kXKWR0lZNywWuMIXoveMhoWgFkrxdAA9SgADUko0E6LDeILyLajTJYWClhVqW0vpTkZ+x9NqwWCrWJKgNSwLmoSAE6Z0AB8DCEFMLoQAfnXDQAIe4W7oxLKwcQ5x26wMBBXdV4hNU9BLtlGpEAjy3nXIjHcKq1VyLug5YgWqdVXHofq7KfSjymvVeay1AAff1Zql4Wp6NXRZ-Ltq5GSOEEVBRpLislXAdcMr4GIOvkqu1ldNVtzdXqn1DqjUpkoPMAtt0-XzCtTarN6qvW5suvmz1TqS1lsPBW28gbg3LxLeGwFY4YyBQ+RnEUdwChiqbrkJNXcfAaHXEqrtobrUGodX6no6F7XluFWlMd-QF2WvXPedcnQIA7iTbu31IbKBW1vJwNBT9WkbQHVtId6AomjoTRO9AU6O4zrQvOi93b5hLr3UB7cG621btLNhEDVrD3HtPYHc9K7L3XtvXANhXxMVgKoZ+i+m7Y3brXQAQm7moLGfLTH7WQjWh118ZWaGXbdOt2qmR5u7h6gDFr63ut7Xyp9Aqdoxrjb6Kjk7A4ptlemxVyrVXZuLdx-NjHDxFswJQX0rbKB+t9FW3cNGmPNoU+xqQTb35qdBHADTWnzMdqDZxszYJeOgP41G19I7wgs3M6Jr9gdp0aD-UpzTl7fTAbs8FsDZrIMebBEh8tQXrMHqPUwE9Z692odYSou2rLHbS2BuZmlkRuU1DqA0REb73MiZkEwTO1gGTiBwAwCqMk2YlRqHYAOEhyllaiyHTzvlVHe0peEfLdL8bW2K40futJpFVeUTViw9XGuiyHq1nA7XIwLVqjUets9+uIgUPjQmxNrgyHG4KGQv1Rrv1EjtfbBNfBE2SjUYJq8aEHfu0dzcvcIl7cZiLZr4siv1Am+gGoM3HigEUBY374gWb-c5gvaKcAkqwHXOOdcAAhL664ADqcAkt0DgIjGo93vnoAACLQ6Cg1tgxQEA4H8F8dAv0AULyUbg07Jxdubx6OzoH4IZQ5ZknegJHOARc+BqDcGwzRfAEZRdloV2RQ7UO49mQz33Q0JbljRXmAdoAAEYlRNQCrp7GHESy4euLuCJUaAUxO3z+Z53JCXdIEr3IBu2BG9+BaK4YNJBq7NxYrXNYdc7XkMosGqBves2CSXcPDNZCoFsAwWATZjsgHV4zkAFuOFqOXgAQRt3bjPgf0BICL3AdGe0rcB2yPdo1gOSuO-ts7hXrvdfu8NyKKPWlWZsFIGYzPpWICF4DqQOdR6K8hbkdr9vc5SX5nJdbsfPKA8veX7bnl33o0AA1Wut9AKHrqvfED97gERkuyfYDk3P6b9fBep9KugPUOAOcejl3LyvwL3aw1LswHv3Pb2TAAATX3z+iP3DhPxv0vy0mvzPzvw1wZBH0fyRigBfxznmA-wr2-wtUrT-1AMANfj3yd3ALn2Px92gPXCvxgBvwQKzwfxXwn2f38DfywK-y9V-0RhwAAO32alAJIJd2u3INZkoOoNoLX0QIYM3yYLQJYMikwJLk-030dVMzwK4IIN4NaGIJb1IKEMgIoLPxgJTxoPgIkPoOQMYKf1kNf0inf0UOwJU33URnEB4Kt3EH4J0MELd30JEMMKoNgJMOLyHwzgsOkKsPQPkLYOUMcLUPXHcMtzsSAJDTJ2XlKlF2cHl0PzIJ8NP1ICMLgKCNLyQNHzCKRgAEdR4dwYlZBXwdxbx+h-8S4vArVtxqidx5g6iGjgCmjbwdNzUUjvlCDeknUBi0iHdUAMiD8fY9DPQDC8j-DjDxCS979Qjx8n8KjMAqiwZaj6juCej0I2iOjdjuj1xmjbwuCRjUiEjBcVNRjG9gdJjdDvDZjfD5ixDTDljJDVjk11jKi2iehOiXD9jWjtijj+h3CeidNbirihjmonVopigHJ7iztPC28Zjo9ciLMFiCjrZgjX1viJ8dwqid8Gid9YNdwAT6j-8WjdwcBgCujyT2jOiQDeiCA+lRj1xA11x+hpheS+Sl0+kETSgt83CSwhSkT7cm8JiBC0TniMTRCAili8TiiUCiSXDSTGTKSNT113CGSEsmSqTgDWToTDhOT-VuS+T+TnCxTESRTEjEQk0ttOQIB7tLgzF0jKtqtKpasFtchzJAYnSZZXTpElEPQ3Y0QgQ0EThDQHA5cpiICXjMT8jAjcSiipC1jdwlEdwbEBQS43ZszM5czzp4TbSJMVNxSfjdw015UrEUEoQBAEtBTbTOANitiajuDSTgTzpti6SujISdMdxqzH46Ftx6zD1yzmyIBWy2j1TGjTiaSZz6SQD+zeidNHSQ9sjEylSijZoGBlEENsh7wnA1Ab1jzriwkKVGFhzTYPTUSsi9CF8eI2UJVA5QJPis9dz9yk0GJNC+l2ALRecpTHivCO8ciFTFiPjlShzIU4A1x1wAAedcNnaTZCqxRGaCq2Ncc8heFTQCh4mU+8uUqAvw94wo9fDCgUT7CTHMqxJVGi5NdCq8mCz7bCtRCiyoFmMMCwKwSU4HEAMAkCnaeUyCoorOHOC6IuW8VIdiuAIMO6dkZaDch8mSRfZ8mSt85UsSyKCSyKKSmSuS+6WEkAHnNZMwxEF0omV-N8ECAi6Y5427E3MyoMyy18EsXtCAx8uSEAEEEoasJy9AVICMWAUoICddEyq8G8bko9bVUGcIICcknyjwRQmKkKyKsDcKqiKKoK2K+KhLRKhAIMVi72eYIWOg8y97V-MiGyu8uy0CvGO7B7Mq5y3Sdoty2fZS1lXIfKjSoowKlKuKn8ddEqjwUKlBbKkKn8BK3y5K4KgaoMIaoWTKsa-qqiKajwQqoynoeBZEtAcQScXwWyhMjEhPf3d88qly8Kn8q3eYba3i8EPaoqQ6zc46v3Jq4GCq9ooWK6+0ixLMZIHatITQG8J6vQloeJdAePMGAaWuYS4vbDXGIjHXNTJeIIAAaUeT2A6wPHBCpgsxcDSlkDgCbH1hhpPxOvTEo3QERvb2RpVUwHRsWBrHBrkEzihtDFJp92yUUjtk0r9wn1SBOqAhPDqJLjBMFp-HmsRmvCkBvCKsRHytsABoeoOpqoTMhsTwxJxWVNcDXS5IVrYDloSTYAXFF2VpBu8LBvXhcXVuhqElhutnhuQiRpBjpoZpqGKEjGxspnCEaEqwJqJqmOPhetkFOsdqTBppdrRseSZqtsRBtvZrtpPy5o9n8qRD5qVVSEpNFrqMlriP2vauePVp705uuWVOVsNpoVerut2v2vNrquDtOuVJ6COIrrgn6oBuluBtVs3NkHgCzDepAFSAsAH02NsPLkpNvBLmHruFHoUPXCONvA2s0O6uroBDrrDz7t8CI3TFKDDlxtTraNVA0H1SRsuBTiQGAMbO2IcDmHXFPr+qQHigeDgF6NboqzOsmyyBwGInXAICRhMHEFfC+pLn1WPJPIeiBGsOywvOMpqDBFmjQACHqFZgSEp29M6vnFKsZX9LjsUGUGurgbuANtQCQd8BQbTuFmd08qX2Gr8pABwdyG0F0GCCt0G1tsRCIV4lQcoZqyzgIV0WEVMmqkmwtDpGwYjADPQdTwG1EY8BZmkZ5VYY5XCC8HYdyE4cLG4aZioYvhSHxQEf-iEYnnQdUv7mUeG0KxaXoYkZUgFDIFKEZp+vBSYH7oTo4b0U0Yoe0d4aSD0dqiMbbBEbUjfIYe9L4YpSm3UgpsCZhXaBZzUV9HkZfzUfSWDiSg+DQdAHCf0aEUMeickmoefN9AsdGyHHEcsHBG-CkF-RTrgmLGgYDkwF5n4vO0iFEiNvcE8EgeSfnBqHskhyTx9rxoDlegAGEtI0xCQZApwXGyHchyM6BmnWs2nJn1FAhh5rCEIZoBn97awHtxm9yKoBBpnOgswdoIG1nAYkk-owE1LlGBpFnERYomAEokpUoO9WnMxVnaY9A05tVn6asIB5gEBXA5nvTRIgZx4ioAB5EwKAOgAkUAdIygWEKxmZs5mrPEmwfiKRnp5FWZ-JzkdFwseqUlu2eWZKBp2uSoFMRCf5y4TF0vbF2lkxp8-uJiq2TiyISwN8vob00XGENQRlRF2ocY7YIV8SIqGrUXQJByRxuuXwWF8vBF6V8YqEQMFsP4aKTzfl8Y480lzFGl0qAIW5LJ3x8Ov2WvIOBvRlMrJQimEh5BvGpsYoBl70rF2B3F5phcYR3p87AIAIVmI54VwFzZqSQlhCRlW51VqUkAAAYh1AEDfNuaVfhbrBjYeMoH0EZSNZq19cWgUuuANYfVyCCWuRNbBSqnLzShqwXkGmECHlKEzFMmyffktcDnr2tjLfmlicUZ+DeapbaWDlBVjDNf+vQHrcbbaeqEZRdYBfdaZc9dJTDdgdKUklgZDa9cRGknzflcOFmlSgzcRDjaYFPbfP3Y6TgGxzwe9F1alJlCFwPbgFTZVbvczdRbnity71KmPiBZBcKhHZ8fHdq2iViUwz+ddfBEPzczzeTjZWXbxbYbXfBxUrZfZQySGy5VKasZEy3ZlnMySdhmQ8BdMdyzBBKYZSsY9b5YQ+9YjdcyODHTfJFeYO3fo5A-fWTbg9DcQ-ueI9Za8sGwo77ZUolDw7I7gEI4duMcKfw-I6w8o8lcVbhdfYTiqEa0rgRC7itc7arzOi5MLOSBzjziuALkcSLhLkijLg0yrgBtjLAmRdhD60Nf4lWVHd0eHVA6nHA44-DAr0QadYg-neg7pG9OjbfePbGCi+Ta1Z1aRb1ZCCjb+FxyiDHlFdjdBaLdDBxfHhibCUZXqHzCPf7ghbqkq1nGtag-S74tcE6bKf8tABo5khXZ9eMd86Y83do7Y-4-a+kjYADaDaWEZVw667k8k9Y-Y66xEyjbg5ffTaPnU6D0LS047h0+Dj0+TQM+UV8eM78-zkSW+nLis4RHLk0+yGquRZUBrHSMUk-aAA)

**Comment by domoritz** [comment]
Please provide a minimal example that shows the problem. Thanks.
