### ISSUE TITLE
Editor dies when cannot bind to missing element (instead of previous behavior of warning)

### ISSUE THREAD

**Issue by davcraig75** [vega/editor#747]
It's helpful to be able to use the editor for development in instances where signals bind to elements in the originating page. If element is not on DOM, the rendering fails with _Cannot use 'in' operator to search for 'message' in Signal bind element not found: null_

Example below were code fails, rather than warns because #Palette3 does not exist in Vega Editor (but was in the originating page).  Not sure if this is vega.js issue or a vega-editor issue.  This is probably the reason for the other recent issue that was reported where pages fail in editor, but work in originating page.

{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "signals": [
    {
      "name": "Palette",
      "value": "category10",
      "bind": {
        "input": "select",
        "element": "#Palette3",
        "options": [
          "Viridis",
          "Magma"
        ]
      }
    }
  ],
  "data": [],

  "marks": [

  ]
}

**Comment by domoritz** [comment]
The editor doesn't have the element that the spec refers to so it's expected that the chart does not render. The editor UI does not crash and instead shows the error. 

If you want to change the behavior and render a chart regardless of this error, please suggest an enhancement for Vega.

**Comment by davcraig75** [comment]
I'll post the issue on vega.  What is strange is that the code below works in Vega deployment in VSCode - not sure how it didn't get triggered - but perhaps because it is at 5.12 of vega.

{
"$schema": "https://vega.github.io/schema/vega/v5.json",
"signals": [
{
"name": "Palette",
"value": "category10",
"bind": {
"input": "select",
"element":"#palette",
"options": [
"Viridis",
"Magma"
]
}
}
],
"data": [],

"marks": [
  {
      "type": "rect",
      "encode": {
        "enter": {
          "fill": {"value": "#939597"},
          "height":{"value":100},
          "width":{"value":100},
          "stroke": {"value": "#652c90"}
        }
      }
}

]
}

**Comment by domoritz** [comment]
Which vscode extension are you using?

**Comment by davcraig75** [comment]
Vega Viewer v9.0.0 - which I think you've contributed - and it uses 5.12.  Handy tool for vscode.
If I use it to view code with an element tag in the vega json, it draws the graphs & the element tag doesn't cause a failure to render. I'm guessing this would change if it were updated.

Should vega view it to be better to die when element tags aren't found - it pretty much makes the element tag problematic for vega-editor use.  I could always edit a fork of vega.js to catch it.

**Comment by domoritz** [comment]
cc @RandomFractals

**Comment by RandomFractals** [comment]
@davcraig75 VegaViewer is my creation & I am updating both vega & vega-lite libs & built-in examples today/tomorrow. Will check on the issue you ran into as I go through it. see here if you want to track it: https://github.com/RandomFractals/vscode-vega-viewer/issues/99
