### ISSUE TITLE
Auto popout autocompletion descriptions

### ISSUE THREAD

**Issue by grant** [vega/editor#832]
I'm trying to get autocompletion descriptions for the JSON Schema in https://vega.github.io/editor/ like I get with VS Code.

## Actual

Screenshot, no descriptions, must click arrow that appears on hover:

<img width="655" alt="Screen Shot 2020-10-15 at 23 09 33" src="https://user-images.githubusercontent.com/744973/96212114-9dcee080-0f3b-11eb-8f44-b7897536c778.png">

## Expected

The editor should automatically pop-up the autocompletion descriptions without me having to click any > button.
This is similar to VS Code's 

<img width="735" alt="Screen Shot 2020-10-15 at 23 11 16" src="https://user-images.githubusercontent.com/744973/96212183-c48d1700-0f3b-11eb-8be8-a3ba547e3250.png">

Or like VS Code:

![Screen Shot 2020-10-15 at 23 13 14](https://user-images.githubusercontent.com/744973/96212281-08801c00-0f3c-11eb-80a9-a5a4da8ea18d.png)

## Repro

https://vega.github.io/editor/

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json"
  
}
```

---

I'm not sure if this is a limitation of Monaco's feature set.

CC: @domoritz

**Comment by domoritz** [comment]
Hmm, I wonder whether there is a setting we are missing. I usually use ctl+space to trigger autocomplete and haven't noticed the difference between VSCode and the Vega editor yet. I just tried it and can confirm that there is a difference.

**Comment by domoritz** [comment]
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults also requires ctrl+space.

**Comment by grant** [comment]
The main issue is that there isn't the description after you ctrl+space.  You have to press the ">" once per session. It must be some state.

![dom](https://user-images.githubusercontent.com/744973/96213347-6a418580-0f3e-11eb-9119-86bdade08d23.gif)

**Comment by domoritz** [comment]
I looked through the API at https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html and haven't yet found a relevant setting. 

Here is where we initialize Monaco: https://github.com/vega/editor/blob/7d4568ccdaf4daa319c4d415d820e20e377f4f25/src/components/input-panel/spec-editor/renderer.tsx#L262. Let me know if you see a relevant config option.

**Comment by grant** [comment]
The UI is `.can-expand-details .details-label .readMore`.

Yup, it can be toggled with `Read More (^Space)`.

I'll investigate further. Thanks for helping :) feel free to close this issue.

**Comment by domoritz** [comment]
It looks like if I add `quickSuggestions: {other: true, comments: true, strings: true},` to the options, autocomplete triggers as soon as I type `"m`, which is already better.

So it does look like the defaults are not quite the same as in VSCode.

**Comment by domoritz** [comment]
Okay, I found a css bug where our description had this big header (visible in https://github.com/vega/editor/issues/832#issuecomment-709751417). That's fixed now. 

I don't see an option to auto open the description and my VSCode also doesn't open it by default either. You can run control+space when the suggestions list is visible to show the description and it stays open when the next suggestion list triggers.

**Comment by grant** [comment]
Interesting. (Note to self: I should really open a issue in monaco to explore further)

I can't seem to make the `quickSuggestions` option to work.

Full Repro:

https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults

Paste this js:

```js
// Configures two JSON schemas, with references.

var jsonCode = [
    '{',
    '    "message": {',
    '        "data": "foo"',
    '    }',
    "}"
].join('\n');
var modelUri = monaco.Uri.parse("a://b/foo.json"); // a made up unique URI for our model
var model = monaco.editor.createModel(jsonCode, "json", modelUri);

// configure the JSON language support with schemas and schema associations
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    validate: true,
    schemas: [{
        uri: "http://myserver/foo-schema.json", // id of the first schema
        fileMatch: [modelUri.toString()], // associate with our model
        schema:{
  "$id": "google.events.cloud.pubsub.v1",
  "$schema": "http://json-schema.org/schema",
  "title": "Cloud Pub/Sub Message v1",
  "name": "MessagePublishedData",
  "description": "A message that is published by publishers and consumed by subscribers.",
  "type": "object",
  "goPackage": "pubsubv1",
  "definitions": {
    "PubsubMessage": {
      "type": "object",
      "$comment": "https://cloud.google.com/pubsub/docs/reference/rest/v1/PubsubMessage",
      "description": "A message published to a topic.",
      "properties": {
        "data": {
          "description": "The message data field. If this field is empty, the message must contain at least one attribute. A base64-encoded string.",
          "type": "string",
          "format": "binary"
        },
        "attributes": {
          "description": "Attributes for this message. If this field is empty, the message must contain non-empty data. This can be used to filter messages on the subscription.",
          "type": "object"
        },
        "messageId": {
          "description": "ID of this message, assigned by the server when the message is published. Guaranteed to be unique within the topic. This value may be read by a subscriber that receives a PubsubMessage via a subscriptions.pull call or a push delivery. It must not be populated by the publisher in a topics.publish call.",
          "type": "string"
        }
      }
    }
  },
  "properties": {
    "message": {
      "$ref": "#/definitions/PubsubMessage",
      "description": "The message that was published."
    },
    "subscription": {
      "description": "The resource name of the subscription for which this event was generated. The format of the value is `projects/{project-id}/subscriptions/{subscription-id}`.",
      "type": "string"
    }
  }
}
    }, {
        uri: "http://myserver/bar-schema.json", // id of the second schema
        schema: {
            type: "object",
            properties: {
                q1: {
                    enum: ["x1", "x2"]
                }
            }
        }
    }]
});

monaco.editor.create(document.getElementById("container"), {
    model: model,
    quickSuggestions: true,
});
```

**Comment by domoritz** [comment]
Try https://vega.github.io/editor/ with version 0.91.1 (should be up in a few minutes).

**Comment by grant** [comment]
That formatting bug is gone! :)

**Comment by domoritz** [comment]
Yes, and also suggestions pup up when you type `"m` without you having to manually trigger it. Thanks for bringing up the issues!
