### ISSUE TITLE
Error thrown when using tooltips and dynamic data 

### ISSUE THREAD

**Issue by GrzegorzKazana** [vega/editor#885]
Hi 👋 

I came across an issue when using tooltips and dynamic data - it seemed to me it might be related to how the tooltips are handled in the editor, so I am opening the issue here - feel free to move it is not the right place.

### Expected behavior

When having tooltips enabled and using dynamic data - by defining `url` by a signal value (as described [here](https://vega.github.io/vega/docs/data/) - Dynamic Data Loading section), no errors should be thrown.

### Actual behavior

When enabling tooltips and using dynamic data, editor crashes with the following error
```
Cannot use 'in' operator to search for 'message' in Dataflow already running. Use runAsync() to chain invocations.
```

### Steps to reproduce

1. Enable tooltips: `Settings -> Tooltips` checkbox
2. Use specification with dynamic data, i.e.
```js
{
  "signals": [
    {
      "name": "testtest",
      "value": "https://jsonplaceholder.typicode.com/posts"
    }
  ],
  "data": [
    {
      "name": "baseData",
      "url": {"signal": "testtest"}
    }
  ]
}
```
3. Run the view (if not run automatically)
4. (An error is raised)
5. Disable the tooltips, and rerun the view
6. everything works fine

##### [Minimal reproduction (link to editor)](https://vega.github.io/editor/#/url/vega/N4Igzglg5gdghgGzCAXAbVPAtgU1SAFxzAKJJABoQA3RAVzxRAAtSAHMFAei4CswA9jDYI4AYxzMBCACY4ATgDoCATzYQxAuYs1YubASWQBfALpUZcAnFQYQ2RiABGcMDgAiVm1TryEqUEhYRHwyUmICEGMzYyA)

```
Versions
Vega: 5.17.0
Vega-Lite: 4.17.0
Vega-Tooltip: 0.24.2
Editor: 0.91.2

Chrome 87.0
Firefox 83.0
```

**Comment by domoritz** [comment]
Is this a problem with the Vega editor or Vega or Vega Tooltip?

**Comment by GrzegorzKazana** [comment]
It is difficult for me to say, thought it might be related how the tooltip is called from the editor app (?)
Feel free to correct me 🤷

**Comment by domoritz** [comment]
Could you try to reproduce the example without the editor? You can start with https://bl.ocks.org/domoritz/cd636b15fa0e187b51b73fc60b4d3014.

**Comment by GrzegorzKazana** [comment]
I have fiddled around in this codepen (https://codepen.io/GrzegorzKazana/pen/VwKzxyg?editors=0011)

I followed the error message and changed the way `vegaTooltip` is called. Option `1.` throws the error (the same as in the editor) and option `2.` does not
```js
const spec = { /* */ };

const runtime = vega.parse(spec);
const view = new vega.View(runtime);

// 1. - throws
view.runAsync();
vegaTooltip(view);

// 2. - does not throw
view.runAsync().then(() => vegaTooltip(view));
```

I have cloned the `vega-editor`, and changed `vegaTooltip` to be called in `.then` after `.runAsync` just like in the above example - it solves this error, however I am not sure is this is 100% correct

**Comment by domoritz** [comment]
Thank you for digging into the problem. It looks like we need to wait for the view to be initialized. I hope we can just await the view.runAsync call.

**Comment by GrzegorzKazana** [comment]
I might open a PR and we will see if the CI passes 😅

**Comment by domoritz** [comment]
<img width="831" alt="Screen Shot 2020-12-21 at 16 13 29" src="https://user-images.githubusercontent.com/589034/102791656-32025d00-435c-11eb-90e8-af412e312923.png">

Should fix it.
