### ISSUE TITLE
Cannot load editor in Safari: SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by marcprux** [vega/editor#888]
As of yesterday, https://vega.github.io/editor/ doesn't load in Safari Version 14.0.2 (16610.3.7.1.9) on macOS 11.1 (20C69). It works fine on Chrome and Firefox on macOS. The error in the console is:

```console
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
	(anonymous function) (vendor.js:88)
```

I don't know anything about `vendor.js`, but I'm guessing that some library implemented a regular expression that isn't supported by WebKit (i.e., Safari): https://stackoverflow.com/questions/641407/javascript-negative-lookbehind-equivalent/50434875#50434875

**Comment by domoritz** [comment]
Ah great. I'm looking into it.

**Comment by domoritz** [comment]
The error is happening in the dart language descriptions from VSCode. They are not really needed.

**Comment by domoritz** [comment]
Fixed in 0.92.1

**Comment by marcprux** [comment]
It's working again in Safari. Thanks for the super-quick fix!

**Comment by domoritz** [comment]
Thanks for the report. I would really like to know why it broke now since we never used dart.

**Comment by domoritz** [comment]
Oh, I think it was https://github.com/react-monaco-editor/react-monaco-editor/issues/322
