### ISSUE TITLE
Autocomplete slightly broken

### ISSUE THREAD

**Issue by domoritz** [vega/editor#99]
![moncao](https://user-images.githubusercontent.com/589034/40635376-90941c5a-62ae-11e8-9715-4d4a3bc49669.gif)

I can't quite figure out what the issue is. I don't have the same problem in VSCode so I suspect it has something to do with our setup. 

Maybe we should consider dropping React Monaco and add Monaco manually as in https://github.com/wasdk/WebAssemblyStudio/blob/master/src/components/editor/Editor.tsx.

To debug this, try to build a minimal react monaco setup (https://github.com/superRaytin/react-monaco-editor) and try to reproduce this issue.

**Comment by domoritz** [comment]
Another advantage of refactoring this is that we could provide the schema without requiring `$schema`. See https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults

**Comment by kanitw** [comment]
> we could provide the schema without requiring $schema. 

I wonder what should has higher precedence?  (In a way, if we have local VL schema, it's more up to date.  However, if users want to use older version of schema, then it should have higher precedence?)

**Comment by domoritz** [comment]
We actually don't load the schema but instead always use the latest one. See #33

**Comment by kanitw** [comment]
Oh can we make it load the latest VL then?

**Comment by domoritz** [comment]
That would need a JSON request service (#33). We use the schema from the installed vega-lite version. This is great for using the editor for development, btw.

**Comment by algomaster99** [comment]
@domoritz This doesn't seem to be a problem now.

**Comment by domoritz** [comment]
I still see it. Type `"color": {` and then enter.

**Comment by algomaster99** [comment]
@domoritz Can you share the specification? I'm unable to reproduce it.

**Comment by domoritz** [comment]
See the gif above. I start with the bar chart example.

**Comment by domoritz** [comment]
The example is https://vega.github.io/editor/#/examples/vega-lite/bar

**Comment by domoritz** [comment]
I fixed it.
