### ISSUE TITLE
Can't load a local data in Vega Editor

### ISSUE THREAD

**Issue by rafael78co** [vega/editor#997]
Hello 
I am trying to use the Vega Online Editor with a local data. I first created a localhost server at port 8080 in my computer from where to access the data and test that it works using a web browser  (http://localhost:8080/path/mydata.csv). Then I write the following code in the Online Editor: 

{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
   "description": "Create scatterplot.",
    "data": { "url":"http://localhost:8080/path/mydata.csv", "format": {"type": "csv"}},
    "mark":"tick",
    "encoding":{
        "x":{
            "field":"Sales",
            "type":"quantitative"
        }
    }
}

Then appear the following comment in the Logs: 

[Warning] Loading failed
[Warning] Infinite extent for field "Sales": [Infinity, -Infinity]

And nothing appear in the View 

Any help to solve this problem ? 
Best Regards 
Rafael

**Comment by domoritz** [comment]
Please check your browser console.

You have to make sure your server supports CORS. That's a restriction of browsers.

**Comment by domoritz** [comment]
Closing for now but feel free to comment.

**Comment by rafael78co** [comment]
you right, that is the problem. I will try yo enable CORS in the server. Thanks a lot.
